// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              unknown
// source: plugins/osvbng_tunnel.api.json

// Package osvbng_tunnel contains generated bindings for API file osvbng_tunnel.api.
//
// Contents:
// -  2 messages
package osvbng_tunnel

import (
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "osvbng_tunnel"
	APIVersion = "1.0.0"
	VersionCrc = 0x8efc2ab1
)

// Get the tunnel decap next indices for osvbng-tunnel-input
//
//	osvbng-tunnel-input is registered as a next node of vxlan4-input and
//	vxlan6-input at plugin init. Create a vxlan tunnel with the returned
//	value as decap_next_index and every decapsulated frame re-enters the
//	device-input feature arc for the tunnel sw_if_index, so l2gw / ipoe /
//	pppoe features armed on the tunnel behave exactly as on a physical
//	port; with no features armed frames continue into ethernet-input.
//
// OsvbngTunnelDecapNextGet defines message 'osvbng_tunnel_decap_next_get'.
type OsvbngTunnelDecapNextGet struct{}

func (m *OsvbngTunnelDecapNextGet) Reset()               { *m = OsvbngTunnelDecapNextGet{} }
func (*OsvbngTunnelDecapNextGet) GetMessageName() string { return "osvbng_tunnel_decap_next_get" }
func (*OsvbngTunnelDecapNextGet) GetCrcString() string   { return "51077d14" }
func (*OsvbngTunnelDecapNextGet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngTunnelDecapNextGet) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *OsvbngTunnelDecapNextGet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *OsvbngTunnelDecapNextGet) Unmarshal(b []byte) error {
	return nil
}

// Reply with the decap next indices
//   - retval - return code
//   - vxlan4_next - next index on vxlan4-input (~0 = vxlan plugin
//     not loaded)
//   - vxlan6_next - next index on vxlan6-input (~0 = vxlan plugin
//     not loaded)
//
// OsvbngTunnelDecapNextGetReply defines message 'osvbng_tunnel_decap_next_get_reply'.
type OsvbngTunnelDecapNextGetReply struct {
	Retval     int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	Vxlan4Next uint32 `binapi:"u32,name=vxlan4_next" json:"vxlan4_next,omitempty"`
	Vxlan6Next uint32 `binapi:"u32,name=vxlan6_next" json:"vxlan6_next,omitempty"`
}

func (m *OsvbngTunnelDecapNextGetReply) Reset() { *m = OsvbngTunnelDecapNextGetReply{} }
func (*OsvbngTunnelDecapNextGetReply) GetMessageName() string {
	return "osvbng_tunnel_decap_next_get_reply"
}
func (*OsvbngTunnelDecapNextGetReply) GetCrcString() string { return "ab860359" }
func (*OsvbngTunnelDecapNextGetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngTunnelDecapNextGetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	size += 4 // m.Vxlan4Next
	size += 4 // m.Vxlan6Next
	return size
}
func (m *OsvbngTunnelDecapNextGetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(m.Vxlan4Next)
	buf.EncodeUint32(m.Vxlan6Next)
	return buf.Bytes(), nil
}
func (m *OsvbngTunnelDecapNextGetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.Vxlan4Next = buf.DecodeUint32()
	m.Vxlan6Next = buf.DecodeUint32()
	return nil
}

func init() { file_osvbng_tunnel_binapi_init() }
func file_osvbng_tunnel_binapi_init() {
	api.RegisterMessage((*OsvbngTunnelDecapNextGet)(nil), "osvbng_tunnel_decap_next_get_51077d14")
	api.RegisterMessage((*OsvbngTunnelDecapNextGetReply)(nil), "osvbng_tunnel_decap_next_get_reply_ab860359")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*OsvbngTunnelDecapNextGet)(nil),
		(*OsvbngTunnelDecapNextGetReply)(nil),
	}
}
