// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              26.06-release
// source: plugins/l2tpv2.api.json

// Package l2tpv2 contains generated bindings for API file l2tpv2.api.
//
// Contents:
// - 14 messages
package l2tpv2

import (
	interface_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/interface_types"
	ip_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/ip_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "l2tpv2"
	APIVersion = "1.0.0"
	VersionCrc = 0x828eba4b
)

// Add or delete an L2TPv2 session.
//
//	Decap modes:
//	  0 (DECAP_IP)  — strip L2TP+PPP, dispatch to ip4-input or ip6-input
//	                   based on the PPP protocol field; RX sw_if_index is
//	                   set to the session's per-session vnet interface so
//	                   FIB lookup happens in the configured VRF.
//	  1 (DECAP_RAW) — strip L2TP only; forward the raw PPP frame to a
//	                   caller-specified graph node, with raw_opaque
//	                   stashed in vnet_buffer2(b) for downstream
//	                   correlation.
//	For DECAP_IP: decap_vrf_id and encap_if_index are required;
//	raw_next_node_name/raw_opaque are ignored.
//	For DECAP_RAW: raw_next_node_name and encap_if_index are required;
//	decap_vrf_id is ignored. raw_next_node_name is resolved to a graph
//	node index at session-add time; if the named node does not exist
//	the call returns VNET_API_ERROR_NO_SUCH_NODE.
//
// L2tpv2AddDelSession defines message 'l2tpv2_add_del_session'.
type L2tpv2AddDelSession struct {
	IsAdd           bool                           `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	LocalIP         ip_types.Address               `binapi:"address,name=local_ip" json:"local_ip,omitempty"`
	PeerIP          ip_types.Address               `binapi:"address,name=peer_ip" json:"peer_ip,omitempty"`
	LocalTunnelID   uint16                         `binapi:"u16,name=local_tunnel_id" json:"local_tunnel_id,omitempty"`
	LocalSessionID  uint16                         `binapi:"u16,name=local_session_id" json:"local_session_id,omitempty"`
	PeerSessionID   uint16                         `binapi:"u16,name=peer_session_id" json:"peer_session_id,omitempty"`
	DecapMode       uint8                          `binapi:"u8,name=decap_mode" json:"decap_mode,omitempty"`
	RawNextNodeName string                         `binapi:"string[64],name=raw_next_node_name" json:"raw_next_node_name,omitempty"`
	RawOpaque       uint32                         `binapi:"u32,name=raw_opaque" json:"raw_opaque,omitempty"`
	DecapVrfID      uint32                         `binapi:"u32,name=decap_vrf_id" json:"decap_vrf_id,omitempty"`
	EncapIfIndex    interface_types.InterfaceIndex `binapi:"interface_index,name=encap_if_index" json:"encap_if_index,omitempty"`
	PppHdrSkip      uint8                          `binapi:"u8,name=ppp_hdr_skip" json:"ppp_hdr_skip,omitempty"`
}

func (m *L2tpv2AddDelSession) Reset()               { *m = L2tpv2AddDelSession{} }
func (*L2tpv2AddDelSession) GetMessageName() string { return "l2tpv2_add_del_session" }
func (*L2tpv2AddDelSession) GetCrcString() string   { return "940ed15e" }
func (*L2tpv2AddDelSession) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *L2tpv2AddDelSession) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.IsAdd
	size += 1      // m.LocalIP.Af
	size += 1 * 16 // m.LocalIP.Un
	size += 1      // m.PeerIP.Af
	size += 1 * 16 // m.PeerIP.Un
	size += 2      // m.LocalTunnelID
	size += 2      // m.LocalSessionID
	size += 2      // m.PeerSessionID
	size += 1      // m.DecapMode
	size += 64     // m.RawNextNodeName
	size += 4      // m.RawOpaque
	size += 4      // m.DecapVrfID
	size += 4      // m.EncapIfIndex
	size += 1      // m.PppHdrSkip
	return size
}
func (m *L2tpv2AddDelSession) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint8(uint8(m.LocalIP.Af))
	buf.EncodeBytes(m.LocalIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(uint8(m.PeerIP.Af))
	buf.EncodeBytes(m.PeerIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint16(m.LocalTunnelID)
	buf.EncodeUint16(m.LocalSessionID)
	buf.EncodeUint16(m.PeerSessionID)
	buf.EncodeUint8(m.DecapMode)
	buf.EncodeString(m.RawNextNodeName, 64)
	buf.EncodeUint32(m.RawOpaque)
	buf.EncodeUint32(m.DecapVrfID)
	buf.EncodeUint32(uint32(m.EncapIfIndex))
	buf.EncodeUint8(m.PppHdrSkip)
	return buf.Bytes(), nil
}
func (m *L2tpv2AddDelSession) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.LocalIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.LocalIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.PeerIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.PeerIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.LocalTunnelID = buf.DecodeUint16()
	m.LocalSessionID = buf.DecodeUint16()
	m.PeerSessionID = buf.DecodeUint16()
	m.DecapMode = buf.DecodeUint8()
	m.RawNextNodeName = buf.DecodeString(64)
	m.RawOpaque = buf.DecodeUint32()
	m.DecapVrfID = buf.DecodeUint32()
	m.EncapIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.PppHdrSkip = buf.DecodeUint8()
	return nil
}

// L2tpv2AddDelSessionReply defines message 'l2tpv2_add_del_session_reply'.
type L2tpv2AddDelSessionReply struct {
	Retval    int32                          `binapi:"i32,name=retval" json:"retval,omitempty"`
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *L2tpv2AddDelSessionReply) Reset()               { *m = L2tpv2AddDelSessionReply{} }
func (*L2tpv2AddDelSessionReply) GetMessageName() string { return "l2tpv2_add_del_session_reply" }
func (*L2tpv2AddDelSessionReply) GetCrcString() string   { return "5383d31f" }
func (*L2tpv2AddDelSessionReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *L2tpv2AddDelSessionReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	size += 4 // m.SwIfIndex
	return size
}
func (m *L2tpv2AddDelSessionReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *L2tpv2AddDelSessionReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

// Add or delete an L2TPv2 tunnel.
//   - local_ip        - BNG-side endpoint address
//   - peer_ip         - remote endpoint address
//   - local_tunnel_id - ID we assigned (peer puts this on packets to us)
//   - peer_tunnel_id  - ID peer assigned us (we put this on packets to peer)
//   - local_udp_port  - local UDP port (1701 unless overridden)
//   - peer_udp_port   - peer UDP port (1701 unless overridden)
//   - df_bit          - set IP DF on egress (default false per RFC 2661 §4.4.5)
//
// L2tpv2AddDelTunnel defines message 'l2tpv2_add_del_tunnel'.
type L2tpv2AddDelTunnel struct {
	IsAdd         bool             `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	LocalIP       ip_types.Address `binapi:"address,name=local_ip" json:"local_ip,omitempty"`
	PeerIP        ip_types.Address `binapi:"address,name=peer_ip" json:"peer_ip,omitempty"`
	LocalTunnelID uint16           `binapi:"u16,name=local_tunnel_id" json:"local_tunnel_id,omitempty"`
	PeerTunnelID  uint16           `binapi:"u16,name=peer_tunnel_id" json:"peer_tunnel_id,omitempty"`
	LocalUDPPort  uint16           `binapi:"u16,name=local_udp_port" json:"local_udp_port,omitempty"`
	PeerUDPPort   uint16           `binapi:"u16,name=peer_udp_port" json:"peer_udp_port,omitempty"`
	DfBit         bool             `binapi:"bool,name=df_bit" json:"df_bit,omitempty"`
}

func (m *L2tpv2AddDelTunnel) Reset()               { *m = L2tpv2AddDelTunnel{} }
func (*L2tpv2AddDelTunnel) GetMessageName() string { return "l2tpv2_add_del_tunnel" }
func (*L2tpv2AddDelTunnel) GetCrcString() string   { return "9391f3fc" }
func (*L2tpv2AddDelTunnel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *L2tpv2AddDelTunnel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.IsAdd
	size += 1      // m.LocalIP.Af
	size += 1 * 16 // m.LocalIP.Un
	size += 1      // m.PeerIP.Af
	size += 1 * 16 // m.PeerIP.Un
	size += 2      // m.LocalTunnelID
	size += 2      // m.PeerTunnelID
	size += 2      // m.LocalUDPPort
	size += 2      // m.PeerUDPPort
	size += 1      // m.DfBit
	return size
}
func (m *L2tpv2AddDelTunnel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint8(uint8(m.LocalIP.Af))
	buf.EncodeBytes(m.LocalIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(uint8(m.PeerIP.Af))
	buf.EncodeBytes(m.PeerIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint16(m.LocalTunnelID)
	buf.EncodeUint16(m.PeerTunnelID)
	buf.EncodeUint16(m.LocalUDPPort)
	buf.EncodeUint16(m.PeerUDPPort)
	buf.EncodeBool(m.DfBit)
	return buf.Bytes(), nil
}
func (m *L2tpv2AddDelTunnel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.LocalIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.LocalIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.PeerIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.PeerIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.LocalTunnelID = buf.DecodeUint16()
	m.PeerTunnelID = buf.DecodeUint16()
	m.LocalUDPPort = buf.DecodeUint16()
	m.PeerUDPPort = buf.DecodeUint16()
	m.DfBit = buf.DecodeBool()
	return nil
}

// L2tpv2AddDelTunnelReply defines message 'l2tpv2_add_del_tunnel_reply'.
type L2tpv2AddDelTunnelReply struct {
	Retval      int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	TunnelIndex uint32 `binapi:"u32,name=tunnel_index" json:"tunnel_index,omitempty"`
}

func (m *L2tpv2AddDelTunnelReply) Reset()               { *m = L2tpv2AddDelTunnelReply{} }
func (*L2tpv2AddDelTunnelReply) GetMessageName() string { return "l2tpv2_add_del_tunnel_reply" }
func (*L2tpv2AddDelTunnelReply) GetCrcString() string   { return "eea9bee6" }
func (*L2tpv2AddDelTunnelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *L2tpv2AddDelTunnelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	size += 4 // m.TunnelIndex
	return size
}
func (m *L2tpv2AddDelTunnelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(m.TunnelIndex)
	return buf.Bytes(), nil
}
func (m *L2tpv2AddDelTunnelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.TunnelIndex = buf.DecodeUint32()
	return nil
}

// L2tpv2SessionDetails defines message 'l2tpv2_session_details'.
type L2tpv2SessionDetails struct {
	SwIfIndex       interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	TunnelIndex     uint32                         `binapi:"u32,name=tunnel_index" json:"tunnel_index,omitempty"`
	LocalIP         ip_types.Address               `binapi:"address,name=local_ip" json:"local_ip,omitempty"`
	PeerIP          ip_types.Address               `binapi:"address,name=peer_ip" json:"peer_ip,omitempty"`
	LocalTunnelID   uint16                         `binapi:"u16,name=local_tunnel_id" json:"local_tunnel_id,omitempty"`
	LocalSessionID  uint16                         `binapi:"u16,name=local_session_id" json:"local_session_id,omitempty"`
	PeerSessionID   uint16                         `binapi:"u16,name=peer_session_id" json:"peer_session_id,omitempty"`
	DecapMode       uint8                          `binapi:"u8,name=decap_mode" json:"decap_mode,omitempty"`
	RawNextNodeName string                         `binapi:"string[64],name=raw_next_node_name" json:"raw_next_node_name,omitempty"`
	RawOpaque       uint32                         `binapi:"u32,name=raw_opaque" json:"raw_opaque,omitempty"`
	DecapVrfID      uint32                         `binapi:"u32,name=decap_vrf_id" json:"decap_vrf_id,omitempty"`
	EncapIfIndex    interface_types.InterfaceIndex `binapi:"interface_index,name=encap_if_index" json:"encap_if_index,omitempty"`
	PppHdrSkip      uint8                          `binapi:"u8,name=ppp_hdr_skip" json:"ppp_hdr_skip,omitempty"`
}

func (m *L2tpv2SessionDetails) Reset()               { *m = L2tpv2SessionDetails{} }
func (*L2tpv2SessionDetails) GetMessageName() string { return "l2tpv2_session_details" }
func (*L2tpv2SessionDetails) GetCrcString() string   { return "4d67a69a" }
func (*L2tpv2SessionDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *L2tpv2SessionDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.SwIfIndex
	size += 4      // m.TunnelIndex
	size += 1      // m.LocalIP.Af
	size += 1 * 16 // m.LocalIP.Un
	size += 1      // m.PeerIP.Af
	size += 1 * 16 // m.PeerIP.Un
	size += 2      // m.LocalTunnelID
	size += 2      // m.LocalSessionID
	size += 2      // m.PeerSessionID
	size += 1      // m.DecapMode
	size += 64     // m.RawNextNodeName
	size += 4      // m.RawOpaque
	size += 4      // m.DecapVrfID
	size += 4      // m.EncapIfIndex
	size += 1      // m.PppHdrSkip
	return size
}
func (m *L2tpv2SessionDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeUint32(m.TunnelIndex)
	buf.EncodeUint8(uint8(m.LocalIP.Af))
	buf.EncodeBytes(m.LocalIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(uint8(m.PeerIP.Af))
	buf.EncodeBytes(m.PeerIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint16(m.LocalTunnelID)
	buf.EncodeUint16(m.LocalSessionID)
	buf.EncodeUint16(m.PeerSessionID)
	buf.EncodeUint8(m.DecapMode)
	buf.EncodeString(m.RawNextNodeName, 64)
	buf.EncodeUint32(m.RawOpaque)
	buf.EncodeUint32(m.DecapVrfID)
	buf.EncodeUint32(uint32(m.EncapIfIndex))
	buf.EncodeUint8(m.PppHdrSkip)
	return buf.Bytes(), nil
}
func (m *L2tpv2SessionDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.TunnelIndex = buf.DecodeUint32()
	m.LocalIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.LocalIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.PeerIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.PeerIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.LocalTunnelID = buf.DecodeUint16()
	m.LocalSessionID = buf.DecodeUint16()
	m.PeerSessionID = buf.DecodeUint16()
	m.DecapMode = buf.DecodeUint8()
	m.RawNextNodeName = buf.DecodeString(64)
	m.RawOpaque = buf.DecodeUint32()
	m.DecapVrfID = buf.DecodeUint32()
	m.EncapIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.PppHdrSkip = buf.DecodeUint8()
	return nil
}

// Dump configured sessions. sw_if_index = ~0 to dump all.
// L2tpv2SessionDump defines message 'l2tpv2_session_dump'.
type L2tpv2SessionDump struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *L2tpv2SessionDump) Reset()               { *m = L2tpv2SessionDump{} }
func (*L2tpv2SessionDump) GetMessageName() string { return "l2tpv2_session_dump" }
func (*L2tpv2SessionDump) GetCrcString() string   { return "f9e6675e" }
func (*L2tpv2SessionDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *L2tpv2SessionDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.SwIfIndex
	return size
}
func (m *L2tpv2SessionDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *L2tpv2SessionDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

// Set or clear a delegated prefix on a DECAP_IP session.
// L2tpv2SetDelegatedPrefix defines message 'l2tpv2_set_delegated_prefix'.
type L2tpv2SetDelegatedPrefix struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	Prefix    ip_types.Prefix                `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
	NextHop   ip_types.IP6Address            `binapi:"ip6_address,name=next_hop" json:"next_hop,omitempty"`
	IsAdd     bool                           `binapi:"bool,name=is_add" json:"is_add,omitempty"`
}

func (m *L2tpv2SetDelegatedPrefix) Reset()               { *m = L2tpv2SetDelegatedPrefix{} }
func (*L2tpv2SetDelegatedPrefix) GetMessageName() string { return "l2tpv2_set_delegated_prefix" }
func (*L2tpv2SetDelegatedPrefix) GetCrcString() string   { return "80a8a97d" }
func (*L2tpv2SetDelegatedPrefix) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *L2tpv2SetDelegatedPrefix) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.SwIfIndex
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	size += 1 * 16 // m.NextHop
	size += 1      // m.IsAdd
	return size
}
func (m *L2tpv2SetDelegatedPrefix) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	buf.EncodeBytes(m.NextHop[:], 16)
	buf.EncodeBool(m.IsAdd)
	return buf.Bytes(), nil
}
func (m *L2tpv2SetDelegatedPrefix) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	copy(m.NextHop[:], buf.DecodeBytes(16))
	m.IsAdd = buf.DecodeBool()
	return nil
}

// L2tpv2SetDelegatedPrefixReply defines message 'l2tpv2_set_delegated_prefix_reply'.
type L2tpv2SetDelegatedPrefixReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *L2tpv2SetDelegatedPrefixReply) Reset() { *m = L2tpv2SetDelegatedPrefixReply{} }
func (*L2tpv2SetDelegatedPrefixReply) GetMessageName() string {
	return "l2tpv2_set_delegated_prefix_reply"
}
func (*L2tpv2SetDelegatedPrefixReply) GetCrcString() string { return "e8d4e804" }
func (*L2tpv2SetDelegatedPrefixReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *L2tpv2SetDelegatedPrefixReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *L2tpv2SetDelegatedPrefixReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *L2tpv2SetDelegatedPrefixReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Set or clear the subscriber IPv4 binding on a DECAP_IP session.
// L2tpv2SetSessionIPv4 defines message 'l2tpv2_set_session_ipv4'.
type L2tpv2SetSessionIPv4 struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	ClientIP  ip_types.IP4Address            `binapi:"ip4_address,name=client_ip" json:"client_ip,omitempty"`
	IsAdd     bool                           `binapi:"bool,name=is_add" json:"is_add,omitempty"`
}

func (m *L2tpv2SetSessionIPv4) Reset()               { *m = L2tpv2SetSessionIPv4{} }
func (*L2tpv2SetSessionIPv4) GetMessageName() string { return "l2tpv2_set_session_ipv4" }
func (*L2tpv2SetSessionIPv4) GetCrcString() string   { return "e56ebcfd" }
func (*L2tpv2SetSessionIPv4) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *L2tpv2SetSessionIPv4) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4     // m.SwIfIndex
	size += 1 * 4 // m.ClientIP
	size += 1     // m.IsAdd
	return size
}
func (m *L2tpv2SetSessionIPv4) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeBytes(m.ClientIP[:], 4)
	buf.EncodeBool(m.IsAdd)
	return buf.Bytes(), nil
}
func (m *L2tpv2SetSessionIPv4) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	copy(m.ClientIP[:], buf.DecodeBytes(4))
	m.IsAdd = buf.DecodeBool()
	return nil
}

// L2tpv2SetSessionIPv4Reply defines message 'l2tpv2_set_session_ipv4_reply'.
type L2tpv2SetSessionIPv4Reply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *L2tpv2SetSessionIPv4Reply) Reset()               { *m = L2tpv2SetSessionIPv4Reply{} }
func (*L2tpv2SetSessionIPv4Reply) GetMessageName() string { return "l2tpv2_set_session_ipv4_reply" }
func (*L2tpv2SetSessionIPv4Reply) GetCrcString() string   { return "e8d4e804" }
func (*L2tpv2SetSessionIPv4Reply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *L2tpv2SetSessionIPv4Reply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *L2tpv2SetSessionIPv4Reply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *L2tpv2SetSessionIPv4Reply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Set or clear the subscriber IPv6 (IA_NA) binding on a DECAP_IP session.
// L2tpv2SetSessionIPv6 defines message 'l2tpv2_set_session_ipv6'.
type L2tpv2SetSessionIPv6 struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	ClientIP  ip_types.IP6Address            `binapi:"ip6_address,name=client_ip" json:"client_ip,omitempty"`
	IsAdd     bool                           `binapi:"bool,name=is_add" json:"is_add,omitempty"`
}

func (m *L2tpv2SetSessionIPv6) Reset()               { *m = L2tpv2SetSessionIPv6{} }
func (*L2tpv2SetSessionIPv6) GetMessageName() string { return "l2tpv2_set_session_ipv6" }
func (*L2tpv2SetSessionIPv6) GetCrcString() string   { return "aa625d9a" }
func (*L2tpv2SetSessionIPv6) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *L2tpv2SetSessionIPv6) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.SwIfIndex
	size += 1 * 16 // m.ClientIP
	size += 1      // m.IsAdd
	return size
}
func (m *L2tpv2SetSessionIPv6) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeBytes(m.ClientIP[:], 16)
	buf.EncodeBool(m.IsAdd)
	return buf.Bytes(), nil
}
func (m *L2tpv2SetSessionIPv6) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	copy(m.ClientIP[:], buf.DecodeBytes(16))
	m.IsAdd = buf.DecodeBool()
	return nil
}

// L2tpv2SetSessionIPv6Reply defines message 'l2tpv2_set_session_ipv6_reply'.
type L2tpv2SetSessionIPv6Reply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *L2tpv2SetSessionIPv6Reply) Reset()               { *m = L2tpv2SetSessionIPv6Reply{} }
func (*L2tpv2SetSessionIPv6Reply) GetMessageName() string { return "l2tpv2_set_session_ipv6_reply" }
func (*L2tpv2SetSessionIPv6Reply) GetCrcString() string   { return "e8d4e804" }
func (*L2tpv2SetSessionIPv6Reply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *L2tpv2SetSessionIPv6Reply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *L2tpv2SetSessionIPv6Reply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *L2tpv2SetSessionIPv6Reply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// L2tpv2TunnelDetails defines message 'l2tpv2_tunnel_details'.
type L2tpv2TunnelDetails struct {
	TunnelIndex   uint32           `binapi:"u32,name=tunnel_index" json:"tunnel_index,omitempty"`
	LocalIP       ip_types.Address `binapi:"address,name=local_ip" json:"local_ip,omitempty"`
	PeerIP        ip_types.Address `binapi:"address,name=peer_ip" json:"peer_ip,omitempty"`
	LocalTunnelID uint16           `binapi:"u16,name=local_tunnel_id" json:"local_tunnel_id,omitempty"`
	PeerTunnelID  uint16           `binapi:"u16,name=peer_tunnel_id" json:"peer_tunnel_id,omitempty"`
	LocalUDPPort  uint16           `binapi:"u16,name=local_udp_port" json:"local_udp_port,omitempty"`
	PeerUDPPort   uint16           `binapi:"u16,name=peer_udp_port" json:"peer_udp_port,omitempty"`
	DfBit         bool             `binapi:"bool,name=df_bit" json:"df_bit,omitempty"`
	RefCount      uint32           `binapi:"u32,name=ref_count" json:"ref_count,omitempty"`
}

func (m *L2tpv2TunnelDetails) Reset()               { *m = L2tpv2TunnelDetails{} }
func (*L2tpv2TunnelDetails) GetMessageName() string { return "l2tpv2_tunnel_details" }
func (*L2tpv2TunnelDetails) GetCrcString() string   { return "eb048f3b" }
func (*L2tpv2TunnelDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *L2tpv2TunnelDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.TunnelIndex
	size += 1      // m.LocalIP.Af
	size += 1 * 16 // m.LocalIP.Un
	size += 1      // m.PeerIP.Af
	size += 1 * 16 // m.PeerIP.Un
	size += 2      // m.LocalTunnelID
	size += 2      // m.PeerTunnelID
	size += 2      // m.LocalUDPPort
	size += 2      // m.PeerUDPPort
	size += 1      // m.DfBit
	size += 4      // m.RefCount
	return size
}
func (m *L2tpv2TunnelDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TunnelIndex)
	buf.EncodeUint8(uint8(m.LocalIP.Af))
	buf.EncodeBytes(m.LocalIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(uint8(m.PeerIP.Af))
	buf.EncodeBytes(m.PeerIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint16(m.LocalTunnelID)
	buf.EncodeUint16(m.PeerTunnelID)
	buf.EncodeUint16(m.LocalUDPPort)
	buf.EncodeUint16(m.PeerUDPPort)
	buf.EncodeBool(m.DfBit)
	buf.EncodeUint32(m.RefCount)
	return buf.Bytes(), nil
}
func (m *L2tpv2TunnelDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TunnelIndex = buf.DecodeUint32()
	m.LocalIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.LocalIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.PeerIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.PeerIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.LocalTunnelID = buf.DecodeUint16()
	m.PeerTunnelID = buf.DecodeUint16()
	m.LocalUDPPort = buf.DecodeUint16()
	m.PeerUDPPort = buf.DecodeUint16()
	m.DfBit = buf.DecodeBool()
	m.RefCount = buf.DecodeUint32()
	return nil
}

// Dump configured tunnels. tunnel_index = ~0 to dump all.
// L2tpv2TunnelDump defines message 'l2tpv2_tunnel_dump'.
type L2tpv2TunnelDump struct {
	TunnelIndex uint32 `binapi:"u32,name=tunnel_index" json:"tunnel_index,omitempty"`
}

func (m *L2tpv2TunnelDump) Reset()               { *m = L2tpv2TunnelDump{} }
func (*L2tpv2TunnelDump) GetMessageName() string { return "l2tpv2_tunnel_dump" }
func (*L2tpv2TunnelDump) GetCrcString() string   { return "d568a70b" }
func (*L2tpv2TunnelDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *L2tpv2TunnelDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.TunnelIndex
	return size
}
func (m *L2tpv2TunnelDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TunnelIndex)
	return buf.Bytes(), nil
}
func (m *L2tpv2TunnelDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TunnelIndex = buf.DecodeUint32()
	return nil
}

func init() { file_l2tpv2_binapi_init() }
func file_l2tpv2_binapi_init() {
	api.RegisterMessage((*L2tpv2AddDelSession)(nil), "l2tpv2_add_del_session_940ed15e")
	api.RegisterMessage((*L2tpv2AddDelSessionReply)(nil), "l2tpv2_add_del_session_reply_5383d31f")
	api.RegisterMessage((*L2tpv2AddDelTunnel)(nil), "l2tpv2_add_del_tunnel_9391f3fc")
	api.RegisterMessage((*L2tpv2AddDelTunnelReply)(nil), "l2tpv2_add_del_tunnel_reply_eea9bee6")
	api.RegisterMessage((*L2tpv2SessionDetails)(nil), "l2tpv2_session_details_4d67a69a")
	api.RegisterMessage((*L2tpv2SessionDump)(nil), "l2tpv2_session_dump_f9e6675e")
	api.RegisterMessage((*L2tpv2SetDelegatedPrefix)(nil), "l2tpv2_set_delegated_prefix_80a8a97d")
	api.RegisterMessage((*L2tpv2SetDelegatedPrefixReply)(nil), "l2tpv2_set_delegated_prefix_reply_e8d4e804")
	api.RegisterMessage((*L2tpv2SetSessionIPv4)(nil), "l2tpv2_set_session_ipv4_e56ebcfd")
	api.RegisterMessage((*L2tpv2SetSessionIPv4Reply)(nil), "l2tpv2_set_session_ipv4_reply_e8d4e804")
	api.RegisterMessage((*L2tpv2SetSessionIPv6)(nil), "l2tpv2_set_session_ipv6_aa625d9a")
	api.RegisterMessage((*L2tpv2SetSessionIPv6Reply)(nil), "l2tpv2_set_session_ipv6_reply_e8d4e804")
	api.RegisterMessage((*L2tpv2TunnelDetails)(nil), "l2tpv2_tunnel_details_eb048f3b")
	api.RegisterMessage((*L2tpv2TunnelDump)(nil), "l2tpv2_tunnel_dump_d568a70b")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*L2tpv2AddDelSession)(nil),
		(*L2tpv2AddDelSessionReply)(nil),
		(*L2tpv2AddDelTunnel)(nil),
		(*L2tpv2AddDelTunnelReply)(nil),
		(*L2tpv2SessionDetails)(nil),
		(*L2tpv2SessionDump)(nil),
		(*L2tpv2SetDelegatedPrefix)(nil),
		(*L2tpv2SetDelegatedPrefixReply)(nil),
		(*L2tpv2SetSessionIPv4)(nil),
		(*L2tpv2SetSessionIPv4Reply)(nil),
		(*L2tpv2SetSessionIPv6)(nil),
		(*L2tpv2SetSessionIPv6Reply)(nil),
		(*L2tpv2TunnelDetails)(nil),
		(*L2tpv2TunnelDump)(nil),
	}
}
