// Copyright 2026 The osvbng Authors
// Licensed under the GNU General Public License v3.0 or later.
// SPDX-License-Identifier: GPL-3.0-or-later

package l2tp

import (
	"crypto/md5"
	"crypto/rand"
	"errors"
)

// Challenge / Challenge-Response per RFC 2661 §5.1.1.
//
// The Challenge AVP carries a random sequence of bytes generated by
// the issuer. The peer computes the response as
//
//   MD5( message-type-byte || password || challenge )
//
// where message-type-byte is the Message Type of the message that
// carries the response — SCCRP (0x02) when the LNS replies to the
// LAC's SCCRQ challenge, SCCCN (0x03) when the LAC replies to the
// LNS's SCCRP challenge. Using the message-type byte as a prefix
// prevents replay of one message's response into another.

const (
	// ChallengeLen is the length of a generated Challenge AVP value.
	// RFC 2661 §5.1.1 leaves this implementation-defined; we follow
	// the de-facto 16-byte convention used by Cisco/Nokia.
	ChallengeLen = 16

	// ResponseLen is the length of an MD5-based Challenge Response.
	ResponseLen = md5.Size
)

var (
	ErrChallengeShort       = errors.New("l2tp: challenge response shorter than 16 bytes")
	ErrChallengeBadResponse = errors.New("l2tp: challenge response mismatch")
)

// NewChallenge returns ChallengeLen bytes of cryptographically random
// data suitable for use as the Challenge AVP value.
func NewChallenge() ([]byte, error) {
	b := make([]byte, ChallengeLen)
	if _, err := rand.Read(b); err != nil {
		return nil, err
	}
	return b, nil
}

// ComputeChallengeResponse derives the expected response per
// RFC 2661 §5.1.1. `messageTypeByte` is the low byte of the responding
// message's Message Type AVP value (e.g. SCCRP=2, SCCCN=3).
func ComputeChallengeResponse(messageTypeByte byte, password, challenge []byte) []byte {
	h := md5.New()
	h.Write([]byte{messageTypeByte})
	h.Write(password)
	h.Write(challenge)
	return h.Sum(nil)
}

// VerifyChallengeResponse compares an observed response against the
// expected value using a constant-time comparison.
func VerifyChallengeResponse(messageTypeByte byte, password, challenge, observed []byte) error {
	if len(observed) < ResponseLen {
		return ErrChallengeShort
	}
	expected := ComputeChallengeResponse(messageTypeByte, password, challenge)
	if !constantTimeEqual(expected, observed[:ResponseLen]) {
		return ErrChallengeBadResponse
	}
	return nil
}

// constantTimeEqual avoids depending on crypto/subtle for a 16-byte
// compare; the inputs are bounded length so the explicit loop is
// fine and lets us return early on a length mismatch without leaking
// timing on the common-case 16-vs-16 path.
func constantTimeEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	var diff byte
	for i := range a {
		diff |= a[i] ^ b[i]
	}
	return diff == 0
}
