// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package osvbng_srg

import (
	"context"
	"fmt"
	"io"

	memclnt "github.com/veesix-networks/osvbng/pkg/vpp/binapi/memclnt"
	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service osvbng_srg.
type RPCService interface {
	OsvbngSrgAddDel(ctx context.Context, in *OsvbngSrgAddDel) (*OsvbngSrgAddDelReply, error)
	OsvbngSrgCounterDump(ctx context.Context, in *OsvbngSrgCounterDump) (RPCService_OsvbngSrgCounterDumpClient, error)
	OsvbngSrgSendGarp(ctx context.Context, in *OsvbngSrgSendGarp) (*OsvbngSrgSendGarpReply, error)
	OsvbngSrgSetState(ctx context.Context, in *OsvbngSrgSetState) (*OsvbngSrgSetStateReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) OsvbngSrgAddDel(ctx context.Context, in *OsvbngSrgAddDel) (*OsvbngSrgAddDelReply, error) {
	out := new(OsvbngSrgAddDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngSrgCounterDump(ctx context.Context, in *OsvbngSrgCounterDump) (RPCService_OsvbngSrgCounterDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_OsvbngSrgCounterDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_OsvbngSrgCounterDumpClient interface {
	Recv() (*OsvbngSrgCounterDetails, error)
	api.Stream
}

type serviceClient_OsvbngSrgCounterDumpClient struct {
	api.Stream
}

func (c *serviceClient_OsvbngSrgCounterDumpClient) Recv() (*OsvbngSrgCounterDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *OsvbngSrgCounterDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) OsvbngSrgSendGarp(ctx context.Context, in *OsvbngSrgSendGarp) (*OsvbngSrgSendGarpReply, error) {
	out := new(OsvbngSrgSendGarpReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngSrgSetState(ctx context.Context, in *OsvbngSrgSetState) (*OsvbngSrgSetStateReply, error) {
	out := new(OsvbngSrgSetStateReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
