// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              26.02-release
// source: plugins/osvbng_srg.api.json

// Package osvbng_srg contains generated bindings for API file osvbng_srg.api.
//
// Contents:
// -  2 structs
// -  8 messages
package osvbng_srg

import (
	ethernet_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/ethernet_types"
	interface_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/interface_types"
	ip_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/ip_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "osvbng_srg"
	APIVersion = "1.0.0"
	VersionCrc = 0xf23daeb0
)

// OsvbngSrgCounters defines type 'osvbng_srg_counters'.
type OsvbngSrgCounters struct {
	SrgName    string `binapi:"string[64],name=srg_name" json:"srg_name,omitempty"`
	GarpSent   uint64 `binapi:"u64,name=garp_sent" json:"garp_sent,omitempty"`
	NaSent     uint64 `binapi:"u64,name=na_sent" json:"na_sent,omitempty"`
	MacAdds    uint64 `binapi:"u64,name=mac_adds" json:"mac_adds,omitempty"`
	MacRemoves uint64 `binapi:"u64,name=mac_removes" json:"mac_removes,omitempty"`
}

// OsvbngSrgGarpEntry defines type 'osvbng_srg_garp_entry'.
type OsvbngSrgGarpEntry struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	IPAddress ip_types.Address               `binapi:"address,name=ip_address" json:"ip_address,omitempty"`
}

// Register or deregister an SRG with virtual MAC and sub-interface list
//   - is_add - add SRG if true, delete if false
//   - srg_name - unique SRG name (up to 63 chars)
//   - virtual_mac - virtual MAC address for this SRG
//   - sw_if_count - number of sub-interfaces
//   - sw_if_indices - sub-interface indices belonging to this SRG
//
// OsvbngSrgAddDel defines message 'osvbng_srg_add_del'.
type OsvbngSrgAddDel struct {
	IsAdd       bool                             `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	SrgName     string                           `binapi:"string[64],name=srg_name" json:"srg_name,omitempty"`
	VirtualMac  ethernet_types.MacAddress        `binapi:"mac_address,name=virtual_mac" json:"virtual_mac,omitempty"`
	SwIfCount   uint32                           `binapi:"u32,name=sw_if_count" json:"-"`
	SwIfIndices []interface_types.InterfaceIndex `binapi:"interface_index[sw_if_count],name=sw_if_indices" json:"sw_if_indices,omitempty"`
}

func (m *OsvbngSrgAddDel) Reset()               { *m = OsvbngSrgAddDel{} }
func (*OsvbngSrgAddDel) GetMessageName() string { return "osvbng_srg_add_del" }
func (*OsvbngSrgAddDel) GetCrcString() string   { return "783dbea3" }
func (*OsvbngSrgAddDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngSrgAddDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1     // m.IsAdd
	size += 64    // m.SrgName
	size += 1 * 6 // m.VirtualMac
	size += 4     // m.SwIfCount
	for j1 := 0; j1 < len(m.SwIfIndices); j1++ {
		var s1 interface_types.InterfaceIndex
		_ = s1
		if j1 < len(m.SwIfIndices) {
			s1 = m.SwIfIndices[j1]
		}
		size += 4 // s1
	}
	return size
}
func (m *OsvbngSrgAddDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeString(m.SrgName, 64)
	buf.EncodeBytes(m.VirtualMac[:], 6)
	buf.EncodeUint32(uint32(len(m.SwIfIndices)))
	for j0 := 0; j0 < len(m.SwIfIndices); j0++ {
		var v0 interface_types.InterfaceIndex // SwIfIndices
		if j0 < len(m.SwIfIndices) {
			v0 = m.SwIfIndices[j0]
		}
		buf.EncodeUint32(uint32(v0))
	}
	return buf.Bytes(), nil
}
func (m *OsvbngSrgAddDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.SrgName = buf.DecodeString(64)
	copy(m.VirtualMac[:], buf.DecodeBytes(6))
	m.SwIfCount = buf.DecodeUint32()
	m.SwIfIndices = make([]interface_types.InterfaceIndex, m.SwIfCount)
	for j0 := 0; j0 < len(m.SwIfIndices); j0++ {
		m.SwIfIndices[j0] = interface_types.InterfaceIndex(buf.DecodeUint32())
	}
	return nil
}

// OsvbngSrgAddDelReply defines message 'osvbng_srg_add_del_reply'.
type OsvbngSrgAddDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngSrgAddDelReply) Reset()               { *m = OsvbngSrgAddDelReply{} }
func (*OsvbngSrgAddDelReply) GetMessageName() string { return "osvbng_srg_add_del_reply" }
func (*OsvbngSrgAddDelReply) GetCrcString() string   { return "e8d4e804" }
func (*OsvbngSrgAddDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngSrgAddDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngSrgAddDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngSrgAddDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Per-SRG counter details
//   - counters - counter values for one SRG
//
// OsvbngSrgCounterDetails defines message 'osvbng_srg_counter_details'.
type OsvbngSrgCounterDetails struct {
	Counters OsvbngSrgCounters `binapi:"osvbng_srg_counters,name=counters" json:"counters,omitempty"`
}

func (m *OsvbngSrgCounterDetails) Reset()               { *m = OsvbngSrgCounterDetails{} }
func (*OsvbngSrgCounterDetails) GetMessageName() string { return "osvbng_srg_counter_details" }
func (*OsvbngSrgCounterDetails) GetCrcString() string   { return "a2ecbc3a" }
func (*OsvbngSrgCounterDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngSrgCounterDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.Counters.SrgName
	size += 8  // m.Counters.GarpSent
	size += 8  // m.Counters.NaSent
	size += 8  // m.Counters.MacAdds
	size += 8  // m.Counters.MacRemoves
	return size
}
func (m *OsvbngSrgCounterDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Counters.SrgName, 64)
	buf.EncodeUint64(m.Counters.GarpSent)
	buf.EncodeUint64(m.Counters.NaSent)
	buf.EncodeUint64(m.Counters.MacAdds)
	buf.EncodeUint64(m.Counters.MacRemoves)
	return buf.Bytes(), nil
}
func (m *OsvbngSrgCounterDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Counters.SrgName = buf.DecodeString(64)
	m.Counters.GarpSent = buf.DecodeUint64()
	m.Counters.NaSent = buf.DecodeUint64()
	m.Counters.MacAdds = buf.DecodeUint64()
	m.Counters.MacRemoves = buf.DecodeUint64()
	return nil
}

// Dump per-SRG counters
//   - srg_name - specific SRG name (empty string for all)
//
// OsvbngSrgCounterDump defines message 'osvbng_srg_counter_dump'.
type OsvbngSrgCounterDump struct {
	SrgName string `binapi:"string[64],name=srg_name" json:"srg_name,omitempty"`
}

func (m *OsvbngSrgCounterDump) Reset()               { *m = OsvbngSrgCounterDump{} }
func (*OsvbngSrgCounterDump) GetMessageName() string { return "osvbng_srg_counter_dump" }
func (*OsvbngSrgCounterDump) GetCrcString() string   { return "d58aa7b4" }
func (*OsvbngSrgCounterDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngSrgCounterDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.SrgName
	return size
}
func (m *OsvbngSrgCounterDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.SrgName, 64)
	return buf.Bytes(), nil
}
func (m *OsvbngSrgCounterDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SrgName = buf.DecodeString(64)
	return nil
}

// Batch send GARP (IPv4) and unsolicited NA (IPv6) packets
//   - srg_name - SRG name (for counter attribution)
//   - count - number of entries
//   - entries - array of (sw_if_index, ip_address) pairs
//
// OsvbngSrgSendGarp defines message 'osvbng_srg_send_garp'.
type OsvbngSrgSendGarp struct {
	SrgName string               `binapi:"string[64],name=srg_name" json:"srg_name,omitempty"`
	Count   uint32               `binapi:"u32,name=count" json:"-"`
	Entries []OsvbngSrgGarpEntry `binapi:"osvbng_srg_garp_entry[count],name=entries" json:"entries,omitempty"`
}

func (m *OsvbngSrgSendGarp) Reset()               { *m = OsvbngSrgSendGarp{} }
func (*OsvbngSrgSendGarp) GetMessageName() string { return "osvbng_srg_send_garp" }
func (*OsvbngSrgSendGarp) GetCrcString() string   { return "421869a0" }
func (*OsvbngSrgSendGarp) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngSrgSendGarp) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.SrgName
	size += 4  // m.Count
	for j1 := 0; j1 < len(m.Entries); j1++ {
		var s1 OsvbngSrgGarpEntry
		_ = s1
		if j1 < len(m.Entries) {
			s1 = m.Entries[j1]
		}
		size += 4      // s1.SwIfIndex
		size += 1      // s1.IPAddress.Af
		size += 1 * 16 // s1.IPAddress.Un
	}
	return size
}
func (m *OsvbngSrgSendGarp) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.SrgName, 64)
	buf.EncodeUint32(uint32(len(m.Entries)))
	for j0 := 0; j0 < len(m.Entries); j0++ {
		var v0 OsvbngSrgGarpEntry // Entries
		if j0 < len(m.Entries) {
			v0 = m.Entries[j0]
		}
		buf.EncodeUint32(uint32(v0.SwIfIndex))
		buf.EncodeUint8(uint8(v0.IPAddress.Af))
		buf.EncodeBytes(v0.IPAddress.Un.XXX_UnionData[:], 16)
	}
	return buf.Bytes(), nil
}
func (m *OsvbngSrgSendGarp) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SrgName = buf.DecodeString(64)
	m.Count = buf.DecodeUint32()
	m.Entries = make([]OsvbngSrgGarpEntry, m.Count)
	for j0 := 0; j0 < len(m.Entries); j0++ {
		m.Entries[j0].SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
		m.Entries[j0].IPAddress.Af = ip_types.AddressFamily(buf.DecodeUint8())
		copy(m.Entries[j0].IPAddress.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	}
	return nil
}

// OsvbngSrgSendGarpReply defines message 'osvbng_srg_send_garp_reply'.
type OsvbngSrgSendGarpReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngSrgSendGarpReply) Reset()               { *m = OsvbngSrgSendGarpReply{} }
func (*OsvbngSrgSendGarpReply) GetMessageName() string { return "osvbng_srg_send_garp_reply" }
func (*OsvbngSrgSendGarpReply) GetCrcString() string   { return "e8d4e804" }
func (*OsvbngSrgSendGarpReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngSrgSendGarpReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngSrgSendGarpReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngSrgSendGarpReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Set SRG state to ACTIVE or STANDBY
//   - srg_name - SRG name
//   - is_active - true for ACTIVE (add vMAC), false for STANDBY (remove vMAC)
//
// OsvbngSrgSetState defines message 'osvbng_srg_set_state'.
type OsvbngSrgSetState struct {
	SrgName  string `binapi:"string[64],name=srg_name" json:"srg_name,omitempty"`
	IsActive bool   `binapi:"bool,name=is_active" json:"is_active,omitempty"`
}

func (m *OsvbngSrgSetState) Reset()               { *m = OsvbngSrgSetState{} }
func (*OsvbngSrgSetState) GetMessageName() string { return "osvbng_srg_set_state" }
func (*OsvbngSrgSetState) GetCrcString() string   { return "7cb41e5f" }
func (*OsvbngSrgSetState) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngSrgSetState) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.SrgName
	size += 1  // m.IsActive
	return size
}
func (m *OsvbngSrgSetState) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.SrgName, 64)
	buf.EncodeBool(m.IsActive)
	return buf.Bytes(), nil
}
func (m *OsvbngSrgSetState) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SrgName = buf.DecodeString(64)
	m.IsActive = buf.DecodeBool()
	return nil
}

// OsvbngSrgSetStateReply defines message 'osvbng_srg_set_state_reply'.
type OsvbngSrgSetStateReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngSrgSetStateReply) Reset()               { *m = OsvbngSrgSetStateReply{} }
func (*OsvbngSrgSetStateReply) GetMessageName() string { return "osvbng_srg_set_state_reply" }
func (*OsvbngSrgSetStateReply) GetCrcString() string   { return "e8d4e804" }
func (*OsvbngSrgSetStateReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngSrgSetStateReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngSrgSetStateReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngSrgSetStateReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

func init() { file_osvbng_srg_binapi_init() }
func file_osvbng_srg_binapi_init() {
	api.RegisterMessage((*OsvbngSrgAddDel)(nil), "osvbng_srg_add_del_783dbea3")
	api.RegisterMessage((*OsvbngSrgAddDelReply)(nil), "osvbng_srg_add_del_reply_e8d4e804")
	api.RegisterMessage((*OsvbngSrgCounterDetails)(nil), "osvbng_srg_counter_details_a2ecbc3a")
	api.RegisterMessage((*OsvbngSrgCounterDump)(nil), "osvbng_srg_counter_dump_d58aa7b4")
	api.RegisterMessage((*OsvbngSrgSendGarp)(nil), "osvbng_srg_send_garp_421869a0")
	api.RegisterMessage((*OsvbngSrgSendGarpReply)(nil), "osvbng_srg_send_garp_reply_e8d4e804")
	api.RegisterMessage((*OsvbngSrgSetState)(nil), "osvbng_srg_set_state_7cb41e5f")
	api.RegisterMessage((*OsvbngSrgSetStateReply)(nil), "osvbng_srg_set_state_reply_e8d4e804")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*OsvbngSrgAddDel)(nil),
		(*OsvbngSrgAddDelReply)(nil),
		(*OsvbngSrgCounterDetails)(nil),
		(*OsvbngSrgCounterDump)(nil),
		(*OsvbngSrgSendGarp)(nil),
		(*OsvbngSrgSendGarpReply)(nil),
		(*OsvbngSrgSetState)(nil),
		(*OsvbngSrgSetStateReply)(nil),
	}
}
