// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package fib_control

import (
	"context"

	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service fib_control.
type RPCService interface {
	FibControlAddHostRoute(ctx context.Context, in *FibControlAddHostRoute) (*FibControlAddHostRouteReply, error)
	FibControlAdjAddRewrite(ctx context.Context, in *FibControlAdjAddRewrite) (*FibControlAdjAddRewriteReply, error)
	FibControlAdjUnlock(ctx context.Context, in *FibControlAdjUnlock) (*FibControlAdjUnlockReply, error)
	FibControlDelHostRoute(ctx context.Context, in *FibControlDelHostRoute) (*FibControlDelHostRouteReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) FibControlAddHostRoute(ctx context.Context, in *FibControlAddHostRoute) (*FibControlAddHostRouteReply, error) {
	out := new(FibControlAddHostRouteReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) FibControlAdjAddRewrite(ctx context.Context, in *FibControlAdjAddRewrite) (*FibControlAdjAddRewriteReply, error) {
	out := new(FibControlAdjAddRewriteReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) FibControlAdjUnlock(ctx context.Context, in *FibControlAdjUnlock) (*FibControlAdjUnlockReply, error) {
	out := new(FibControlAdjUnlockReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) FibControlDelHostRoute(ctx context.Context, in *FibControlDelHostRoute) (*FibControlDelHostRouteReply, error) {
	out := new(FibControlDelHostRouteReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
