// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              25.10-release
// source: plugins/fib_control.api.json

// Package fib_control contains generated bindings for API file fib_control.api.
//
// Contents:
// -  8 messages
package fib_control

import (
	interface_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/interface_types"
	ip_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/ip_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "fib_control"
	APIVersion = "1.0.0"
	VersionCrc = 0x129370aa
)

// Add /32 or /128 host route using existing adjacency
//   - table_id - FIB table ID (0 for default)
//   - prefix - IP prefix (must be /32 for IPv4, /128 for IPv6)
//   - adj_index - adjacency index from fib_control_adj_add_rewrite
//   - sw_if_index - interface the route is attached to
//
// FibControlAddHostRoute defines message 'fib_control_add_host_route'.
type FibControlAddHostRoute struct {
	TableID   uint32                         `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	Prefix    ip_types.Prefix                `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
	AdjIndex  uint32                         `binapi:"u32,name=adj_index" json:"adj_index,omitempty"`
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *FibControlAddHostRoute) Reset()               { *m = FibControlAddHostRoute{} }
func (*FibControlAddHostRoute) GetMessageName() string { return "fib_control_add_host_route" }
func (*FibControlAddHostRoute) GetCrcString() string   { return "521bb980" }
func (*FibControlAddHostRoute) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *FibControlAddHostRoute) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.TableID
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	size += 4      // m.AdjIndex
	size += 4      // m.SwIfIndex
	return size
}
func (m *FibControlAddHostRoute) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	buf.EncodeUint32(m.AdjIndex)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *FibControlAddHostRoute) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TableID = buf.DecodeUint32()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	m.AdjIndex = buf.DecodeUint32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

// FibControlAddHostRouteReply defines message 'fib_control_add_host_route_reply'.
type FibControlAddHostRouteReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *FibControlAddHostRouteReply) Reset() { *m = FibControlAddHostRouteReply{} }
func (*FibControlAddHostRouteReply) GetMessageName() string {
	return "fib_control_add_host_route_reply"
}
func (*FibControlAddHostRouteReply) GetCrcString() string { return "e8d4e804" }
func (*FibControlAddHostRouteReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *FibControlAddHostRouteReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *FibControlAddHostRouteReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *FibControlAddHostRouteReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Add or lock neighbor adjacency with custom rewrite
//   - sw_if_index - interface for the adjacency
//   - nh_addr - next-hop IP address
//   - link_type - link type (0=ipv4, 1=ipv6)
//   - rewrite_len - length of rewrite data
//   - rewrite - L2 rewrite data (Ethernet + VLAN headers)
//
// FibControlAdjAddRewrite defines message 'fib_control_adj_add_rewrite'.
type FibControlAdjAddRewrite struct {
	SwIfIndex  interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	NhAddr     ip_types.Address               `binapi:"address,name=nh_addr" json:"nh_addr,omitempty"`
	LinkType   uint8                          `binapi:"u8,name=link_type" json:"link_type,omitempty"`
	RewriteLen uint8                          `binapi:"u8,name=rewrite_len" json:"rewrite_len,omitempty"`
	Rewrite    []byte                         `binapi:"u8[128],name=rewrite" json:"rewrite,omitempty"`
}

func (m *FibControlAdjAddRewrite) Reset()               { *m = FibControlAdjAddRewrite{} }
func (*FibControlAdjAddRewrite) GetMessageName() string { return "fib_control_adj_add_rewrite" }
func (*FibControlAdjAddRewrite) GetCrcString() string   { return "029fa7c2" }
func (*FibControlAdjAddRewrite) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *FibControlAdjAddRewrite) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4       // m.SwIfIndex
	size += 1       // m.NhAddr.Af
	size += 1 * 16  // m.NhAddr.Un
	size += 1       // m.LinkType
	size += 1       // m.RewriteLen
	size += 1 * 128 // m.Rewrite
	return size
}
func (m *FibControlAdjAddRewrite) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeUint8(uint8(m.NhAddr.Af))
	buf.EncodeBytes(m.NhAddr.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.LinkType)
	buf.EncodeUint8(m.RewriteLen)
	buf.EncodeBytes(m.Rewrite, 128)
	return buf.Bytes(), nil
}
func (m *FibControlAdjAddRewrite) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.NhAddr.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.NhAddr.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.LinkType = buf.DecodeUint8()
	m.RewriteLen = buf.DecodeUint8()
	m.Rewrite = make([]byte, 128)
	copy(m.Rewrite, buf.DecodeBytes(len(m.Rewrite)))
	return nil
}

// Reply for adjacency add with rewrite
//   - retval - return code
//   - adj_index - index of the created/locked adjacency
//
// FibControlAdjAddRewriteReply defines message 'fib_control_adj_add_rewrite_reply'.
type FibControlAdjAddRewriteReply struct {
	Retval   int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	AdjIndex uint32 `binapi:"u32,name=adj_index" json:"adj_index,omitempty"`
}

func (m *FibControlAdjAddRewriteReply) Reset() { *m = FibControlAdjAddRewriteReply{} }
func (*FibControlAdjAddRewriteReply) GetMessageName() string {
	return "fib_control_adj_add_rewrite_reply"
}
func (*FibControlAdjAddRewriteReply) GetCrcString() string { return "f660d70d" }
func (*FibControlAdjAddRewriteReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *FibControlAdjAddRewriteReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	size += 4 // m.AdjIndex
	return size
}
func (m *FibControlAdjAddRewriteReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(m.AdjIndex)
	return buf.Bytes(), nil
}
func (m *FibControlAdjAddRewriteReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.AdjIndex = buf.DecodeUint32()
	return nil
}

// Unlock neighbor adjacency
//   - adj_index - index returned from adj_add_rewrite
//
// FibControlAdjUnlock defines message 'fib_control_adj_unlock'.
type FibControlAdjUnlock struct {
	AdjIndex uint32 `binapi:"u32,name=adj_index" json:"adj_index,omitempty"`
}

func (m *FibControlAdjUnlock) Reset()               { *m = FibControlAdjUnlock{} }
func (*FibControlAdjUnlock) GetMessageName() string { return "fib_control_adj_unlock" }
func (*FibControlAdjUnlock) GetCrcString() string   { return "cb119b60" }
func (*FibControlAdjUnlock) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *FibControlAdjUnlock) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.AdjIndex
	return size
}
func (m *FibControlAdjUnlock) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.AdjIndex)
	return buf.Bytes(), nil
}
func (m *FibControlAdjUnlock) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.AdjIndex = buf.DecodeUint32()
	return nil
}

// FibControlAdjUnlockReply defines message 'fib_control_adj_unlock_reply'.
type FibControlAdjUnlockReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *FibControlAdjUnlockReply) Reset()               { *m = FibControlAdjUnlockReply{} }
func (*FibControlAdjUnlockReply) GetMessageName() string { return "fib_control_adj_unlock_reply" }
func (*FibControlAdjUnlockReply) GetCrcString() string   { return "e8d4e804" }
func (*FibControlAdjUnlockReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *FibControlAdjUnlockReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *FibControlAdjUnlockReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *FibControlAdjUnlockReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Delete /32 or /128 host route
//   - table_id - FIB table ID
//   - prefix - IP prefix to remove
//
// FibControlDelHostRoute defines message 'fib_control_del_host_route'.
type FibControlDelHostRoute struct {
	TableID uint32          `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	Prefix  ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
}

func (m *FibControlDelHostRoute) Reset()               { *m = FibControlDelHostRoute{} }
func (*FibControlDelHostRoute) GetMessageName() string { return "fib_control_del_host_route" }
func (*FibControlDelHostRoute) GetCrcString() string   { return "0f37725d" }
func (*FibControlDelHostRoute) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *FibControlDelHostRoute) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.TableID
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	return size
}
func (m *FibControlDelHostRoute) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	return buf.Bytes(), nil
}
func (m *FibControlDelHostRoute) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TableID = buf.DecodeUint32()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	return nil
}

// FibControlDelHostRouteReply defines message 'fib_control_del_host_route_reply'.
type FibControlDelHostRouteReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *FibControlDelHostRouteReply) Reset() { *m = FibControlDelHostRouteReply{} }
func (*FibControlDelHostRouteReply) GetMessageName() string {
	return "fib_control_del_host_route_reply"
}
func (*FibControlDelHostRouteReply) GetCrcString() string { return "e8d4e804" }
func (*FibControlDelHostRouteReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *FibControlDelHostRouteReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *FibControlDelHostRouteReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *FibControlDelHostRouteReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

func init() { file_fib_control_binapi_init() }
func file_fib_control_binapi_init() {
	api.RegisterMessage((*FibControlAddHostRoute)(nil), "fib_control_add_host_route_521bb980")
	api.RegisterMessage((*FibControlAddHostRouteReply)(nil), "fib_control_add_host_route_reply_e8d4e804")
	api.RegisterMessage((*FibControlAdjAddRewrite)(nil), "fib_control_adj_add_rewrite_029fa7c2")
	api.RegisterMessage((*FibControlAdjAddRewriteReply)(nil), "fib_control_adj_add_rewrite_reply_f660d70d")
	api.RegisterMessage((*FibControlAdjUnlock)(nil), "fib_control_adj_unlock_cb119b60")
	api.RegisterMessage((*FibControlAdjUnlockReply)(nil), "fib_control_adj_unlock_reply_e8d4e804")
	api.RegisterMessage((*FibControlDelHostRoute)(nil), "fib_control_del_host_route_0f37725d")
	api.RegisterMessage((*FibControlDelHostRouteReply)(nil), "fib_control_del_host_route_reply_e8d4e804")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*FibControlAddHostRoute)(nil),
		(*FibControlAddHostRouteReply)(nil),
		(*FibControlAdjAddRewrite)(nil),
		(*FibControlAdjAddRewriteReply)(nil),
		(*FibControlAdjUnlock)(nil),
		(*FibControlAdjUnlockReply)(nil),
		(*FibControlDelHostRoute)(nil),
		(*FibControlDelHostRouteReply)(nil),
	}
}
