# Copyright 2026 The osvbng Authors
# Licensed under the GNU General Public License v3.0 or later.
# SPDX-License-Identifier: GPL-3.0-or-later

*** Comments ***
End-to-end TLS verification for the northbound REST API listener
(osvbng-context #45). Spins up a single BNG with the API on :8443 and
mTLS configured (client_auth: require). Self-signed CA + server cert +
client cert are generated by gen_certs.sh at suite setup.

Run:
  scripts/run-qa-tests.sh -t 28-northbound-api-tls -r 1

*** Settings ***
Library             OperatingSystem
Library             String
Library             Process
Resource            ../common.robot

Suite Setup         Deploy TLS Topology
Suite Teardown      Teardown TLS Topology

*** Variables ***
${lab-name}         osvbng-northbound-api-tls
${lab-file}         ${CURDIR}/28-northbound-api-tls.clab.yml
${bng1}             clab-${lab-name}-bng1
${cert-dir}         ${CURDIR}/config/certs
${api-port}         8443

*** Keywords ***
Deploy TLS Topology
    ${rc}    ${output} =    Run And Return Rc And Output    bash ${CURDIR}/gen_certs.sh
    Should Be Equal As Integers    ${rc}    0    cert generation failed: ${output}
    Deploy Topology    ${lab-file}
    Wait For osvbng Healthy Over mTLS    bng1    ${lab-name}

Teardown TLS Topology
    Destroy Topology    ${lab-file}

Wait For osvbng Healthy Over mTLS
    [Arguments]    ${node}    ${lab_name}
    ${container} =    Set Variable    clab-${lab_name}-${node}
    Wait Until Keyword Succeeds    ${HEALTH_RETRIES} x    ${HEALTH_INTERVAL}
    ...    Check osvbng Started    ${container}
    Wait Until Keyword Succeeds    ${HEALTH_RETRIES} x    ${HEALTH_INTERVAL}
    ...    Check API Reachable Over mTLS    ${container}

Check API Reachable Over mTLS
    [Arguments]    ${container}
    ${ip} =    Get Container IPv4    ${container}
    ${rc}    ${output} =    Run And Return Rc And Output
    ...    curl -sf --resolve bng1:${api-port}:${ip} --cacert ${cert-dir}/ca.crt --cert ${cert-dir}/client.crt --key ${cert-dir}/client.key https://bng1:${api-port}/api/show/system/version
    Should Be Equal As Integers    ${rc}    0    API not reachable over mTLS yet: ${output}

*** Test Cases ***

HTTPS With Valid Client Cert Succeeds
    [Documentation]    mTLS handshake completes; an authenticated request returns the version envelope.
    ${ip} =    Get Container IPv4    ${bng1}
    ${rc}    ${output} =    Run And Return Rc And Output
    ...    curl -sf --resolve bng1:${api-port}:${ip} --cacert ${cert-dir}/ca.crt --cert ${cert-dir}/client.crt --key ${cert-dir}/client.key https://bng1:${api-port}/api/show/system/version
    Should Be Equal As Integers    ${rc}    0    ${output}
    Should Contain    ${output}    "path"
    Should Contain    ${output}    system.version

Plain HTTP Is Refused
    [Documentation]    Listener is HTTPS only; plain HTTP request must not succeed.
    ${ip} =    Get Container IPv4    ${bng1}
    ${rc}    ${output} =    Run And Return Rc And Output
    ...    curl -s --max-time 5 -o /dev/null -w '\%{http_code}' http://${ip}:${api-port}/api/show/system/version
    Should Not Be Equal As Strings    ${output}    200    plain HTTP unexpectedly succeeded

HTTPS Without Client Cert Is Rejected
    [Documentation]    With client_auth=require, a TLS handshake without a client cert fails.
    ${ip} =    Get Container IPv4    ${bng1}
    ${rc}    ${output} =    Run And Return Rc And Output
    ...    curl -s --max-time 5 --cacert ${cert-dir}/ca.crt -o /dev/null -w '\%{http_code}' --resolve bng1:${api-port}:${ip} https://bng1:${api-port}/api/show/system/version
    Should Not Be Equal As Strings    ${output}    200    request without client cert unexpectedly succeeded

HTTPS With Untrusted CA Is Rejected
    [Documentation]    Server cert is signed by the test CA only; a client trusting a different CA must fail.
    ${ip} =    Get Container IPv4    ${bng1}
    ${rc}    ${output} =    Run And Return Rc And Output
    ...    curl -s --max-time 5 --cacert /etc/ssl/certs/ca-certificates.crt --cert ${cert-dir}/client.crt --key ${cert-dir}/client.key -o /dev/null -w '\%{http_code}' --resolve bng1:${api-port}:${ip} https://bng1:${api-port}/api/show/system/version
    Should Not Be Equal As Strings    ${output}    200    request with untrusted CA unexpectedly succeeded

TLS Min Version Is 1.3
    [Documentation]    Spec mandates TLS 1.3 default; a TLS 1.2-only handshake must fail.
    ${ip} =    Get Container IPv4    ${bng1}
    ${rc}    ${output} =    Run And Return Rc And Output
    ...    curl -s --max-time 5 --tls-max 1.2 --tlsv1.2 --cacert ${cert-dir}/ca.crt --cert ${cert-dir}/client.crt --key ${cert-dir}/client.key -o /dev/null -w '\%{http_code}' --resolve bng1:${api-port}:${ip} https://bng1:${api-port}/api/show/system/version
    Should Not Be Equal As Strings    ${output}    200    TLS 1.2 unexpectedly succeeded
