name: Bug Report
description: Report a bug
labels:
  - bug

body:
  - type: textarea
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: Output of `osvbngd --version`
      placeholder: "v0.1.0"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Logs, config snippets, screenshots, etc.
    validations:
      required: false
