name: Feature Request
description: Suggest a new feature
labels:
  - enhancement

body:
  - type: textarea
    attributes:
      label: Description
      description: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: Why do you need this? What problem does it solve?
    validations:
      required: false
