// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package osvbng_qos_sched

import (
	"context"
	"fmt"
	"io"

	memclnt "github.com/veesix-networks/osvbng/pkg/vpp/binapi/memclnt"
	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service osvbng_qos_sched.
type RPCService interface {
	OsvbngCakeSchedDump(ctx context.Context, in *OsvbngCakeSchedDump) (RPCService_OsvbngCakeSchedDumpClient, error)
	OsvbngCakeSchedEnableDisable(ctx context.Context, in *OsvbngCakeSchedEnableDisable) (*OsvbngCakeSchedEnableDisableReply, error)
	OsvbngCakeSchedResetStats(ctx context.Context, in *OsvbngCakeSchedResetStats) (*OsvbngCakeSchedResetStatsReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) OsvbngCakeSchedDump(ctx context.Context, in *OsvbngCakeSchedDump) (RPCService_OsvbngCakeSchedDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_OsvbngCakeSchedDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_OsvbngCakeSchedDumpClient interface {
	Recv() (*OsvbngCakeSchedDetails, error)
	api.Stream
}

type serviceClient_OsvbngCakeSchedDumpClient struct {
	api.Stream
}

func (c *serviceClient_OsvbngCakeSchedDumpClient) Recv() (*OsvbngCakeSchedDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *OsvbngCakeSchedDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) OsvbngCakeSchedEnableDisable(ctx context.Context, in *OsvbngCakeSchedEnableDisable) (*OsvbngCakeSchedEnableDisableReply, error) {
	out := new(OsvbngCakeSchedEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCakeSchedResetStats(ctx context.Context, in *OsvbngCakeSchedResetStats) (*OsvbngCakeSchedResetStatsReply, error) {
	out := new(OsvbngCakeSchedResetStatsReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
