// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              25.10-release
// source: plugins/osvbng_qos_sched.api.json

// Package osvbng_qos_sched contains generated bindings for API file osvbng_qos_sched.api.
//
// Contents:
// -  3 enums
// -  6 messages
package osvbng_qos_sched

import (
	"strconv"

	interface_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/interface_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "osvbng_qos_sched"
	APIVersion = "1.0.0"
	VersionCrc = 0x5b1aa9e6
)

// OsvbngCakeAtmMode defines enum 'osvbng_cake_atm_mode'.
type OsvbngCakeAtmMode uint8

const (
	OSVBNG_CAKE_ATM_NONE OsvbngCakeAtmMode = 0
	OSVBNG_CAKE_ATM_ATM  OsvbngCakeAtmMode = 1
	OSVBNG_CAKE_ATM_PTM  OsvbngCakeAtmMode = 2
)

var (
	OsvbngCakeAtmMode_name = map[uint8]string{
		0: "OSVBNG_CAKE_ATM_NONE",
		1: "OSVBNG_CAKE_ATM_ATM",
		2: "OSVBNG_CAKE_ATM_PTM",
	}
	OsvbngCakeAtmMode_value = map[string]uint8{
		"OSVBNG_CAKE_ATM_NONE": 0,
		"OSVBNG_CAKE_ATM_ATM":  1,
		"OSVBNG_CAKE_ATM_PTM":  2,
	}
)

func (x OsvbngCakeAtmMode) String() string {
	s, ok := OsvbngCakeAtmMode_name[uint8(x)]
	if ok {
		return s
	}
	return "OsvbngCakeAtmMode(" + strconv.Itoa(int(x)) + ")"
}

// OsvbngCakeFlags defines enum 'osvbng_cake_flags'.
type OsvbngCakeFlags uint32

const (
	OSVBNG_CAKE_FLAG_NONE       OsvbngCakeFlags = 0
	OSVBNG_CAKE_FLAG_WASH_DSCP  OsvbngCakeFlags = 1
	OSVBNG_CAKE_FLAG_ACK_FILTER OsvbngCakeFlags = 2
	OSVBNG_CAKE_FLAG_SPLIT_GSO  OsvbngCakeFlags = 4
)

var (
	OsvbngCakeFlags_name = map[uint32]string{
		0: "OSVBNG_CAKE_FLAG_NONE",
		1: "OSVBNG_CAKE_FLAG_WASH_DSCP",
		2: "OSVBNG_CAKE_FLAG_ACK_FILTER",
		4: "OSVBNG_CAKE_FLAG_SPLIT_GSO",
	}
	OsvbngCakeFlags_value = map[string]uint32{
		"OSVBNG_CAKE_FLAG_NONE":       0,
		"OSVBNG_CAKE_FLAG_WASH_DSCP":  1,
		"OSVBNG_CAKE_FLAG_ACK_FILTER": 2,
		"OSVBNG_CAKE_FLAG_SPLIT_GSO":  4,
	}
)

func (x OsvbngCakeFlags) String() string {
	s, ok := OsvbngCakeFlags_name[uint32(x)]
	if ok {
		return s
	}
	str := func(n uint32) string {
		s, ok := OsvbngCakeFlags_name[uint32(n)]
		if ok {
			return s
		}
		return "OsvbngCakeFlags(" + strconv.Itoa(int(n)) + ")"
	}
	for i := uint32(0); i <= 32; i++ {
		val := uint32(x)
		if val&(1<<i) != 0 {
			if s != "" {
				s += "|"
			}
			s += str(1 << i)
		}
	}
	if s == "" {
		return str(uint32(x))
	}
	return s
}

// OsvbngCakeTinMode defines enum 'osvbng_cake_tin_mode'.
type OsvbngCakeTinMode uint8

const (
	OSVBNG_CAKE_TIN_MODE_BESTEFFORT OsvbngCakeTinMode = 0
	OSVBNG_CAKE_TIN_MODE_DIFFSERV3  OsvbngCakeTinMode = 1
	OSVBNG_CAKE_TIN_MODE_DIFFSERV4  OsvbngCakeTinMode = 2
	OSVBNG_CAKE_TIN_MODE_DIFFSERV8  OsvbngCakeTinMode = 3
)

var (
	OsvbngCakeTinMode_name = map[uint8]string{
		0: "OSVBNG_CAKE_TIN_MODE_BESTEFFORT",
		1: "OSVBNG_CAKE_TIN_MODE_DIFFSERV3",
		2: "OSVBNG_CAKE_TIN_MODE_DIFFSERV4",
		3: "OSVBNG_CAKE_TIN_MODE_DIFFSERV8",
	}
	OsvbngCakeTinMode_value = map[string]uint8{
		"OSVBNG_CAKE_TIN_MODE_BESTEFFORT": 0,
		"OSVBNG_CAKE_TIN_MODE_DIFFSERV3":  1,
		"OSVBNG_CAKE_TIN_MODE_DIFFSERV4":  2,
		"OSVBNG_CAKE_TIN_MODE_DIFFSERV8":  3,
	}
)

func (x OsvbngCakeTinMode) String() string {
	s, ok := OsvbngCakeTinMode_name[uint8(x)]
	if ok {
		return s
	}
	return "OsvbngCakeTinMode(" + strconv.Itoa(int(x)) + ")"
}

// Per-subscriber scheduler details (response to dump)
//   - sw_if_index - subscriber interface
//   - rate_bytes_per_sec - configured shaping rate
//   - tin_mode - active tin mode
//   - tin_cnt - number of active tins
//   - buffer_usage - current bytes queued across all tins
//   - buffer_limit - maximum buffer bytes
//   - tin_packets - per-tin packet counters (up to 8)
//   - tin_bytes - per-tin byte counters
//   - tin_drops - per-tin AQM + overflow drop counters
//   - tin_ecn_marks - per-tin ECN CE mark counters
//   - tin_peak_delay_us - per-tin peak sojourn time (microseconds)
//   - tin_avg_delay_us - per-tin average sojourn time (microseconds)
//   - tin_sparse_flows - per-tin count of flows in sparse state
//   - tin_bulk_flows - per-tin count of flows in bulk state
//
// OsvbngCakeSchedDetails defines message 'osvbng_cake_sched_details'.
type OsvbngCakeSchedDetails struct {
	SwIfIndex       interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	RateBytesPerSec uint64                         `binapi:"u64,name=rate_bytes_per_sec" json:"rate_bytes_per_sec,omitempty"`
	TinMode         OsvbngCakeTinMode              `binapi:"osvbng_cake_tin_mode,name=tin_mode" json:"tin_mode,omitempty"`
	TinCnt          uint8                          `binapi:"u8,name=tin_cnt" json:"tin_cnt,omitempty"`
	BufferUsage     uint32                         `binapi:"u32,name=buffer_usage" json:"buffer_usage,omitempty"`
	BufferLimit     uint32                         `binapi:"u32,name=buffer_limit" json:"buffer_limit,omitempty"`
	TinPackets      []uint64                       `binapi:"u64[8],name=tin_packets" json:"tin_packets,omitempty"`
	TinBytes        []uint64                       `binapi:"u64[8],name=tin_bytes" json:"tin_bytes,omitempty"`
	TinDrops        []uint64                       `binapi:"u64[8],name=tin_drops" json:"tin_drops,omitempty"`
	TinEcnMarks     []uint64                       `binapi:"u64[8],name=tin_ecn_marks" json:"tin_ecn_marks,omitempty"`
	TinPeakDelayUs  []uint32                       `binapi:"u32[8],name=tin_peak_delay_us" json:"tin_peak_delay_us,omitempty"`
	TinAvgDelayUs   []uint32                       `binapi:"u32[8],name=tin_avg_delay_us" json:"tin_avg_delay_us,omitempty"`
	TinSparseFlows  []uint32                       `binapi:"u32[8],name=tin_sparse_flows" json:"tin_sparse_flows,omitempty"`
	TinBulkFlows    []uint32                       `binapi:"u32[8],name=tin_bulk_flows" json:"tin_bulk_flows,omitempty"`
}

func (m *OsvbngCakeSchedDetails) Reset()               { *m = OsvbngCakeSchedDetails{} }
func (*OsvbngCakeSchedDetails) GetMessageName() string { return "osvbng_cake_sched_details" }
func (*OsvbngCakeSchedDetails) GetCrcString() string   { return "9939f302" }
func (*OsvbngCakeSchedDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCakeSchedDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4     // m.SwIfIndex
	size += 8     // m.RateBytesPerSec
	size += 1     // m.TinMode
	size += 1     // m.TinCnt
	size += 4     // m.BufferUsage
	size += 4     // m.BufferLimit
	size += 8 * 8 // m.TinPackets
	size += 8 * 8 // m.TinBytes
	size += 8 * 8 // m.TinDrops
	size += 8 * 8 // m.TinEcnMarks
	size += 4 * 8 // m.TinPeakDelayUs
	size += 4 * 8 // m.TinAvgDelayUs
	size += 4 * 8 // m.TinSparseFlows
	size += 4 * 8 // m.TinBulkFlows
	return size
}
func (m *OsvbngCakeSchedDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeUint64(m.RateBytesPerSec)
	buf.EncodeUint8(uint8(m.TinMode))
	buf.EncodeUint8(m.TinCnt)
	buf.EncodeUint32(m.BufferUsage)
	buf.EncodeUint32(m.BufferLimit)
	for i := 0; i < 8; i++ {
		var x uint64
		if i < len(m.TinPackets) {
			x = uint64(m.TinPackets[i])
		}
		buf.EncodeUint64(x)
	}
	for i := 0; i < 8; i++ {
		var x uint64
		if i < len(m.TinBytes) {
			x = uint64(m.TinBytes[i])
		}
		buf.EncodeUint64(x)
	}
	for i := 0; i < 8; i++ {
		var x uint64
		if i < len(m.TinDrops) {
			x = uint64(m.TinDrops[i])
		}
		buf.EncodeUint64(x)
	}
	for i := 0; i < 8; i++ {
		var x uint64
		if i < len(m.TinEcnMarks) {
			x = uint64(m.TinEcnMarks[i])
		}
		buf.EncodeUint64(x)
	}
	for i := 0; i < 8; i++ {
		var x uint32
		if i < len(m.TinPeakDelayUs) {
			x = uint32(m.TinPeakDelayUs[i])
		}
		buf.EncodeUint32(x)
	}
	for i := 0; i < 8; i++ {
		var x uint32
		if i < len(m.TinAvgDelayUs) {
			x = uint32(m.TinAvgDelayUs[i])
		}
		buf.EncodeUint32(x)
	}
	for i := 0; i < 8; i++ {
		var x uint32
		if i < len(m.TinSparseFlows) {
			x = uint32(m.TinSparseFlows[i])
		}
		buf.EncodeUint32(x)
	}
	for i := 0; i < 8; i++ {
		var x uint32
		if i < len(m.TinBulkFlows) {
			x = uint32(m.TinBulkFlows[i])
		}
		buf.EncodeUint32(x)
	}
	return buf.Bytes(), nil
}
func (m *OsvbngCakeSchedDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.RateBytesPerSec = buf.DecodeUint64()
	m.TinMode = OsvbngCakeTinMode(buf.DecodeUint8())
	m.TinCnt = buf.DecodeUint8()
	m.BufferUsage = buf.DecodeUint32()
	m.BufferLimit = buf.DecodeUint32()
	m.TinPackets = make([]uint64, 8)
	for i := 0; i < len(m.TinPackets); i++ {
		m.TinPackets[i] = buf.DecodeUint64()
	}
	m.TinBytes = make([]uint64, 8)
	for i := 0; i < len(m.TinBytes); i++ {
		m.TinBytes[i] = buf.DecodeUint64()
	}
	m.TinDrops = make([]uint64, 8)
	for i := 0; i < len(m.TinDrops); i++ {
		m.TinDrops[i] = buf.DecodeUint64()
	}
	m.TinEcnMarks = make([]uint64, 8)
	for i := 0; i < len(m.TinEcnMarks); i++ {
		m.TinEcnMarks[i] = buf.DecodeUint64()
	}
	m.TinPeakDelayUs = make([]uint32, 8)
	for i := 0; i < len(m.TinPeakDelayUs); i++ {
		m.TinPeakDelayUs[i] = buf.DecodeUint32()
	}
	m.TinAvgDelayUs = make([]uint32, 8)
	for i := 0; i < len(m.TinAvgDelayUs); i++ {
		m.TinAvgDelayUs[i] = buf.DecodeUint32()
	}
	m.TinSparseFlows = make([]uint32, 8)
	for i := 0; i < len(m.TinSparseFlows); i++ {
		m.TinSparseFlows[i] = buf.DecodeUint32()
	}
	m.TinBulkFlows = make([]uint32, 8)
	for i := 0; i < len(m.TinBulkFlows); i++ {
		m.TinBulkFlows[i] = buf.DecodeUint32()
	}
	return nil
}

// Dump per-subscriber scheduler state
//   - sw_if_index - subscriber interface (~0 for all)
//
// OsvbngCakeSchedDump defines message 'osvbng_cake_sched_dump'.
type OsvbngCakeSchedDump struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *OsvbngCakeSchedDump) Reset()               { *m = OsvbngCakeSchedDump{} }
func (*OsvbngCakeSchedDump) GetMessageName() string { return "osvbng_cake_sched_dump" }
func (*OsvbngCakeSchedDump) GetCrcString() string   { return "f9e6675e" }
func (*OsvbngCakeSchedDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCakeSchedDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.SwIfIndex
	return size
}
func (m *OsvbngCakeSchedDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *OsvbngCakeSchedDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

// Enable or disable per-subscriber CAKE scheduler
//   - sw_if_index - subscriber interface
//   - is_enable - enable if true, disable if false
//   - rate_bytes_per_sec - shaping rate (bytes/sec). 0 on disable.
//   - tin_mode - DiffServ tin mode (besteffort, diffserv3, diffserv4, diffserv8)
//   - overhead_bytes - per-packet overhead adjustment (signed, for link-layer framing)
//   - atm_mode - ATM cell rounding mode (none, ATM, PTM)
//   - mpu - minimum packet unit (bytes, e.g. 64 for Ethernet)
//   - buffer_limit - max queued bytes (0 = auto-calculate from rate * RTT)
//   - target_us - CoDel AQM target (microseconds, 0 = 5000)
//   - interval_us - CoDel AQM interval (microseconds, 0 = 100000)
//   - flags - behavior flags (wash DSCP, ACK filter, split GSO)
//
// OsvbngCakeSchedEnableDisable defines message 'osvbng_cake_sched_enable_disable'.
type OsvbngCakeSchedEnableDisable struct {
	SwIfIndex       interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	IsEnable        bool                           `binapi:"bool,name=is_enable" json:"is_enable,omitempty"`
	RateBytesPerSec uint64                         `binapi:"u64,name=rate_bytes_per_sec" json:"rate_bytes_per_sec,omitempty"`
	TinMode         OsvbngCakeTinMode              `binapi:"osvbng_cake_tin_mode,name=tin_mode" json:"tin_mode,omitempty"`
	OverheadBytes   int16                          `binapi:"i16,name=overhead_bytes" json:"overhead_bytes,omitempty"`
	AtmMode         OsvbngCakeAtmMode              `binapi:"osvbng_cake_atm_mode,name=atm_mode" json:"atm_mode,omitempty"`
	Mpu             uint8                          `binapi:"u8,name=mpu" json:"mpu,omitempty"`
	BufferLimit     uint32                         `binapi:"u32,name=buffer_limit" json:"buffer_limit,omitempty"`
	TargetUs        uint32                         `binapi:"u32,name=target_us" json:"target_us,omitempty"`
	IntervalUs      uint32                         `binapi:"u32,name=interval_us" json:"interval_us,omitempty"`
	Flags           OsvbngCakeFlags                `binapi:"osvbng_cake_flags,name=flags" json:"flags,omitempty"`
}

func (m *OsvbngCakeSchedEnableDisable) Reset() { *m = OsvbngCakeSchedEnableDisable{} }
func (*OsvbngCakeSchedEnableDisable) GetMessageName() string {
	return "osvbng_cake_sched_enable_disable"
}
func (*OsvbngCakeSchedEnableDisable) GetCrcString() string { return "911be194" }
func (*OsvbngCakeSchedEnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCakeSchedEnableDisable) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.SwIfIndex
	size += 1 // m.IsEnable
	size += 8 // m.RateBytesPerSec
	size += 1 // m.TinMode
	size += 2 // m.OverheadBytes
	size += 1 // m.AtmMode
	size += 1 // m.Mpu
	size += 4 // m.BufferLimit
	size += 4 // m.TargetUs
	size += 4 // m.IntervalUs
	size += 4 // m.Flags
	return size
}
func (m *OsvbngCakeSchedEnableDisable) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeBool(m.IsEnable)
	buf.EncodeUint64(m.RateBytesPerSec)
	buf.EncodeUint8(uint8(m.TinMode))
	buf.EncodeInt16(m.OverheadBytes)
	buf.EncodeUint8(uint8(m.AtmMode))
	buf.EncodeUint8(m.Mpu)
	buf.EncodeUint32(m.BufferLimit)
	buf.EncodeUint32(m.TargetUs)
	buf.EncodeUint32(m.IntervalUs)
	buf.EncodeUint32(uint32(m.Flags))
	return buf.Bytes(), nil
}
func (m *OsvbngCakeSchedEnableDisable) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.IsEnable = buf.DecodeBool()
	m.RateBytesPerSec = buf.DecodeUint64()
	m.TinMode = OsvbngCakeTinMode(buf.DecodeUint8())
	m.OverheadBytes = buf.DecodeInt16()
	m.AtmMode = OsvbngCakeAtmMode(buf.DecodeUint8())
	m.Mpu = buf.DecodeUint8()
	m.BufferLimit = buf.DecodeUint32()
	m.TargetUs = buf.DecodeUint32()
	m.IntervalUs = buf.DecodeUint32()
	m.Flags = OsvbngCakeFlags(buf.DecodeUint32())
	return nil
}

// OsvbngCakeSchedEnableDisableReply defines message 'osvbng_cake_sched_enable_disable_reply'.
type OsvbngCakeSchedEnableDisableReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCakeSchedEnableDisableReply) Reset() { *m = OsvbngCakeSchedEnableDisableReply{} }
func (*OsvbngCakeSchedEnableDisableReply) GetMessageName() string {
	return "osvbng_cake_sched_enable_disable_reply"
}
func (*OsvbngCakeSchedEnableDisableReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCakeSchedEnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCakeSchedEnableDisableReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCakeSchedEnableDisableReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCakeSchedEnableDisableReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Reset scheduler statistics for a subscriber
//   - sw_if_index - subscriber interface
//
// OsvbngCakeSchedResetStats defines message 'osvbng_cake_sched_reset_stats'.
type OsvbngCakeSchedResetStats struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *OsvbngCakeSchedResetStats) Reset()               { *m = OsvbngCakeSchedResetStats{} }
func (*OsvbngCakeSchedResetStats) GetMessageName() string { return "osvbng_cake_sched_reset_stats" }
func (*OsvbngCakeSchedResetStats) GetCrcString() string   { return "f9e6675e" }
func (*OsvbngCakeSchedResetStats) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCakeSchedResetStats) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.SwIfIndex
	return size
}
func (m *OsvbngCakeSchedResetStats) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *OsvbngCakeSchedResetStats) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

// OsvbngCakeSchedResetStatsReply defines message 'osvbng_cake_sched_reset_stats_reply'.
type OsvbngCakeSchedResetStatsReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCakeSchedResetStatsReply) Reset() { *m = OsvbngCakeSchedResetStatsReply{} }
func (*OsvbngCakeSchedResetStatsReply) GetMessageName() string {
	return "osvbng_cake_sched_reset_stats_reply"
}
func (*OsvbngCakeSchedResetStatsReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCakeSchedResetStatsReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCakeSchedResetStatsReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCakeSchedResetStatsReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCakeSchedResetStatsReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

func init() { file_osvbng_qos_sched_binapi_init() }
func file_osvbng_qos_sched_binapi_init() {
	api.RegisterMessage((*OsvbngCakeSchedDetails)(nil), "osvbng_cake_sched_details_9939f302")
	api.RegisterMessage((*OsvbngCakeSchedDump)(nil), "osvbng_cake_sched_dump_f9e6675e")
	api.RegisterMessage((*OsvbngCakeSchedEnableDisable)(nil), "osvbng_cake_sched_enable_disable_911be194")
	api.RegisterMessage((*OsvbngCakeSchedEnableDisableReply)(nil), "osvbng_cake_sched_enable_disable_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCakeSchedResetStats)(nil), "osvbng_cake_sched_reset_stats_f9e6675e")
	api.RegisterMessage((*OsvbngCakeSchedResetStatsReply)(nil), "osvbng_cake_sched_reset_stats_reply_e8d4e804")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*OsvbngCakeSchedDetails)(nil),
		(*OsvbngCakeSchedDump)(nil),
		(*OsvbngCakeSchedEnableDisable)(nil),
		(*OsvbngCakeSchedEnableDisableReply)(nil),
		(*OsvbngCakeSchedResetStats)(nil),
		(*OsvbngCakeSchedResetStatsReply)(nil),
	}
}
