// Copyright 2025 Veesix Networks Ltd
// Licensed under the GNU General Public License v3.0 or later.
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/ha/ha.proto

package hapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	SrgStatuses   []*SRGStatus           `protobuf:"bytes,4,rep,name=srg_statuses,json=srgStatuses,proto3" json:"srg_statuses,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,5,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_api_proto_ha_ha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ha_ha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_ha_ha_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HeartbeatMessage) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *HeartbeatMessage) GetSrgStatuses() []*SRGStatus {
	if x != nil {
		return x.SrgStatuses
	}
	return nil
}

func (x *HeartbeatMessage) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

type SRGStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrgName       string                 `protobuf:"bytes,1,opt,name=srg_name,json=srgName,proto3" json:"srg_name,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	SessionCount  uint64                 `protobuf:"varint,3,opt,name=session_count,json=sessionCount,proto3" json:"session_count,omitempty"`
	LastSyncSeq   uint64                 `protobuf:"varint,4,opt,name=last_sync_seq,json=lastSyncSeq,proto3" json:"last_sync_seq,omitempty"`
	Priority      uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRGStatus) Reset() {
	*x = SRGStatus{}
	mi := &file_api_proto_ha_ha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRGStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRGStatus) ProtoMessage() {}

func (x *SRGStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ha_ha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRGStatus.ProtoReflect.Descriptor instead.
func (*SRGStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_ha_ha_proto_rawDescGZIP(), []int{1}
}

func (x *SRGStatus) GetSrgName() string {
	if x != nil {
		return x.SrgName
	}
	return ""
}

func (x *SRGStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SRGStatus) GetSessionCount() uint64 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

func (x *SRGStatus) GetLastSyncSeq() uint64 {
	if x != nil {
		return x.LastSyncSeq
	}
	return 0
}

func (x *SRGStatus) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SRGStateNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrgName       string                 `protobuf:"bytes,1,opt,name=srg_name,json=srgName,proto3" json:"srg_name,omitempty"`
	NewState      string                 `protobuf:"bytes,2,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	PrevState     string                 `protobuf:"bytes,3,opt,name=prev_state,json=prevState,proto3" json:"prev_state,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRGStateNotification) Reset() {
	*x = SRGStateNotification{}
	mi := &file_api_proto_ha_ha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRGStateNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRGStateNotification) ProtoMessage() {}

func (x *SRGStateNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ha_ha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRGStateNotification.ProtoReflect.Descriptor instead.
func (*SRGStateNotification) Descriptor() ([]byte, []int) {
	return file_api_proto_ha_ha_proto_rawDescGZIP(), []int{2}
}

func (x *SRGStateNotification) GetSrgName() string {
	if x != nil {
		return x.SrgName
	}
	return ""
}

func (x *SRGStateNotification) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

func (x *SRGStateNotification) GetPrevState() string {
	if x != nil {
		return x.PrevState
	}
	return ""
}

func (x *SRGStateNotification) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type SRGStateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRGStateAck) Reset() {
	*x = SRGStateAck{}
	mi := &file_api_proto_ha_ha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRGStateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRGStateAck) ProtoMessage() {}

func (x *SRGStateAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ha_ha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRGStateAck.ProtoReflect.Descriptor instead.
func (*SRGStateAck) Descriptor() ([]byte, []int) {
	return file_api_proto_ha_ha_proto_rawDescGZIP(), []int{3}
}

func (x *SRGStateAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type SwitchoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrgNames      []string               `protobuf:"bytes,1,rep,name=srg_names,json=srgNames,proto3" json:"srg_names,omitempty"`
	Graceful      bool                   `protobuf:"varint,2,opt,name=graceful,proto3" json:"graceful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchoverRequest) Reset() {
	*x = SwitchoverRequest{}
	mi := &file_api_proto_ha_ha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchoverRequest) ProtoMessage() {}

func (x *SwitchoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ha_ha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchoverRequest.ProtoReflect.Descriptor instead.
func (*SwitchoverRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ha_ha_proto_rawDescGZIP(), []int{4}
}

func (x *SwitchoverRequest) GetSrgNames() []string {
	if x != nil {
		return x.SrgNames
	}
	return nil
}

func (x *SwitchoverRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type SwitchoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchoverResponse) Reset() {
	*x = SwitchoverResponse{}
	mi := &file_api_proto_ha_ha_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchoverResponse) ProtoMessage() {}

func (x *SwitchoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ha_ha_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchoverResponse.ProtoReflect.Descriptor instead.
func (*SwitchoverResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ha_ha_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchoverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwitchoverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_ha_ha_proto protoreflect.FileDescriptor

const file_api_proto_ha_ha_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/ha/ha.proto\x12\fosvbng.ha.v1\"\xc7\x01\n" +
	"\x10HeartbeatMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x12:\n" +
	"\fsrg_statuses\x18\x04 \x03(\v2\x17.osvbng.ha.v1.SRGStatusR\vsrgStatuses\x12\x1f\n" +
	"\vconfig_hash\x18\x05 \x01(\tR\n" +
	"configHash\"\xa1\x01\n" +
	"\tSRGStatus\x12\x19\n" +
	"\bsrg_name\x18\x01 \x01(\tR\asrgName\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12#\n" +
	"\rsession_count\x18\x03 \x01(\x04R\fsessionCount\x12\"\n" +
	"\rlast_sync_seq\x18\x04 \x01(\x04R\vlastSyncSeq\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\"\x90\x01\n" +
	"\x14SRGStateNotification\x12\x19\n" +
	"\bsrg_name\x18\x01 \x01(\tR\asrgName\x12\x1b\n" +
	"\tnew_state\x18\x02 \x01(\tR\bnewState\x12\x1d\n" +
	"\n" +
	"prev_state\x18\x03 \x01(\tR\tprevState\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs\"1\n" +
	"\vSRGStateAck\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"L\n" +
	"\x11SwitchoverRequest\x12\x1b\n" +
	"\tsrg_names\x18\x01 \x03(\tR\bsrgNames\x12\x1a\n" +
	"\bgraceful\x18\x02 \x01(\bR\bgraceful\"H\n" +
	"\x12SwitchoverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x89\x02\n" +
	"\rHAPeerService\x12O\n" +
	"\tHeartbeat\x12\x1e.osvbng.ha.v1.HeartbeatMessage\x1a\x1e.osvbng.ha.v1.HeartbeatMessage(\x010\x01\x12O\n" +
	"\x0eNotifySRGState\x12\".osvbng.ha.v1.SRGStateNotification\x1a\x19.osvbng.ha.v1.SRGStateAck\x12V\n" +
	"\x11RequestSwitchover\x12\x1f.osvbng.ha.v1.SwitchoverRequest\x1a .osvbng.ha.v1.SwitchoverResponseB5Z3github.com/veesix-networks/osvbng/api/proto/ha;hapbb\x06proto3"

var (
	file_api_proto_ha_ha_proto_rawDescOnce sync.Once
	file_api_proto_ha_ha_proto_rawDescData []byte
)

func file_api_proto_ha_ha_proto_rawDescGZIP() []byte {
	file_api_proto_ha_ha_proto_rawDescOnce.Do(func() {
		file_api_proto_ha_ha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ha_ha_proto_rawDesc), len(file_api_proto_ha_ha_proto_rawDesc)))
	})
	return file_api_proto_ha_ha_proto_rawDescData
}

var file_api_proto_ha_ha_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_ha_ha_proto_goTypes = []any{
	(*HeartbeatMessage)(nil),     // 0: osvbng.ha.v1.HeartbeatMessage
	(*SRGStatus)(nil),            // 1: osvbng.ha.v1.SRGStatus
	(*SRGStateNotification)(nil), // 2: osvbng.ha.v1.SRGStateNotification
	(*SRGStateAck)(nil),          // 3: osvbng.ha.v1.SRGStateAck
	(*SwitchoverRequest)(nil),    // 4: osvbng.ha.v1.SwitchoverRequest
	(*SwitchoverResponse)(nil),   // 5: osvbng.ha.v1.SwitchoverResponse
}
var file_api_proto_ha_ha_proto_depIdxs = []int32{
	1, // 0: osvbng.ha.v1.HeartbeatMessage.srg_statuses:type_name -> osvbng.ha.v1.SRGStatus
	0, // 1: osvbng.ha.v1.HAPeerService.Heartbeat:input_type -> osvbng.ha.v1.HeartbeatMessage
	2, // 2: osvbng.ha.v1.HAPeerService.NotifySRGState:input_type -> osvbng.ha.v1.SRGStateNotification
	4, // 3: osvbng.ha.v1.HAPeerService.RequestSwitchover:input_type -> osvbng.ha.v1.SwitchoverRequest
	0, // 4: osvbng.ha.v1.HAPeerService.Heartbeat:output_type -> osvbng.ha.v1.HeartbeatMessage
	3, // 5: osvbng.ha.v1.HAPeerService.NotifySRGState:output_type -> osvbng.ha.v1.SRGStateAck
	5, // 6: osvbng.ha.v1.HAPeerService.RequestSwitchover:output_type -> osvbng.ha.v1.SwitchoverResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_ha_ha_proto_init() }
func file_api_proto_ha_ha_proto_init() {
	if File_api_proto_ha_ha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ha_ha_proto_rawDesc), len(file_api_proto_ha_ha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ha_ha_proto_goTypes,
		DependencyIndexes: file_api_proto_ha_ha_proto_depIdxs,
		MessageInfos:      file_api_proto_ha_ha_proto_msgTypes,
	}.Build()
	File_api_proto_ha_ha_proto = out.File
	file_api_proto_ha_ha_proto_goTypes = nil
	file_api_proto_ha_ha_proto_depIdxs = nil
}
