// Copyright 2025 Veesix Networks Ltd
// Licensed under the GNU General Public License v3.0 or later.
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/ha/ha.proto

package hapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HAPeerService_Heartbeat_FullMethodName         = "/osvbng.ha.v1.HAPeerService/Heartbeat"
	HAPeerService_NotifySRGState_FullMethodName    = "/osvbng.ha.v1.HAPeerService/NotifySRGState"
	HAPeerService_RequestSwitchover_FullMethodName = "/osvbng.ha.v1.HAPeerService/RequestSwitchover"
	HAPeerService_SyncSession_FullMethodName       = "/osvbng.ha.v1.HAPeerService/SyncSession"
	HAPeerService_BulkSync_FullMethodName          = "/osvbng.ha.v1.HAPeerService/BulkSync"
)

// HAPeerServiceClient is the client API for HAPeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HAPeerServiceClient interface {
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatMessage, HeartbeatMessage], error)
	NotifySRGState(ctx context.Context, in *SRGStateNotification, opts ...grpc.CallOption) (*SRGStateAck, error)
	RequestSwitchover(ctx context.Context, in *SwitchoverRequest, opts ...grpc.CallOption) (*SwitchoverResponse, error)
	SyncSession(ctx context.Context, in *SyncSessionRequest, opts ...grpc.CallOption) (*SyncSessionResponse, error)
	BulkSync(ctx context.Context, in *BulkSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BulkSyncResponse], error)
}

type hAPeerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHAPeerServiceClient(cc grpc.ClientConnInterface) HAPeerServiceClient {
	return &hAPeerServiceClient{cc}
}

func (c *hAPeerServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatMessage, HeartbeatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HAPeerService_ServiceDesc.Streams[0], HAPeerService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatMessage, HeartbeatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HAPeerService_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatMessage, HeartbeatMessage]

func (c *hAPeerServiceClient) NotifySRGState(ctx context.Context, in *SRGStateNotification, opts ...grpc.CallOption) (*SRGStateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SRGStateAck)
	err := c.cc.Invoke(ctx, HAPeerService_NotifySRGState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hAPeerServiceClient) RequestSwitchover(ctx context.Context, in *SwitchoverRequest, opts ...grpc.CallOption) (*SwitchoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchoverResponse)
	err := c.cc.Invoke(ctx, HAPeerService_RequestSwitchover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hAPeerServiceClient) SyncSession(ctx context.Context, in *SyncSessionRequest, opts ...grpc.CallOption) (*SyncSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncSessionResponse)
	err := c.cc.Invoke(ctx, HAPeerService_SyncSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hAPeerServiceClient) BulkSync(ctx context.Context, in *BulkSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BulkSyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HAPeerService_ServiceDesc.Streams[1], HAPeerService_BulkSync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BulkSyncRequest, BulkSyncResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HAPeerService_BulkSyncClient = grpc.ServerStreamingClient[BulkSyncResponse]

// HAPeerServiceServer is the server API for HAPeerService service.
// All implementations must embed UnimplementedHAPeerServiceServer
// for forward compatibility.
type HAPeerServiceServer interface {
	Heartbeat(grpc.BidiStreamingServer[HeartbeatMessage, HeartbeatMessage]) error
	NotifySRGState(context.Context, *SRGStateNotification) (*SRGStateAck, error)
	RequestSwitchover(context.Context, *SwitchoverRequest) (*SwitchoverResponse, error)
	SyncSession(context.Context, *SyncSessionRequest) (*SyncSessionResponse, error)
	BulkSync(*BulkSyncRequest, grpc.ServerStreamingServer[BulkSyncResponse]) error
	mustEmbedUnimplementedHAPeerServiceServer()
}

// UnimplementedHAPeerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHAPeerServiceServer struct{}

func (UnimplementedHAPeerServiceServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatMessage, HeartbeatMessage]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedHAPeerServiceServer) NotifySRGState(context.Context, *SRGStateNotification) (*SRGStateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifySRGState not implemented")
}
func (UnimplementedHAPeerServiceServer) RequestSwitchover(context.Context, *SwitchoverRequest) (*SwitchoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestSwitchover not implemented")
}
func (UnimplementedHAPeerServiceServer) SyncSession(context.Context, *SyncSessionRequest) (*SyncSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSession not implemented")
}
func (UnimplementedHAPeerServiceServer) BulkSync(*BulkSyncRequest, grpc.ServerStreamingServer[BulkSyncResponse]) error {
	return status.Error(codes.Unimplemented, "method BulkSync not implemented")
}
func (UnimplementedHAPeerServiceServer) mustEmbedUnimplementedHAPeerServiceServer() {}
func (UnimplementedHAPeerServiceServer) testEmbeddedByValue()                       {}

// UnsafeHAPeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HAPeerServiceServer will
// result in compilation errors.
type UnsafeHAPeerServiceServer interface {
	mustEmbedUnimplementedHAPeerServiceServer()
}

func RegisterHAPeerServiceServer(s grpc.ServiceRegistrar, srv HAPeerServiceServer) {
	// If the following call panics, it indicates UnimplementedHAPeerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HAPeerService_ServiceDesc, srv)
}

func _HAPeerService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HAPeerServiceServer).Heartbeat(&grpc.GenericServerStream[HeartbeatMessage, HeartbeatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HAPeerService_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatMessage, HeartbeatMessage]

func _HAPeerService_NotifySRGState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SRGStateNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAPeerServiceServer).NotifySRGState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HAPeerService_NotifySRGState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAPeerServiceServer).NotifySRGState(ctx, req.(*SRGStateNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _HAPeerService_RequestSwitchover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAPeerServiceServer).RequestSwitchover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HAPeerService_RequestSwitchover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAPeerServiceServer).RequestSwitchover(ctx, req.(*SwitchoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HAPeerService_SyncSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAPeerServiceServer).SyncSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HAPeerService_SyncSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAPeerServiceServer).SyncSession(ctx, req.(*SyncSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HAPeerService_BulkSync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BulkSyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HAPeerServiceServer).BulkSync(m, &grpc.GenericServerStream[BulkSyncRequest, BulkSyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HAPeerService_BulkSyncServer = grpc.ServerStreamingServer[BulkSyncResponse]

// HAPeerService_ServiceDesc is the grpc.ServiceDesc for HAPeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HAPeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osvbng.ha.v1.HAPeerService",
	HandlerType: (*HAPeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifySRGState",
			Handler:    _HAPeerService_NotifySRGState_Handler,
		},
		{
			MethodName: "RequestSwitchover",
			Handler:    _HAPeerService_RequestSwitchover_Handler,
		},
		{
			MethodName: "SyncSession",
			Handler:    _HAPeerService_SyncSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _HAPeerService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "BulkSync",
			Handler:       _HAPeerService_BulkSync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/ha/ha.proto",
}
