FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    libssl3 \
    libncurses6 \
    libjansson4 \
    wget \
    iproute2 \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/rtbrick/bngblaster/releases/download/0.9.26/bngblaster-0.9.26-ubuntu-24.04_amd64.deb && \
    dpkg -i bngblaster-0.9.26-ubuntu-24.04_amd64.deb && \
    rm bngblaster-0.9.26-ubuntu-24.04_amd64.deb

RUN bngblaster -v

WORKDIR /config

CMD ["sleep", "infinity"]