apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-config
data:
  frr.conf: |
   log syslog informational
   service integrated-vtysh-config
   ip forwarding
   ipv6 forwarding
   !
   line vty
   !
  routing-daemons: |
    bgpd=yes
    ospfd=yes
    ospf6d=yes
    bfdd=yes
    ldpd=yes
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 67108864 -M dplane_fpm_nl"
    bgpd_options="   -A 127.0.0.1"
    ospfd_options="  -A 127.0.0.1"
    ospf6d_options=" -A ::1"
    staticd_options="-A 127.0.0.1"
    bfdd_options="   -A 127.0.0.1"
    ldpd_options="   -A 127.0.0.1"
    log_file=/var/log/osvbng/routing.log  