package config

import (
	"fmt"
	"os"

	"github.com/veesix-networks/osvbng/pkg/config/aaa"
	"github.com/veesix-networks/osvbng/pkg/config/interfaces"
	"github.com/veesix-networks/osvbng/pkg/config/ip"
	"github.com/veesix-networks/osvbng/pkg/config/protocols"
	"github.com/veesix-networks/osvbng/pkg/config/subscriber"
	"github.com/veesix-networks/osvbng/pkg/config/system"
	"github.com/veesix-networks/osvbng/pkg/logger"
	"github.com/veesix-networks/osvbng/pkg/version"
	"gopkg.in/yaml.v3"
)

type GenerateOptions struct {
	AllDataplane bool
}

func Generate(opts GenerateOptions) (string, error) {
	accessInterface := os.Getenv("OSVBNG_ACCESS_INTERFACE")
	if accessInterface == "" {
		accessInterface = "eth1"
	}

	coreInterface := os.Getenv("OSVBNG_CORE_INTERFACE")

	logLevel := logger.LogLevel(os.Getenv("OSVBNG_LOG_LEVEL"))
	if logLevel == "" {
		logLevel = logger.LogLevelInfo
	}

	cfg := &Config{
		Logging: system.LoggingConfig{
			Format: "text",
			Level:  logLevel,
			Components: map[string]logger.LogLevel{
				"ipoed": logLevel,
				"aaad":  logLevel,
				"dpd":   logLevel,
				"subd":  logLevel,
				"arpd":  logLevel,
				"pppoed": logLevel,
				"sb":     logLevel,
			},
		},
		Dataplane: system.DataplaneConfig{},
		SubscriberGroups: &subscriber.SubscriberGroupsConfig{
			Groups: map[string]*subscriber.SubscriberGroup{
				"default": {
					AccessType: "ipoe",
					VLANs: []subscriber.VLANRange{
						{
							SVLAN:     "100",
							CVLAN:     "any",
							Interface: "loop100",
						},
					},
					IPv4Profile:   "default",
					IPv6Profile:   "default-v6",
					BGP: &subscriber.SubscriberBGP{
						Enabled:               true,
						AdvertisePools:        true,
						RedistributeConnected: true,
					},
					AAAPolicy: "default-policy",
				},
			},
		},
		IPv4Profiles: map[string]*ip.IPv4Profile{
			"default": {
				Gateway: "10.255.0.1",
				DNS:     []string{"8.8.8.8", "8.8.4.4"},
				Pools: []ip.IPv4Pool{
					{
						Name:    "subscriber-pool",
						Network: "10.255.0.0/16",
					},
				},
				DHCP: &ip.IPv4DHCPOptions{
					LeaseTime: 3600,
				},
			},
		},
		IPv6Profiles: map[string]*ip.IPv6Profile{
			"default-v6": {
				IANAPools: []ip.IANAPool{
					{
						Name:          "wan-link-pool",
						Network:       "2001:db8:0:1::/64",
						RangeStart:    "2001:db8:0:1::1000",
						RangeEnd:      "2001:db8:0:1::ffff",
						Gateway:       "2001:db8:0:1::1",
						PreferredTime: 3600,
						ValidTime:     7200,
					},
				},
				PDPools: []ip.PDPool{
					{
						Name:          "subscriber-pd-pool",
						Network:       "2001:db8:100::/40",
						PrefixLength:  56,
						PreferredTime: 3600,
						ValidTime:     7200,
					},
				},
				DNS: []string{"2001:4860:4860::8888", "2001:4860:4860::8844"},
			},
		},
		DHCP: ip.DHCPConfig{
			Provider: "local",
		},
		DHCPv6: ip.DHCPv6Config{
			Provider:   "local",
			DNSServers: []string{"2001:4860:4860::8888", "2001:4860:4860::8844"},
			RA: &ip.IPv6RAConfig{
				RouterLifetime: 1800,
				MaxInterval:    600,
				MinInterval:    200,
			},
		},
		AAA: aaa.AAAConfig{
			AuthProvider:  "local",
			NASIdentifier: "osvbng",
			Policy: []aaa.AAAPolicy{
				{
					Name:                  "default-policy",
					Format:                "$remote-id$",
					MaxConcurrentSessions: 1,
				},
			},
		},
		Protocols: protocols.ProtocolConfig{
			BGP: &protocols.BGPConfig{
				ASN:      65000,
				RouterID: "10.255.0.1",
			},
		},
		Interfaces: map[string]*interfaces.InterfaceConfig{
			accessInterface: {
				Name:        accessInterface,
				Description: "Access Interface",
				Enabled:     true,
				BNGMode:     "access",
			},
		},
	}

	if coreInterface != "" {
		cfg.Interfaces[coreInterface] = &interfaces.InterfaceConfig{
			Name:        coreInterface,
			Description: "Core Interface",
			Enabled:     true,
			BNGMode:     "core",
			LCP:         true,
		}
	}

	cfg.Interfaces["loop100"] = &interfaces.InterfaceConfig{
		Name:        "loop100",
		Description: "Subscriber Gateway Loopback",
		Enabled:     true,
		LCP:         true,
		Address: &interfaces.AddressConfig{
			IPv4: []string{"10.255.0.1/32"},
			IPv6: []string{"2001:db8:0:1::1/128"},
		},
	}

	cfg.Plugins = map[string]interface{}{
		"subscriber.auth.local": map[string]interface{}{
			"database_path": "/tmp/osvbng.db",
			"allow_all":     true,
		},
		"exporter.prometheus": map[string]interface{}{
			"enabled":        false,
			"listen_address": ":9090",
		},
		"northbound.api": map[string]interface{}{
			"enabled":        true,
			"listen_address": ":8080",
		},
	}

	output, err := yaml.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("failed to marshal config: %w", err)
	}

	header := fmt.Sprintf("# Auto-generated by osvbngd %s\n# Do not edit this header\n\n", version.Version)
	return header + string(output), nil
}
