package config

import (
	"fmt"
	"os"

	"github.com/veesix-networks/osvbng/pkg/config/aaa"
	"github.com/veesix-networks/osvbng/pkg/config/interfaces"
	"github.com/veesix-networks/osvbng/pkg/config/ip"
	"github.com/veesix-networks/osvbng/pkg/config/subscriber"
	"github.com/veesix-networks/osvbng/pkg/config/system"
	"github.com/veesix-networks/osvbng/pkg/version"
	"gopkg.in/yaml.v3"
)

type GenerateOptions struct {
	AllDataplane bool
}

func Generate(opts GenerateOptions) (string, error) {
	accessInterface := os.Getenv("OSVBNG_ACCESS_INTERFACE")
	if accessInterface == "" {
		accessInterface = "eth0"
	}

	cfg := &Config{
		Logging: system.LoggingConfig{
			Format: "text",
			Level:  "info",
			Components: map[string]string{
				"ipoed":  "info",
				"aaad":   "info",
				"dhcprd": "info",
				"dpd":    "info",
				"subd":   "info",
				"arpd":   "info",
			},
		},
		Dataplane: system.DataplaneConfig{
			AccessInterface: accessInterface,
		},
		SubscriberGroup: subscriber.SubscriberGroupConfig{
			DefaultPolicy: "default-policy",
			VLANs: []subscriber.VLANRange{
				{
					SVLAN:     "100",
					CVLAN:     "any",
					Interface: "loop100",
				},
			},
		},
		DHCP: ip.DHCPConfig{
			Provider: "local",
			Pools: []ip.DHCPPool{
				{
					Name:       "subscriber-pool",
					Network:    "10.255.0.0/16",
					RangeStart: "10.255.0.10",
					RangeEnd:   "10.255.255.254",
					Gateway:    "10.255.0.1",
					DNSServers: []string{"8.8.8.8", "8.8.4.4"},
					LeaseTime:  3600,
				},
			},
		},
		AAA: aaa.AAAConfig{
			Provider:      "local",
			NASIdentifier: "osvbng",
			Policy: []aaa.AAAPolicy{
				{
					Name:                  "default-policy",
					Format:                "$mac-address$",
					Type:                  "dhcp",
					MaxConcurrentSessions: 1,
				},
			},
		},
		Interfaces: map[string]*interfaces.InterfaceConfig{
			"eth0": {
				Name:        "eth0",
				Description: "Access Interface",
				Enabled:     true,
			},
			"eth1": {
				Name:        "eth1",
				Description: "Core Interface",
				Enabled:     true,
				LCP:         true,
			},
			"loop100": {
				Name:        "loop100",
				Description: "Subscriber Gateway Loopback",
				Enabled:     true,
				LCP:         true,
				Address: &interfaces.AddressConfig{
					IPv4: []string{"10.255.0.1/32"},
				},
			},
		},
		Plugins: map[string]interface{}{
			"subscriber.auth.local": map[string]interface{}{
				"database_path": "/tmp/osvbng.db",
				"allow_all":     true,
			},
			"exporter.prometheus": map[string]interface{}{
				"enabled":        false,
				"listen_address": ":9090",
			},
			"northbound.api": map[string]interface{}{
				"enabled":        true,
				"listen_address": ":8080",
			},
		},
	}

	if opts.AllDataplane {
		cfg.Dataplane.DPAPISocket = "/run/osvbng/dataplane_api.sock"
		cfg.Dataplane.PuntSocketPath = "/run/osvbng/osvbng-punt.sock"
		cfg.Dataplane.ARPPuntSocketPath = "/run/osvbng/arp-punt.sock"
		cfg.Dataplane.MemifSocketPath = "/run/osvbng/memif.sock"
	}

	out, err := yaml.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("failed to marshal config: %w", err)
	}

	header := fmt.Sprintf("# Auto-generated by osvbngd %s\n# Do not edit this header\n\n", version.Version)

	return header + string(out), nil
}
