package config

import (
	"fmt"
	"os"
	"strings"

	"github.com/veesix-networks/osvbng/pkg/version"
	"gopkg.in/yaml.v3"
)

type GenerateOptions struct {
	AllDataplane bool
}

func Generate(opts GenerateOptions) (string, error) {
	accessInterface := os.Getenv("OSVBNG_ACCESS_INTERFACE")
	if accessInterface == "" {
		accessInterface = "eth0"
	}

	cfg := &Config{
		Logging: Logging{
			Format: "text",
			Level:  "debug",
			Components: map[string]string{
				"ipoed":  "debug",
				"aaad":   "debug",
				"dhcprd": "debug",
				"dpd":    "debug",
				"subd":   "debug",
				"arpd":   "debug",
			},
		},
		Dataplane: Dataplane{
			AccessInterface: accessInterface,
		},
		SubscriberGroup: SubscriberGroup{
			DefaultPolicy: "default-policy",
			VLANs: []VLANRange{
				{
					SVLAN:     "100",
					CVLAN:     "any",
					Interface: "loop100",
				},
			},
		},
		DHCP: DHCP{
			Provider: "local",
			Pools: []DHCPPool{
				{
					Name:       "subscriber-pool",
					Network:    "10.1.0.0/16",
					RangeStart: "10.1.0.10",
					RangeEnd:   "10.1.255.254",
					Gateway:    "10.255.240.1",
					DNSServers: []string{"8.8.8.8", "8.8.4.4"},
					LeaseTime:  3600,
				},
			},
		},
		AAA: AAA{
			Provider:      "local",
			NASIdentifier: "osvbng",
			Policy: []AAAPolicy{
				{
					Name:                  "default-policy",
					Format:                "$mac-address$",
					Type:                  "dhcp",
					MaxConcurrentSessions: 1,
				},
			},
		},
		Plugins: map[string]map[string]interface{}{
			"subscriber.auth.local": {
				"database_path": "/tmp/osvbng.db",
			},
			"exporter.prometheus": {
				"enabled":        false,
				"listen_address": ":9090",
			},
			"northbound.api": {
				"enabled":        true,
				"listen_address": ":8080",
			},
		},
	}

	if opts.AllDataplane {
		cfg.Dataplane.DPAPISocket = "/run/osvbng/dataplane_api.sock"
		cfg.Dataplane.PuntSocketPath = "/run/osvbng/osvbng-punt.sock"
		cfg.Dataplane.ARPPuntSocketPath = "/run/osvbng/arp-punt.sock"
		cfg.Dataplane.MemifSocketPath = "/run/osvbng/memif.sock"
	}

	out, err := yaml.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("failed to marshal config: %w", err)
	}

	header := fmt.Sprintf("# Auto-generated by osvbngd %s\n# Do not edit this header\n\n", version.Version)

	interfacesSection := `
interfaces:
  eth0:
    description: "Access Interface"
    enabled: true
  eth1:
    description: "Core Interface"
    enabled: true
    lcp: true
  loop100:
    description: "Subscriber Gateway Loopback"
    enabled: true
    lcp: true
    address:
      ipv4:
        - 10.255.240.1/32
`

	return header + string(out) + strings.TrimPrefix(interfacesSection, "\n"), nil
}
