// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              25.10-release
// source: plugins/osvbng_pppoe.api.json

// Package osvbng_pppoe contains generated bindings for API file osvbng_pppoe.api.
//
// Contents:
// -  4 messages
package osvbng_pppoe

import (
	ethernet_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/ethernet_types"
	interface_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/interface_types"
	ip_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/ip_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "osvbng_pppoe"
	APIVersion = "1.0.0"
	VersionCrc = 0x8fbe5315
)

// Set or delete a PPPoE session
//   - is_add - add address if non-zero, else delete
//   - session_id - PPPoE session ID
//   - client_ip - PPPoE session's client address
//   - decap_vrf_id - the vrf index for pppoe decaped packet
//   - client_mac - the client ethernet address
//   - local_mac - the BNG ethernet address (explicit, not learned)
//   - encap_if_index - the index of tx interface for pppoe encaped packet (explicit)
//   - outer_vlan - S-VLAN tag (0 if untagged, or single VLAN tag value)
//   - inner_vlan - C-VLAN tag (0 if not Q-in-Q)
//
// OsvbngPppoeAddDelSession defines message 'osvbng_pppoe_add_del_session'.
type OsvbngPppoeAddDelSession struct {
	IsAdd        bool                           `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	SessionID    uint16                         `binapi:"u16,name=session_id" json:"session_id,omitempty"`
	ClientIP     ip_types.Address               `binapi:"address,name=client_ip" json:"client_ip,omitempty"`
	DecapVrfID   uint32                         `binapi:"u32,name=decap_vrf_id" json:"decap_vrf_id,omitempty"`
	ClientMac    ethernet_types.MacAddress      `binapi:"mac_address,name=client_mac" json:"client_mac,omitempty"`
	LocalMac     ethernet_types.MacAddress      `binapi:"mac_address,name=local_mac" json:"local_mac,omitempty"`
	EncapIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=encap_if_index" json:"encap_if_index,omitempty"`
	OuterVlan    uint16                         `binapi:"u16,name=outer_vlan" json:"outer_vlan,omitempty"`
	InnerVlan    uint16                         `binapi:"u16,name=inner_vlan" json:"inner_vlan,omitempty"`
}

func (m *OsvbngPppoeAddDelSession) Reset()               { *m = OsvbngPppoeAddDelSession{} }
func (*OsvbngPppoeAddDelSession) GetMessageName() string { return "osvbng_pppoe_add_del_session" }
func (*OsvbngPppoeAddDelSession) GetCrcString() string   { return "0ae5915d" }
func (*OsvbngPppoeAddDelSession) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngPppoeAddDelSession) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.IsAdd
	size += 2      // m.SessionID
	size += 1      // m.ClientIP.Af
	size += 1 * 16 // m.ClientIP.Un
	size += 4      // m.DecapVrfID
	size += 1 * 6  // m.ClientMac
	size += 1 * 6  // m.LocalMac
	size += 4      // m.EncapIfIndex
	size += 2      // m.OuterVlan
	size += 2      // m.InnerVlan
	return size
}
func (m *OsvbngPppoeAddDelSession) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint16(m.SessionID)
	buf.EncodeUint8(uint8(m.ClientIP.Af))
	buf.EncodeBytes(m.ClientIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint32(m.DecapVrfID)
	buf.EncodeBytes(m.ClientMac[:], 6)
	buf.EncodeBytes(m.LocalMac[:], 6)
	buf.EncodeUint32(uint32(m.EncapIfIndex))
	buf.EncodeUint16(m.OuterVlan)
	buf.EncodeUint16(m.InnerVlan)
	return buf.Bytes(), nil
}
func (m *OsvbngPppoeAddDelSession) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.SessionID = buf.DecodeUint16()
	m.ClientIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.ClientIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.DecapVrfID = buf.DecodeUint32()
	copy(m.ClientMac[:], buf.DecodeBytes(6))
	copy(m.LocalMac[:], buf.DecodeBytes(6))
	m.EncapIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.OuterVlan = buf.DecodeUint16()
	m.InnerVlan = buf.DecodeUint16()
	return nil
}

// reply for set or delete a PPPoE session
//   - retval - return code
//   - sw_if_index - software index of the interface
//
// OsvbngPppoeAddDelSessionReply defines message 'osvbng_pppoe_add_del_session_reply'.
type OsvbngPppoeAddDelSessionReply struct {
	Retval    int32                          `binapi:"i32,name=retval" json:"retval,omitempty"`
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *OsvbngPppoeAddDelSessionReply) Reset() { *m = OsvbngPppoeAddDelSessionReply{} }
func (*OsvbngPppoeAddDelSessionReply) GetMessageName() string {
	return "osvbng_pppoe_add_del_session_reply"
}
func (*OsvbngPppoeAddDelSessionReply) GetCrcString() string { return "5383d31f" }
func (*OsvbngPppoeAddDelSessionReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngPppoeAddDelSessionReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	size += 4 // m.SwIfIndex
	return size
}
func (m *OsvbngPppoeAddDelSessionReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *OsvbngPppoeAddDelSessionReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

// dump details of a PPPoE session
//   - sw_if_index - software index of the interface
//   - session_id - PPPoE session ID
//   - client_ip - PPPoE session's client address
//   - encap_if_index - the index of tx interface for pppoe encaped packet
//   - decap_vrf_id - the vrf index for pppoe decaped packet
//   - local_mac - the BNG ethernet address
//   - client_mac - the client ethernet address
//   - outer_vlan - S-VLAN tag
//   - inner_vlan - C-VLAN tag
//
// OsvbngPppoeSessionDetails defines message 'osvbng_pppoe_session_details'.
type OsvbngPppoeSessionDetails struct {
	SwIfIndex    interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	SessionID    uint16                         `binapi:"u16,name=session_id" json:"session_id,omitempty"`
	ClientIP     ip_types.Address               `binapi:"address,name=client_ip" json:"client_ip,omitempty"`
	EncapIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=encap_if_index" json:"encap_if_index,omitempty"`
	DecapVrfID   uint32                         `binapi:"u32,name=decap_vrf_id" json:"decap_vrf_id,omitempty"`
	LocalMac     ethernet_types.MacAddress      `binapi:"mac_address,name=local_mac" json:"local_mac,omitempty"`
	ClientMac    ethernet_types.MacAddress      `binapi:"mac_address,name=client_mac" json:"client_mac,omitempty"`
	OuterVlan    uint16                         `binapi:"u16,name=outer_vlan" json:"outer_vlan,omitempty"`
	InnerVlan    uint16                         `binapi:"u16,name=inner_vlan" json:"inner_vlan,omitempty"`
}

func (m *OsvbngPppoeSessionDetails) Reset()               { *m = OsvbngPppoeSessionDetails{} }
func (*OsvbngPppoeSessionDetails) GetMessageName() string { return "osvbng_pppoe_session_details" }
func (*OsvbngPppoeSessionDetails) GetCrcString() string   { return "97890e59" }
func (*OsvbngPppoeSessionDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngPppoeSessionDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.SwIfIndex
	size += 2      // m.SessionID
	size += 1      // m.ClientIP.Af
	size += 1 * 16 // m.ClientIP.Un
	size += 4      // m.EncapIfIndex
	size += 4      // m.DecapVrfID
	size += 1 * 6  // m.LocalMac
	size += 1 * 6  // m.ClientMac
	size += 2      // m.OuterVlan
	size += 2      // m.InnerVlan
	return size
}
func (m *OsvbngPppoeSessionDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeUint16(m.SessionID)
	buf.EncodeUint8(uint8(m.ClientIP.Af))
	buf.EncodeBytes(m.ClientIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint32(uint32(m.EncapIfIndex))
	buf.EncodeUint32(m.DecapVrfID)
	buf.EncodeBytes(m.LocalMac[:], 6)
	buf.EncodeBytes(m.ClientMac[:], 6)
	buf.EncodeUint16(m.OuterVlan)
	buf.EncodeUint16(m.InnerVlan)
	return buf.Bytes(), nil
}
func (m *OsvbngPppoeSessionDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.SessionID = buf.DecodeUint16()
	m.ClientIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.ClientIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.EncapIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.DecapVrfID = buf.DecodeUint32()
	copy(m.LocalMac[:], buf.DecodeBytes(6))
	copy(m.ClientMac[:], buf.DecodeBytes(6))
	m.OuterVlan = buf.DecodeUint16()
	m.InnerVlan = buf.DecodeUint16()
	return nil
}

// Dump PPPoE session
//   - sw_if_index - software index of the interface (~0 for all)
//
// OsvbngPppoeSessionDump defines message 'osvbng_pppoe_session_dump'.
type OsvbngPppoeSessionDump struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *OsvbngPppoeSessionDump) Reset()               { *m = OsvbngPppoeSessionDump{} }
func (*OsvbngPppoeSessionDump) GetMessageName() string { return "osvbng_pppoe_session_dump" }
func (*OsvbngPppoeSessionDump) GetCrcString() string   { return "f9e6675e" }
func (*OsvbngPppoeSessionDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngPppoeSessionDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.SwIfIndex
	return size
}
func (m *OsvbngPppoeSessionDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *OsvbngPppoeSessionDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

func init() { file_osvbng_pppoe_binapi_init() }
func file_osvbng_pppoe_binapi_init() {
	api.RegisterMessage((*OsvbngPppoeAddDelSession)(nil), "osvbng_pppoe_add_del_session_0ae5915d")
	api.RegisterMessage((*OsvbngPppoeAddDelSessionReply)(nil), "osvbng_pppoe_add_del_session_reply_5383d31f")
	api.RegisterMessage((*OsvbngPppoeSessionDetails)(nil), "osvbng_pppoe_session_details_97890e59")
	api.RegisterMessage((*OsvbngPppoeSessionDump)(nil), "osvbng_pppoe_session_dump_f9e6675e")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*OsvbngPppoeAddDelSession)(nil),
		(*OsvbngPppoeAddDelSessionReply)(nil),
		(*OsvbngPppoeSessionDetails)(nil),
		(*OsvbngPppoeSessionDump)(nil),
	}
}
