// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package osvbng_accounting

import (
	"context"
	"fmt"
	"io"

	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service osvbng_accounting.
type RPCService interface {
	OsvbngAcctInterfaceEnableDisable(ctx context.Context, in *OsvbngAcctInterfaceEnableDisable) (*OsvbngAcctInterfaceEnableDisableReply, error)
	OsvbngAcctSubscriberAdd(ctx context.Context, in *OsvbngAcctSubscriberAdd) (*OsvbngAcctSubscriberAddReply, error)
	OsvbngAcctSubscriberDel(ctx context.Context, in *OsvbngAcctSubscriberDel) (*OsvbngAcctSubscriberDelReply, error)
	OsvbngAcctSubscriberDump(ctx context.Context, in *OsvbngAcctSubscriberDump) (RPCService_OsvbngAcctSubscriberDumpClient, error)
	OsvbngAcctSubscriberGet(ctx context.Context, in *OsvbngAcctSubscriberGet) (*OsvbngAcctSubscriberGetReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) OsvbngAcctInterfaceEnableDisable(ctx context.Context, in *OsvbngAcctInterfaceEnableDisable) (*OsvbngAcctInterfaceEnableDisableReply, error) {
	out := new(OsvbngAcctInterfaceEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngAcctSubscriberAdd(ctx context.Context, in *OsvbngAcctSubscriberAdd) (*OsvbngAcctSubscriberAddReply, error) {
	out := new(OsvbngAcctSubscriberAddReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngAcctSubscriberDel(ctx context.Context, in *OsvbngAcctSubscriberDel) (*OsvbngAcctSubscriberDelReply, error) {
	out := new(OsvbngAcctSubscriberDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngAcctSubscriberDump(ctx context.Context, in *OsvbngAcctSubscriberDump) (RPCService_OsvbngAcctSubscriberDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_OsvbngAcctSubscriberDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_OsvbngAcctSubscriberDumpClient interface {
	Recv() (*OsvbngAcctSubscriberDetails, *OsvbngAcctSubscriberDumpReply, error)
	api.Stream
}

type serviceClient_OsvbngAcctSubscriberDumpClient struct {
	api.Stream
}

func (c *serviceClient_OsvbngAcctSubscriberDumpClient) Recv() (*OsvbngAcctSubscriberDetails, *OsvbngAcctSubscriberDumpReply, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, nil, err
	}
	switch m := msg.(type) {
	case *OsvbngAcctSubscriberDetails:
		return m, nil, nil
	case *OsvbngAcctSubscriberDumpReply:
		if err := api.RetvalToVPPApiError(m.Retval); err != nil {
			c.Stream.Close()
			return nil, m, err
		}
		err = c.Stream.Close()
		if err != nil {
			return nil, m, err
		}
		return nil, m, io.EOF
	default:
		return nil, nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) OsvbngAcctSubscriberGet(ctx context.Context, in *OsvbngAcctSubscriberGet) (*OsvbngAcctSubscriberGetReply, error) {
	out := new(OsvbngAcctSubscriberGetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
