// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              25.10.0-1~g07ca4b339
// source: plugins/osvbng_accounting.api.json

// Package osvbng_accounting contains generated bindings for API file osvbng_accounting.api.
//
// Contents:
// - 11 messages
package osvbng_accounting

import (
	interface_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/interface_types"
	ip_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/ip_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "osvbng_accounting"
	APIVersion = "1.0.0"
	VersionCrc = 0x73675ed5
)

// Enable/disable accounting on an interface
//   - sw_if_index - software interface index
//   - enable - enable (1) or disable (0)
//
// OsvbngAcctInterfaceEnableDisable defines message 'osvbng_acct_interface_enable_disable'.
type OsvbngAcctInterfaceEnableDisable struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	Enable    bool                           `binapi:"bool,name=enable" json:"enable,omitempty"`
}

func (m *OsvbngAcctInterfaceEnableDisable) Reset() { *m = OsvbngAcctInterfaceEnableDisable{} }
func (*OsvbngAcctInterfaceEnableDisable) GetMessageName() string {
	return "osvbng_acct_interface_enable_disable"
}
func (*OsvbngAcctInterfaceEnableDisable) GetCrcString() string { return "ae6cfcfb" }
func (*OsvbngAcctInterfaceEnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngAcctInterfaceEnableDisable) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.SwIfIndex
	size += 1 // m.Enable
	return size
}
func (m *OsvbngAcctInterfaceEnableDisable) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeBool(m.Enable)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctInterfaceEnableDisable) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.Enable = buf.DecodeBool()
	return nil
}

// OsvbngAcctInterfaceEnableDisableReply defines message 'osvbng_acct_interface_enable_disable_reply'.
type OsvbngAcctInterfaceEnableDisableReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngAcctInterfaceEnableDisableReply) Reset() { *m = OsvbngAcctInterfaceEnableDisableReply{} }
func (*OsvbngAcctInterfaceEnableDisableReply) GetMessageName() string {
	return "osvbng_acct_interface_enable_disable_reply"
}
func (*OsvbngAcctInterfaceEnableDisableReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngAcctInterfaceEnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngAcctInterfaceEnableDisableReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngAcctInterfaceEnableDisableReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctInterfaceEnableDisableReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Add a subscriber for accounting
//   - ip4_address - subscriber IPv4 address
//   - fib_index - VRF/FIB table index
//   - sw_if_index - software interface index
//   - session_id - accounting session ID (8 bytes)
//
// OsvbngAcctSubscriberAdd defines message 'osvbng_acct_subscriber_add'.
type OsvbngAcctSubscriberAdd struct {
	IP4Address ip_types.IP4Address            `binapi:"ip4_address,name=ip4_address" json:"ip4_address,omitempty"`
	FibIndex   uint32                         `binapi:"u32,name=fib_index" json:"fib_index,omitempty"`
	SwIfIndex  interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	SessionID  []byte                         `binapi:"u8[8],name=session_id" json:"session_id,omitempty"`
}

func (m *OsvbngAcctSubscriberAdd) Reset()               { *m = OsvbngAcctSubscriberAdd{} }
func (*OsvbngAcctSubscriberAdd) GetMessageName() string { return "osvbng_acct_subscriber_add" }
func (*OsvbngAcctSubscriberAdd) GetCrcString() string   { return "011037d6" }
func (*OsvbngAcctSubscriberAdd) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngAcctSubscriberAdd) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 4 // m.IP4Address
	size += 4     // m.FibIndex
	size += 4     // m.SwIfIndex
	size += 1 * 8 // m.SessionID
	return size
}
func (m *OsvbngAcctSubscriberAdd) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.IP4Address[:], 4)
	buf.EncodeUint32(m.FibIndex)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeBytes(m.SessionID, 8)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberAdd) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	copy(m.IP4Address[:], buf.DecodeBytes(4))
	m.FibIndex = buf.DecodeUint32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.SessionID = make([]byte, 8)
	copy(m.SessionID, buf.DecodeBytes(len(m.SessionID)))
	return nil
}

// OsvbngAcctSubscriberAddReply defines message 'osvbng_acct_subscriber_add_reply'.
type OsvbngAcctSubscriberAddReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngAcctSubscriberAddReply) Reset() { *m = OsvbngAcctSubscriberAddReply{} }
func (*OsvbngAcctSubscriberAddReply) GetMessageName() string {
	return "osvbng_acct_subscriber_add_reply"
}
func (*OsvbngAcctSubscriberAddReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngAcctSubscriberAddReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngAcctSubscriberAddReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngAcctSubscriberAddReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberAddReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Delete a subscriber from accounting
//   - ip4_address - subscriber IPv4 address
//   - fib_index - VRF/FIB table index
//
// OsvbngAcctSubscriberDel defines message 'osvbng_acct_subscriber_del'.
type OsvbngAcctSubscriberDel struct {
	IP4Address ip_types.IP4Address `binapi:"ip4_address,name=ip4_address" json:"ip4_address,omitempty"`
	FibIndex   uint32              `binapi:"u32,name=fib_index" json:"fib_index,omitempty"`
}

func (m *OsvbngAcctSubscriberDel) Reset()               { *m = OsvbngAcctSubscriberDel{} }
func (*OsvbngAcctSubscriberDel) GetMessageName() string { return "osvbng_acct_subscriber_del" }
func (*OsvbngAcctSubscriberDel) GetCrcString() string   { return "625c31e3" }
func (*OsvbngAcctSubscriberDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngAcctSubscriberDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 4 // m.IP4Address
	size += 4     // m.FibIndex
	return size
}
func (m *OsvbngAcctSubscriberDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.IP4Address[:], 4)
	buf.EncodeUint32(m.FibIndex)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	copy(m.IP4Address[:], buf.DecodeBytes(4))
	m.FibIndex = buf.DecodeUint32()
	return nil
}

// OsvbngAcctSubscriberDelReply defines message 'osvbng_acct_subscriber_del_reply'.
type OsvbngAcctSubscriberDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngAcctSubscriberDelReply) Reset() { *m = OsvbngAcctSubscriberDelReply{} }
func (*OsvbngAcctSubscriberDelReply) GetMessageName() string {
	return "osvbng_acct_subscriber_del_reply"
}
func (*OsvbngAcctSubscriberDelReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngAcctSubscriberDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngAcctSubscriberDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngAcctSubscriberDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// OsvbngAcctSubscriberDetails defines message 'osvbng_acct_subscriber_details'.
type OsvbngAcctSubscriberDetails struct {
	IP4Address ip_types.IP4Address            `binapi:"ip4_address,name=ip4_address" json:"ip4_address,omitempty"`
	FibIndex   uint32                         `binapi:"u32,name=fib_index" json:"fib_index,omitempty"`
	SwIfIndex  interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	PoolIndex  uint32                         `binapi:"u32,name=pool_index" json:"pool_index,omitempty"`
	SessionID  []byte                         `binapi:"u8[8],name=session_id" json:"session_id,omitempty"`
	RxPackets  uint64                         `binapi:"u64,name=rx_packets" json:"rx_packets,omitempty"`
	RxBytes    uint64                         `binapi:"u64,name=rx_bytes" json:"rx_bytes,omitempty"`
	TxPackets  uint64                         `binapi:"u64,name=tx_packets" json:"tx_packets,omitempty"`
	TxBytes    uint64                         `binapi:"u64,name=tx_bytes" json:"tx_bytes,omitempty"`
}

func (m *OsvbngAcctSubscriberDetails) Reset()               { *m = OsvbngAcctSubscriberDetails{} }
func (*OsvbngAcctSubscriberDetails) GetMessageName() string { return "osvbng_acct_subscriber_details" }
func (*OsvbngAcctSubscriberDetails) GetCrcString() string   { return "8fb496cf" }
func (*OsvbngAcctSubscriberDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngAcctSubscriberDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 4 // m.IP4Address
	size += 4     // m.FibIndex
	size += 4     // m.SwIfIndex
	size += 4     // m.PoolIndex
	size += 1 * 8 // m.SessionID
	size += 8     // m.RxPackets
	size += 8     // m.RxBytes
	size += 8     // m.TxPackets
	size += 8     // m.TxBytes
	return size
}
func (m *OsvbngAcctSubscriberDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.IP4Address[:], 4)
	buf.EncodeUint32(m.FibIndex)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeUint32(m.PoolIndex)
	buf.EncodeBytes(m.SessionID, 8)
	buf.EncodeUint64(m.RxPackets)
	buf.EncodeUint64(m.RxBytes)
	buf.EncodeUint64(m.TxPackets)
	buf.EncodeUint64(m.TxBytes)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	copy(m.IP4Address[:], buf.DecodeBytes(4))
	m.FibIndex = buf.DecodeUint32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.PoolIndex = buf.DecodeUint32()
	m.SessionID = make([]byte, 8)
	copy(m.SessionID, buf.DecodeBytes(len(m.SessionID)))
	m.RxPackets = buf.DecodeUint64()
	m.RxBytes = buf.DecodeUint64()
	m.TxPackets = buf.DecodeUint64()
	m.TxBytes = buf.DecodeUint64()
	return nil
}

// OsvbngAcctSubscriberDump defines message 'osvbng_acct_subscriber_dump'.
type OsvbngAcctSubscriberDump struct{}

func (m *OsvbngAcctSubscriberDump) Reset()               { *m = OsvbngAcctSubscriberDump{} }
func (*OsvbngAcctSubscriberDump) GetMessageName() string { return "osvbng_acct_subscriber_dump" }
func (*OsvbngAcctSubscriberDump) GetCrcString() string   { return "51077d14" }
func (*OsvbngAcctSubscriberDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngAcctSubscriberDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *OsvbngAcctSubscriberDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberDump) Unmarshal(b []byte) error {
	return nil
}

// OsvbngAcctSubscriberDumpReply defines message 'osvbng_acct_subscriber_dump_reply'.
type OsvbngAcctSubscriberDumpReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngAcctSubscriberDumpReply) Reset() { *m = OsvbngAcctSubscriberDumpReply{} }
func (*OsvbngAcctSubscriberDumpReply) GetMessageName() string {
	return "osvbng_acct_subscriber_dump_reply"
}
func (*OsvbngAcctSubscriberDumpReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngAcctSubscriberDumpReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngAcctSubscriberDumpReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngAcctSubscriberDumpReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberDumpReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// OsvbngAcctSubscriberGet defines message 'osvbng_acct_subscriber_get'.
type OsvbngAcctSubscriberGet struct {
	IP4Address ip_types.IP4Address `binapi:"ip4_address,name=ip4_address" json:"ip4_address,omitempty"`
	FibIndex   uint32              `binapi:"u32,name=fib_index" json:"fib_index,omitempty"`
}

func (m *OsvbngAcctSubscriberGet) Reset()               { *m = OsvbngAcctSubscriberGet{} }
func (*OsvbngAcctSubscriberGet) GetMessageName() string { return "osvbng_acct_subscriber_get" }
func (*OsvbngAcctSubscriberGet) GetCrcString() string   { return "625c31e3" }
func (*OsvbngAcctSubscriberGet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngAcctSubscriberGet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 4 // m.IP4Address
	size += 4     // m.FibIndex
	return size
}
func (m *OsvbngAcctSubscriberGet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.IP4Address[:], 4)
	buf.EncodeUint32(m.FibIndex)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberGet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	copy(m.IP4Address[:], buf.DecodeBytes(4))
	m.FibIndex = buf.DecodeUint32()
	return nil
}

// OsvbngAcctSubscriberGetReply defines message 'osvbng_acct_subscriber_get_reply'.
type OsvbngAcctSubscriberGetReply struct {
	Retval     int32                          `binapi:"i32,name=retval" json:"retval,omitempty"`
	IP4Address ip_types.IP4Address            `binapi:"ip4_address,name=ip4_address" json:"ip4_address,omitempty"`
	FibIndex   uint32                         `binapi:"u32,name=fib_index" json:"fib_index,omitempty"`
	SwIfIndex  interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	RxPackets  uint64                         `binapi:"u64,name=rx_packets" json:"rx_packets,omitempty"`
	RxBytes    uint64                         `binapi:"u64,name=rx_bytes" json:"rx_bytes,omitempty"`
	TxPackets  uint64                         `binapi:"u64,name=tx_packets" json:"tx_packets,omitempty"`
	TxBytes    uint64                         `binapi:"u64,name=tx_bytes" json:"tx_bytes,omitempty"`
}

func (m *OsvbngAcctSubscriberGetReply) Reset() { *m = OsvbngAcctSubscriberGetReply{} }
func (*OsvbngAcctSubscriberGetReply) GetMessageName() string {
	return "osvbng_acct_subscriber_get_reply"
}
func (*OsvbngAcctSubscriberGetReply) GetCrcString() string { return "88c8bba3" }
func (*OsvbngAcctSubscriberGetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngAcctSubscriberGetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4     // m.Retval
	size += 1 * 4 // m.IP4Address
	size += 4     // m.FibIndex
	size += 4     // m.SwIfIndex
	size += 8     // m.RxPackets
	size += 8     // m.RxBytes
	size += 8     // m.TxPackets
	size += 8     // m.TxBytes
	return size
}
func (m *OsvbngAcctSubscriberGetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeBytes(m.IP4Address[:], 4)
	buf.EncodeUint32(m.FibIndex)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeUint64(m.RxPackets)
	buf.EncodeUint64(m.RxBytes)
	buf.EncodeUint64(m.TxPackets)
	buf.EncodeUint64(m.TxBytes)
	return buf.Bytes(), nil
}
func (m *OsvbngAcctSubscriberGetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	copy(m.IP4Address[:], buf.DecodeBytes(4))
	m.FibIndex = buf.DecodeUint32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.RxPackets = buf.DecodeUint64()
	m.RxBytes = buf.DecodeUint64()
	m.TxPackets = buf.DecodeUint64()
	m.TxBytes = buf.DecodeUint64()
	return nil
}

func init() { file_osvbng_accounting_binapi_init() }
func file_osvbng_accounting_binapi_init() {
	api.RegisterMessage((*OsvbngAcctInterfaceEnableDisable)(nil), "osvbng_acct_interface_enable_disable_ae6cfcfb")
	api.RegisterMessage((*OsvbngAcctInterfaceEnableDisableReply)(nil), "osvbng_acct_interface_enable_disable_reply_e8d4e804")
	api.RegisterMessage((*OsvbngAcctSubscriberAdd)(nil), "osvbng_acct_subscriber_add_011037d6")
	api.RegisterMessage((*OsvbngAcctSubscriberAddReply)(nil), "osvbng_acct_subscriber_add_reply_e8d4e804")
	api.RegisterMessage((*OsvbngAcctSubscriberDel)(nil), "osvbng_acct_subscriber_del_625c31e3")
	api.RegisterMessage((*OsvbngAcctSubscriberDelReply)(nil), "osvbng_acct_subscriber_del_reply_e8d4e804")
	api.RegisterMessage((*OsvbngAcctSubscriberDetails)(nil), "osvbng_acct_subscriber_details_8fb496cf")
	api.RegisterMessage((*OsvbngAcctSubscriberDump)(nil), "osvbng_acct_subscriber_dump_51077d14")
	api.RegisterMessage((*OsvbngAcctSubscriberDumpReply)(nil), "osvbng_acct_subscriber_dump_reply_e8d4e804")
	api.RegisterMessage((*OsvbngAcctSubscriberGet)(nil), "osvbng_acct_subscriber_get_625c31e3")
	api.RegisterMessage((*OsvbngAcctSubscriberGetReply)(nil), "osvbng_acct_subscriber_get_reply_88c8bba3")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*OsvbngAcctInterfaceEnableDisable)(nil),
		(*OsvbngAcctInterfaceEnableDisableReply)(nil),
		(*OsvbngAcctSubscriberAdd)(nil),
		(*OsvbngAcctSubscriberAddReply)(nil),
		(*OsvbngAcctSubscriberDel)(nil),
		(*OsvbngAcctSubscriberDelReply)(nil),
		(*OsvbngAcctSubscriberDetails)(nil),
		(*OsvbngAcctSubscriberDump)(nil),
		(*OsvbngAcctSubscriberDumpReply)(nil),
		(*OsvbngAcctSubscriberGet)(nil),
		(*OsvbngAcctSubscriberGetReply)(nil),
	}
}
