// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              25.10-release
// source: plugins/osvbng_cgnat.api.json

// Package osvbng_cgnat contains generated bindings for API file osvbng_cgnat.api.
//
// Contents:
// -  3 enums
// -  3 structs
// - 32 messages
package osvbng_cgnat

import (
	"strconv"

	interface_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/interface_types"
	ip_types "github.com/veesix-networks/osvbng/pkg/vpp/binapi/ip_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "osvbng_cgnat"
	APIVersion = "1.0.0"
	VersionCrc = 0xf7c93636
)

// OsvbngCgnatAddressPooling defines enum 'osvbng_cgnat_address_pooling'.
type OsvbngCgnatAddressPooling uint8

const (
	OSVBNG_CGNAT_ADDRESS_POOLING_PAIRED    OsvbngCgnatAddressPooling = 0
	OSVBNG_CGNAT_ADDRESS_POOLING_ARBITRARY OsvbngCgnatAddressPooling = 1
)

var (
	OsvbngCgnatAddressPooling_name = map[uint8]string{
		0: "OSVBNG_CGNAT_ADDRESS_POOLING_PAIRED",
		1: "OSVBNG_CGNAT_ADDRESS_POOLING_ARBITRARY",
	}
	OsvbngCgnatAddressPooling_value = map[string]uint8{
		"OSVBNG_CGNAT_ADDRESS_POOLING_PAIRED":    0,
		"OSVBNG_CGNAT_ADDRESS_POOLING_ARBITRARY": 1,
	}
)

func (x OsvbngCgnatAddressPooling) String() string {
	s, ok := OsvbngCgnatAddressPooling_name[uint8(x)]
	if ok {
		return s
	}
	return "OsvbngCgnatAddressPooling(" + strconv.Itoa(int(x)) + ")"
}

// OsvbngCgnatFiltering defines enum 'osvbng_cgnat_filtering'.
type OsvbngCgnatFiltering uint8

const (
	OSVBNG_CGNAT_FILTERING_ENDPOINT_INDEPENDENT OsvbngCgnatFiltering = 0
	OSVBNG_CGNAT_FILTERING_ENDPOINT_DEPENDENT   OsvbngCgnatFiltering = 1
)

var (
	OsvbngCgnatFiltering_name = map[uint8]string{
		0: "OSVBNG_CGNAT_FILTERING_ENDPOINT_INDEPENDENT",
		1: "OSVBNG_CGNAT_FILTERING_ENDPOINT_DEPENDENT",
	}
	OsvbngCgnatFiltering_value = map[string]uint8{
		"OSVBNG_CGNAT_FILTERING_ENDPOINT_INDEPENDENT": 0,
		"OSVBNG_CGNAT_FILTERING_ENDPOINT_DEPENDENT":   1,
	}
)

func (x OsvbngCgnatFiltering) String() string {
	s, ok := OsvbngCgnatFiltering_name[uint8(x)]
	if ok {
		return s
	}
	return "OsvbngCgnatFiltering(" + strconv.Itoa(int(x)) + ")"
}

// OsvbngCgnatPoolMode defines enum 'osvbng_cgnat_pool_mode'.
type OsvbngCgnatPoolMode uint8

const (
	OSVBNG_CGNAT_POOL_MODE_PBA           OsvbngCgnatPoolMode = 0
	OSVBNG_CGNAT_POOL_MODE_DETERMINISTIC OsvbngCgnatPoolMode = 1
)

var (
	OsvbngCgnatPoolMode_name = map[uint8]string{
		0: "OSVBNG_CGNAT_POOL_MODE_PBA",
		1: "OSVBNG_CGNAT_POOL_MODE_DETERMINISTIC",
	}
	OsvbngCgnatPoolMode_value = map[string]uint8{
		"OSVBNG_CGNAT_POOL_MODE_PBA":           0,
		"OSVBNG_CGNAT_POOL_MODE_DETERMINISTIC": 1,
	}
)

func (x OsvbngCgnatPoolMode) String() string {
	s, ok := OsvbngCgnatPoolMode_name[uint8(x)]
	if ok {
		return s
	}
	return "OsvbngCgnatPoolMode(" + strconv.Itoa(int(x)) + ")"
}

// OsvbngCgnatBulkMappingEntry defines type 'osvbng_cgnat_bulk_mapping_entry'.
type OsvbngCgnatBulkMappingEntry struct {
	SwIfIndex      interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	InsideIP       ip_types.IP4Address            `binapi:"ip4_address,name=inside_ip" json:"inside_ip,omitempty"`
	InsideVrfID    uint32                         `binapi:"u32,name=inside_vrf_id" json:"inside_vrf_id,omitempty"`
	OutsideIP      ip_types.IP4Address            `binapi:"ip4_address,name=outside_ip" json:"outside_ip,omitempty"`
	PortBlockStart uint16                         `binapi:"u16,name=port_block_start" json:"port_block_start,omitempty"`
	PortBlockEnd   uint16                         `binapi:"u16,name=port_block_end" json:"port_block_end,omitempty"`
	EnableFeature  bool                           `binapi:"bool,name=enable_feature" json:"enable_feature,omitempty"`
}

// OsvbngCgnatInsidePrefix defines type 'osvbng_cgnat_inside_prefix'.
type OsvbngCgnatInsidePrefix struct {
	Prefix ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
	VrfID  uint32          `binapi:"u32,name=vrf_id" json:"vrf_id,omitempty"`
}

// OsvbngCgnatTimeouts defines type 'osvbng_cgnat_timeouts'.
type OsvbngCgnatTimeouts struct {
	TCPEstablished uint32 `binapi:"u32,name=tcp_established" json:"tcp_established,omitempty"`
	TCPTransitory  uint32 `binapi:"u32,name=tcp_transitory" json:"tcp_transitory,omitempty"`
	UDP            uint32 `binapi:"u32,name=udp" json:"udp,omitempty"`
	ICMP           uint32 `binapi:"u32,name=icmp" json:"icmp,omitempty"`
}

// Add or delete a bypass prefix (static IP subscribers skip NAT)
//   - is_add - add bypass if true, delete if false
//   - prefix - inside prefix to bypass (e.g. 203.0.113.0/24 or single /32)
//   - inside_vrf_id - subscriber VRF
//
// OsvbngCgnatAddDelBypass defines message 'osvbng_cgnat_add_del_bypass'.
type OsvbngCgnatAddDelBypass struct {
	IsAdd       bool            `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	Prefix      ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
	InsideVrfID uint32          `binapi:"u32,name=inside_vrf_id" json:"inside_vrf_id,omitempty"`
}

func (m *OsvbngCgnatAddDelBypass) Reset()               { *m = OsvbngCgnatAddDelBypass{} }
func (*OsvbngCgnatAddDelBypass) GetMessageName() string { return "osvbng_cgnat_add_del_bypass" }
func (*OsvbngCgnatAddDelBypass) GetCrcString() string   { return "a1ab2cd2" }
func (*OsvbngCgnatAddDelBypass) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatAddDelBypass) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.IsAdd
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	size += 4      // m.InsideVrfID
	return size
}
func (m *OsvbngCgnatAddDelBypass) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	buf.EncodeUint32(m.InsideVrfID)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatAddDelBypass) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	m.InsideVrfID = buf.DecodeUint32()
	return nil
}

// OsvbngCgnatAddDelBypassReply defines message 'osvbng_cgnat_add_del_bypass_reply'.
type OsvbngCgnatAddDelBypassReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatAddDelBypassReply) Reset() { *m = OsvbngCgnatAddDelBypassReply{} }
func (*OsvbngCgnatAddDelBypassReply) GetMessageName() string {
	return "osvbng_cgnat_add_del_bypass_reply"
}
func (*OsvbngCgnatAddDelBypassReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCgnatAddDelBypassReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatAddDelBypassReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatAddDelBypassReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatAddDelBypassReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Add or delete a subscriber mapping (PBA mode)
//   - is_add - add mapping if true, delete if false
//   - pool_id - pool this mapping belongs to
//   - sw_if_index - subscriber's per-session P2P interface
//   - inside_ip - subscriber inside IP
//   - inside_vrf_id - subscriber inside VRF
//   - outside_ip - allocated outside IP
//   - port_block_start - first port in allocated block
//   - port_block_end - last port in allocated block
//   - enable_feature - also enable cgnat-in2out feature on sw_if_index
//
// OsvbngCgnatAddDelSubscriberMapping defines message 'osvbng_cgnat_add_del_subscriber_mapping'.
type OsvbngCgnatAddDelSubscriberMapping struct {
	IsAdd          bool                           `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	PoolID         uint32                         `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	SwIfIndex      interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	InsideIP       ip_types.IP4Address            `binapi:"ip4_address,name=inside_ip" json:"inside_ip,omitempty"`
	InsideVrfID    uint32                         `binapi:"u32,name=inside_vrf_id" json:"inside_vrf_id,omitempty"`
	OutsideIP      ip_types.IP4Address            `binapi:"ip4_address,name=outside_ip" json:"outside_ip,omitempty"`
	PortBlockStart uint16                         `binapi:"u16,name=port_block_start" json:"port_block_start,omitempty"`
	PortBlockEnd   uint16                         `binapi:"u16,name=port_block_end" json:"port_block_end,omitempty"`
	EnableFeature  bool                           `binapi:"bool,name=enable_feature" json:"enable_feature,omitempty"`
}

func (m *OsvbngCgnatAddDelSubscriberMapping) Reset() { *m = OsvbngCgnatAddDelSubscriberMapping{} }
func (*OsvbngCgnatAddDelSubscriberMapping) GetMessageName() string {
	return "osvbng_cgnat_add_del_subscriber_mapping"
}
func (*OsvbngCgnatAddDelSubscriberMapping) GetCrcString() string { return "cd65f0f6" }
func (*OsvbngCgnatAddDelSubscriberMapping) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatAddDelSubscriberMapping) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1     // m.IsAdd
	size += 4     // m.PoolID
	size += 4     // m.SwIfIndex
	size += 1 * 4 // m.InsideIP
	size += 4     // m.InsideVrfID
	size += 1 * 4 // m.OutsideIP
	size += 2     // m.PortBlockStart
	size += 2     // m.PortBlockEnd
	size += 1     // m.EnableFeature
	return size
}
func (m *OsvbngCgnatAddDelSubscriberMapping) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeBytes(m.InsideIP[:], 4)
	buf.EncodeUint32(m.InsideVrfID)
	buf.EncodeBytes(m.OutsideIP[:], 4)
	buf.EncodeUint16(m.PortBlockStart)
	buf.EncodeUint16(m.PortBlockEnd)
	buf.EncodeBool(m.EnableFeature)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatAddDelSubscriberMapping) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.PoolID = buf.DecodeUint32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	copy(m.InsideIP[:], buf.DecodeBytes(4))
	m.InsideVrfID = buf.DecodeUint32()
	copy(m.OutsideIP[:], buf.DecodeBytes(4))
	m.PortBlockStart = buf.DecodeUint16()
	m.PortBlockEnd = buf.DecodeUint16()
	m.EnableFeature = buf.DecodeBool()
	return nil
}

// OsvbngCgnatAddDelSubscriberMappingReply defines message 'osvbng_cgnat_add_del_subscriber_mapping_reply'.
type OsvbngCgnatAddDelSubscriberMappingReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatAddDelSubscriberMappingReply) Reset() {
	*m = OsvbngCgnatAddDelSubscriberMappingReply{}
}
func (*OsvbngCgnatAddDelSubscriberMappingReply) GetMessageName() string {
	return "osvbng_cgnat_add_del_subscriber_mapping_reply"
}
func (*OsvbngCgnatAddDelSubscriberMappingReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCgnatAddDelSubscriberMappingReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatAddDelSubscriberMappingReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatAddDelSubscriberMappingReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatAddDelSubscriberMappingReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Bulk add subscriber mappings (for restart recovery)
//   - pool_id - pool these mappings belong to
//   - count - number of mappings
//
// OsvbngCgnatAddSubscriberMappingBulk defines message 'osvbng_cgnat_add_subscriber_mapping_bulk'.
type OsvbngCgnatAddSubscriberMappingBulk struct {
	PoolID   uint32                        `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	Count    uint32                        `binapi:"u32,name=count" json:"-"`
	Mappings []OsvbngCgnatBulkMappingEntry `binapi:"osvbng_cgnat_bulk_mapping_entry[count],name=mappings" json:"mappings,omitempty"`
}

func (m *OsvbngCgnatAddSubscriberMappingBulk) Reset() { *m = OsvbngCgnatAddSubscriberMappingBulk{} }
func (*OsvbngCgnatAddSubscriberMappingBulk) GetMessageName() string {
	return "osvbng_cgnat_add_subscriber_mapping_bulk"
}
func (*OsvbngCgnatAddSubscriberMappingBulk) GetCrcString() string { return "78614fbd" }
func (*OsvbngCgnatAddSubscriberMappingBulk) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatAddSubscriberMappingBulk) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	size += 4 // m.Count
	for j1 := 0; j1 < len(m.Mappings); j1++ {
		var s1 OsvbngCgnatBulkMappingEntry
		_ = s1
		if j1 < len(m.Mappings) {
			s1 = m.Mappings[j1]
		}
		size += 4     // s1.SwIfIndex
		size += 1 * 4 // s1.InsideIP
		size += 4     // s1.InsideVrfID
		size += 1 * 4 // s1.OutsideIP
		size += 2     // s1.PortBlockStart
		size += 2     // s1.PortBlockEnd
		size += 1     // s1.EnableFeature
	}
	return size
}
func (m *OsvbngCgnatAddSubscriberMappingBulk) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint32(uint32(len(m.Mappings)))
	for j0 := 0; j0 < len(m.Mappings); j0++ {
		var v0 OsvbngCgnatBulkMappingEntry // Mappings
		if j0 < len(m.Mappings) {
			v0 = m.Mappings[j0]
		}
		buf.EncodeUint32(uint32(v0.SwIfIndex))
		buf.EncodeBytes(v0.InsideIP[:], 4)
		buf.EncodeUint32(v0.InsideVrfID)
		buf.EncodeBytes(v0.OutsideIP[:], 4)
		buf.EncodeUint16(v0.PortBlockStart)
		buf.EncodeUint16(v0.PortBlockEnd)
		buf.EncodeBool(v0.EnableFeature)
	}
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatAddSubscriberMappingBulk) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	m.Count = buf.DecodeUint32()
	m.Mappings = make([]OsvbngCgnatBulkMappingEntry, m.Count)
	for j0 := 0; j0 < len(m.Mappings); j0++ {
		m.Mappings[j0].SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
		copy(m.Mappings[j0].InsideIP[:], buf.DecodeBytes(4))
		m.Mappings[j0].InsideVrfID = buf.DecodeUint32()
		copy(m.Mappings[j0].OutsideIP[:], buf.DecodeBytes(4))
		m.Mappings[j0].PortBlockStart = buf.DecodeUint16()
		m.Mappings[j0].PortBlockEnd = buf.DecodeUint16()
		m.Mappings[j0].EnableFeature = buf.DecodeBool()
	}
	return nil
}

// OsvbngCgnatAddSubscriberMappingBulkReply defines message 'osvbng_cgnat_add_subscriber_mapping_bulk_reply'.
type OsvbngCgnatAddSubscriberMappingBulkReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatAddSubscriberMappingBulkReply) Reset() {
	*m = OsvbngCgnatAddSubscriberMappingBulkReply{}
}
func (*OsvbngCgnatAddSubscriberMappingBulkReply) GetMessageName() string {
	return "osvbng_cgnat_add_subscriber_mapping_bulk_reply"
}
func (*OsvbngCgnatAddSubscriberMappingBulkReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCgnatAddSubscriberMappingBulkReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatAddSubscriberMappingBulkReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatAddSubscriberMappingBulkReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatAddSubscriberMappingBulkReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Enable CGNAT on a subscriber session (deterministic mode)
//   - is_enable - enable or disable
//   - pool_id - pool to use
//   - sw_if_index - subscriber's per-session P2P interface
//
// OsvbngCgnatEnableOnSession defines message 'osvbng_cgnat_enable_on_session'.
type OsvbngCgnatEnableOnSession struct {
	IsEnable  bool                           `binapi:"bool,name=is_enable" json:"is_enable,omitempty"`
	PoolID    uint32                         `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *OsvbngCgnatEnableOnSession) Reset()               { *m = OsvbngCgnatEnableOnSession{} }
func (*OsvbngCgnatEnableOnSession) GetMessageName() string { return "osvbng_cgnat_enable_on_session" }
func (*OsvbngCgnatEnableOnSession) GetCrcString() string   { return "b7da3880" }
func (*OsvbngCgnatEnableOnSession) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatEnableOnSession) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 // m.IsEnable
	size += 4 // m.PoolID
	size += 4 // m.SwIfIndex
	return size
}
func (m *OsvbngCgnatEnableOnSession) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsEnable)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatEnableOnSession) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsEnable = buf.DecodeBool()
	m.PoolID = buf.DecodeUint32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

// OsvbngCgnatEnableOnSessionReply defines message 'osvbng_cgnat_enable_on_session_reply'.
type OsvbngCgnatEnableOnSessionReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatEnableOnSessionReply) Reset() { *m = OsvbngCgnatEnableOnSessionReply{} }
func (*OsvbngCgnatEnableOnSessionReply) GetMessageName() string {
	return "osvbng_cgnat_enable_on_session_reply"
}
func (*OsvbngCgnatEnableOnSessionReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCgnatEnableOnSessionReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatEnableOnSessionReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatEnableOnSessionReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatEnableOnSessionReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Add or delete a CGNAT pool
//   - is_add - add pool if true, delete if false
//   - pool_id - unique pool identifier (assigned by control plane)
//   - mode - PBA or deterministic
//   - address_pooling - paired or arbitrary
//   - filtering - endpoint-independent or endpoint-dependent
//   - block_size - ports per block (PBA mode)
//   - max_blocks_per_sub - max port blocks per subscriber (PBA mode)
//   - max_sessions_per_sub - max concurrent sessions per subscriber
//   - port_range_start - first usable port (default 1024)
//   - port_range_end - last usable port (default 65535)
//   - port_reuse_timeout - seconds before port reuse (default 120)
//   - alg_bitmask - per-pool ALG enable flags (bit 0=FTP, 1=TFTP, 2=PPTP, 3=SIP, 4=RTSP, 5=DNS)
//   - timeouts - protocol-specific session timeouts
//
// OsvbngCgnatPoolAddDel defines message 'osvbng_cgnat_pool_add_del'.
type OsvbngCgnatPoolAddDel struct {
	IsAdd             bool                      `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	PoolID            uint32                    `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	Mode              OsvbngCgnatPoolMode       `binapi:"osvbng_cgnat_pool_mode,name=mode" json:"mode,omitempty"`
	AddressPooling    OsvbngCgnatAddressPooling `binapi:"osvbng_cgnat_address_pooling,name=address_pooling" json:"address_pooling,omitempty"`
	Filtering         OsvbngCgnatFiltering      `binapi:"osvbng_cgnat_filtering,name=filtering" json:"filtering,omitempty"`
	BlockSize         uint16                    `binapi:"u16,name=block_size" json:"block_size,omitempty"`
	MaxBlocksPerSub   uint8                     `binapi:"u8,name=max_blocks_per_sub" json:"max_blocks_per_sub,omitempty"`
	MaxSessionsPerSub uint32                    `binapi:"u32,name=max_sessions_per_sub" json:"max_sessions_per_sub,omitempty"`
	PortRangeStart    uint16                    `binapi:"u16,name=port_range_start" json:"port_range_start,omitempty"`
	PortRangeEnd      uint16                    `binapi:"u16,name=port_range_end" json:"port_range_end,omitempty"`
	PortReuseTimeout  uint16                    `binapi:"u16,name=port_reuse_timeout" json:"port_reuse_timeout,omitempty"`
	AlgBitmask        uint8                     `binapi:"u8,name=alg_bitmask" json:"alg_bitmask,omitempty"`
	Timeouts          OsvbngCgnatTimeouts       `binapi:"osvbng_cgnat_timeouts,name=timeouts" json:"timeouts,omitempty"`
}

func (m *OsvbngCgnatPoolAddDel) Reset()               { *m = OsvbngCgnatPoolAddDel{} }
func (*OsvbngCgnatPoolAddDel) GetMessageName() string { return "osvbng_cgnat_pool_add_del" }
func (*OsvbngCgnatPoolAddDel) GetCrcString() string   { return "22bb2f86" }
func (*OsvbngCgnatPoolAddDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatPoolAddDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 // m.IsAdd
	size += 4 // m.PoolID
	size += 1 // m.Mode
	size += 1 // m.AddressPooling
	size += 1 // m.Filtering
	size += 2 // m.BlockSize
	size += 1 // m.MaxBlocksPerSub
	size += 4 // m.MaxSessionsPerSub
	size += 2 // m.PortRangeStart
	size += 2 // m.PortRangeEnd
	size += 2 // m.PortReuseTimeout
	size += 1 // m.AlgBitmask
	size += 4 // m.Timeouts.TCPEstablished
	size += 4 // m.Timeouts.TCPTransitory
	size += 4 // m.Timeouts.UDP
	size += 4 // m.Timeouts.ICMP
	return size
}
func (m *OsvbngCgnatPoolAddDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint8(uint8(m.Mode))
	buf.EncodeUint8(uint8(m.AddressPooling))
	buf.EncodeUint8(uint8(m.Filtering))
	buf.EncodeUint16(m.BlockSize)
	buf.EncodeUint8(m.MaxBlocksPerSub)
	buf.EncodeUint32(m.MaxSessionsPerSub)
	buf.EncodeUint16(m.PortRangeStart)
	buf.EncodeUint16(m.PortRangeEnd)
	buf.EncodeUint16(m.PortReuseTimeout)
	buf.EncodeUint8(m.AlgBitmask)
	buf.EncodeUint32(m.Timeouts.TCPEstablished)
	buf.EncodeUint32(m.Timeouts.TCPTransitory)
	buf.EncodeUint32(m.Timeouts.UDP)
	buf.EncodeUint32(m.Timeouts.ICMP)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolAddDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.PoolID = buf.DecodeUint32()
	m.Mode = OsvbngCgnatPoolMode(buf.DecodeUint8())
	m.AddressPooling = OsvbngCgnatAddressPooling(buf.DecodeUint8())
	m.Filtering = OsvbngCgnatFiltering(buf.DecodeUint8())
	m.BlockSize = buf.DecodeUint16()
	m.MaxBlocksPerSub = buf.DecodeUint8()
	m.MaxSessionsPerSub = buf.DecodeUint32()
	m.PortRangeStart = buf.DecodeUint16()
	m.PortRangeEnd = buf.DecodeUint16()
	m.PortReuseTimeout = buf.DecodeUint16()
	m.AlgBitmask = buf.DecodeUint8()
	m.Timeouts.TCPEstablished = buf.DecodeUint32()
	m.Timeouts.TCPTransitory = buf.DecodeUint32()
	m.Timeouts.UDP = buf.DecodeUint32()
	m.Timeouts.ICMP = buf.DecodeUint32()
	return nil
}

// Add or delete an inside prefix on a pool
//   - is_add - add prefix if true, delete if false
//   - pool_id - pool identifier
//   - prefix - inside prefix (e.g. 100.64.0.0/16)
//   - vrf_id - VRF for this inside prefix
//
// OsvbngCgnatPoolAddDelInsidePrefix defines message 'osvbng_cgnat_pool_add_del_inside_prefix'.
type OsvbngCgnatPoolAddDelInsidePrefix struct {
	IsAdd  bool            `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	PoolID uint32          `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	Prefix ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
	VrfID  uint32          `binapi:"u32,name=vrf_id" json:"vrf_id,omitempty"`
}

func (m *OsvbngCgnatPoolAddDelInsidePrefix) Reset() { *m = OsvbngCgnatPoolAddDelInsidePrefix{} }
func (*OsvbngCgnatPoolAddDelInsidePrefix) GetMessageName() string {
	return "osvbng_cgnat_pool_add_del_inside_prefix"
}
func (*OsvbngCgnatPoolAddDelInsidePrefix) GetCrcString() string { return "5afa7500" }
func (*OsvbngCgnatPoolAddDelInsidePrefix) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatPoolAddDelInsidePrefix) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.IsAdd
	size += 4      // m.PoolID
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	size += 4      // m.VrfID
	return size
}
func (m *OsvbngCgnatPoolAddDelInsidePrefix) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	buf.EncodeUint32(m.VrfID)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolAddDelInsidePrefix) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.PoolID = buf.DecodeUint32()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	m.VrfID = buf.DecodeUint32()
	return nil
}

// OsvbngCgnatPoolAddDelInsidePrefixReply defines message 'osvbng_cgnat_pool_add_del_inside_prefix_reply'.
type OsvbngCgnatPoolAddDelInsidePrefixReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatPoolAddDelInsidePrefixReply) Reset() {
	*m = OsvbngCgnatPoolAddDelInsidePrefixReply{}
}
func (*OsvbngCgnatPoolAddDelInsidePrefixReply) GetMessageName() string {
	return "osvbng_cgnat_pool_add_del_inside_prefix_reply"
}
func (*OsvbngCgnatPoolAddDelInsidePrefixReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCgnatPoolAddDelInsidePrefixReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatPoolAddDelInsidePrefixReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatPoolAddDelInsidePrefixReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolAddDelInsidePrefixReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Add or delete an outside address range on a pool
//   - is_add - add range if true, delete if false
//   - pool_id - pool identifier
//   - prefix - outside address range (e.g. 203.0.113.0/24)
//
// OsvbngCgnatPoolAddDelOutsideAddress defines message 'osvbng_cgnat_pool_add_del_outside_address'.
type OsvbngCgnatPoolAddDelOutsideAddress struct {
	IsAdd  bool            `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	PoolID uint32          `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	Prefix ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
}

func (m *OsvbngCgnatPoolAddDelOutsideAddress) Reset() { *m = OsvbngCgnatPoolAddDelOutsideAddress{} }
func (*OsvbngCgnatPoolAddDelOutsideAddress) GetMessageName() string {
	return "osvbng_cgnat_pool_add_del_outside_address"
}
func (*OsvbngCgnatPoolAddDelOutsideAddress) GetCrcString() string { return "9142422f" }
func (*OsvbngCgnatPoolAddDelOutsideAddress) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatPoolAddDelOutsideAddress) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.IsAdd
	size += 4      // m.PoolID
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	return size
}
func (m *OsvbngCgnatPoolAddDelOutsideAddress) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolAddDelOutsideAddress) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.PoolID = buf.DecodeUint32()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	return nil
}

// OsvbngCgnatPoolAddDelOutsideAddressReply defines message 'osvbng_cgnat_pool_add_del_outside_address_reply'.
type OsvbngCgnatPoolAddDelOutsideAddressReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatPoolAddDelOutsideAddressReply) Reset() {
	*m = OsvbngCgnatPoolAddDelOutsideAddressReply{}
}
func (*OsvbngCgnatPoolAddDelOutsideAddressReply) GetMessageName() string {
	return "osvbng_cgnat_pool_add_del_outside_address_reply"
}
func (*OsvbngCgnatPoolAddDelOutsideAddressReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCgnatPoolAddDelOutsideAddressReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatPoolAddDelOutsideAddressReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatPoolAddDelOutsideAddressReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolAddDelOutsideAddressReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// OsvbngCgnatPoolAddDelReply defines message 'osvbng_cgnat_pool_add_del_reply'.
type OsvbngCgnatPoolAddDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatPoolAddDelReply) Reset()               { *m = OsvbngCgnatPoolAddDelReply{} }
func (*OsvbngCgnatPoolAddDelReply) GetMessageName() string { return "osvbng_cgnat_pool_add_del_reply" }
func (*OsvbngCgnatPoolAddDelReply) GetCrcString() string   { return "e8d4e804" }
func (*OsvbngCgnatPoolAddDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatPoolAddDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatPoolAddDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolAddDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// OsvbngCgnatPoolDetails defines message 'osvbng_cgnat_pool_details'.
type OsvbngCgnatPoolDetails struct {
	PoolID            uint32                    `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	Mode              OsvbngCgnatPoolMode       `binapi:"osvbng_cgnat_pool_mode,name=mode" json:"mode,omitempty"`
	AddressPooling    OsvbngCgnatAddressPooling `binapi:"osvbng_cgnat_address_pooling,name=address_pooling" json:"address_pooling,omitempty"`
	Filtering         OsvbngCgnatFiltering      `binapi:"osvbng_cgnat_filtering,name=filtering" json:"filtering,omitempty"`
	BlockSize         uint16                    `binapi:"u16,name=block_size" json:"block_size,omitempty"`
	MaxBlocksPerSub   uint8                     `binapi:"u8,name=max_blocks_per_sub" json:"max_blocks_per_sub,omitempty"`
	MaxSessionsPerSub uint32                    `binapi:"u32,name=max_sessions_per_sub" json:"max_sessions_per_sub,omitempty"`
	PortRangeStart    uint16                    `binapi:"u16,name=port_range_start" json:"port_range_start,omitempty"`
	PortRangeEnd      uint16                    `binapi:"u16,name=port_range_end" json:"port_range_end,omitempty"`
	PortReuseTimeout  uint16                    `binapi:"u16,name=port_reuse_timeout" json:"port_reuse_timeout,omitempty"`
	AlgBitmask        uint8                     `binapi:"u8,name=alg_bitmask" json:"alg_bitmask,omitempty"`
	Timeouts          OsvbngCgnatTimeouts       `binapi:"osvbng_cgnat_timeouts,name=timeouts" json:"timeouts,omitempty"`
	OutsideVrfTableID uint32                    `binapi:"u32,name=outside_vrf_table_id" json:"outside_vrf_table_id,omitempty"`
	ActiveMappings    uint32                    `binapi:"u32,name=active_mappings" json:"active_mappings,omitempty"`
}

func (m *OsvbngCgnatPoolDetails) Reset()               { *m = OsvbngCgnatPoolDetails{} }
func (*OsvbngCgnatPoolDetails) GetMessageName() string { return "osvbng_cgnat_pool_details" }
func (*OsvbngCgnatPoolDetails) GetCrcString() string   { return "bf778eb1" }
func (*OsvbngCgnatPoolDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatPoolDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	size += 1 // m.Mode
	size += 1 // m.AddressPooling
	size += 1 // m.Filtering
	size += 2 // m.BlockSize
	size += 1 // m.MaxBlocksPerSub
	size += 4 // m.MaxSessionsPerSub
	size += 2 // m.PortRangeStart
	size += 2 // m.PortRangeEnd
	size += 2 // m.PortReuseTimeout
	size += 1 // m.AlgBitmask
	size += 4 // m.Timeouts.TCPEstablished
	size += 4 // m.Timeouts.TCPTransitory
	size += 4 // m.Timeouts.UDP
	size += 4 // m.Timeouts.ICMP
	size += 4 // m.OutsideVrfTableID
	size += 4 // m.ActiveMappings
	return size
}
func (m *OsvbngCgnatPoolDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint8(uint8(m.Mode))
	buf.EncodeUint8(uint8(m.AddressPooling))
	buf.EncodeUint8(uint8(m.Filtering))
	buf.EncodeUint16(m.BlockSize)
	buf.EncodeUint8(m.MaxBlocksPerSub)
	buf.EncodeUint32(m.MaxSessionsPerSub)
	buf.EncodeUint16(m.PortRangeStart)
	buf.EncodeUint16(m.PortRangeEnd)
	buf.EncodeUint16(m.PortReuseTimeout)
	buf.EncodeUint8(m.AlgBitmask)
	buf.EncodeUint32(m.Timeouts.TCPEstablished)
	buf.EncodeUint32(m.Timeouts.TCPTransitory)
	buf.EncodeUint32(m.Timeouts.UDP)
	buf.EncodeUint32(m.Timeouts.ICMP)
	buf.EncodeUint32(m.OutsideVrfTableID)
	buf.EncodeUint32(m.ActiveMappings)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	m.Mode = OsvbngCgnatPoolMode(buf.DecodeUint8())
	m.AddressPooling = OsvbngCgnatAddressPooling(buf.DecodeUint8())
	m.Filtering = OsvbngCgnatFiltering(buf.DecodeUint8())
	m.BlockSize = buf.DecodeUint16()
	m.MaxBlocksPerSub = buf.DecodeUint8()
	m.MaxSessionsPerSub = buf.DecodeUint32()
	m.PortRangeStart = buf.DecodeUint16()
	m.PortRangeEnd = buf.DecodeUint16()
	m.PortReuseTimeout = buf.DecodeUint16()
	m.AlgBitmask = buf.DecodeUint8()
	m.Timeouts.TCPEstablished = buf.DecodeUint32()
	m.Timeouts.TCPTransitory = buf.DecodeUint32()
	m.Timeouts.UDP = buf.DecodeUint32()
	m.Timeouts.ICMP = buf.DecodeUint32()
	m.OutsideVrfTableID = buf.DecodeUint32()
	m.ActiveMappings = buf.DecodeUint32()
	return nil
}

// Dump pools (~0 for all)
// OsvbngCgnatPoolDump defines message 'osvbng_cgnat_pool_dump'.
type OsvbngCgnatPoolDump struct {
	PoolID uint32 `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
}

func (m *OsvbngCgnatPoolDump) Reset()               { *m = OsvbngCgnatPoolDump{} }
func (*OsvbngCgnatPoolDump) GetMessageName() string { return "osvbng_cgnat_pool_dump" }
func (*OsvbngCgnatPoolDump) GetCrcString() string   { return "f797ec5c" }
func (*OsvbngCgnatPoolDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatPoolDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	return size
}
func (m *OsvbngCgnatPoolDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	return nil
}

// OsvbngCgnatPoolInsidePrefixDetails defines message 'osvbng_cgnat_pool_inside_prefix_details'.
type OsvbngCgnatPoolInsidePrefixDetails struct {
	PoolID uint32          `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	Prefix ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
	VrfID  uint32          `binapi:"u32,name=vrf_id" json:"vrf_id,omitempty"`
}

func (m *OsvbngCgnatPoolInsidePrefixDetails) Reset() { *m = OsvbngCgnatPoolInsidePrefixDetails{} }
func (*OsvbngCgnatPoolInsidePrefixDetails) GetMessageName() string {
	return "osvbng_cgnat_pool_inside_prefix_details"
}
func (*OsvbngCgnatPoolInsidePrefixDetails) GetCrcString() string { return "5b82b5f2" }
func (*OsvbngCgnatPoolInsidePrefixDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatPoolInsidePrefixDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.PoolID
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	size += 4      // m.VrfID
	return size
}
func (m *OsvbngCgnatPoolInsidePrefixDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	buf.EncodeUint32(m.VrfID)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolInsidePrefixDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	m.VrfID = buf.DecodeUint32()
	return nil
}

// Dump inside prefixes for a pool (~0 for all pools)
// OsvbngCgnatPoolInsidePrefixDump defines message 'osvbng_cgnat_pool_inside_prefix_dump'.
type OsvbngCgnatPoolInsidePrefixDump struct {
	PoolID uint32 `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
}

func (m *OsvbngCgnatPoolInsidePrefixDump) Reset() { *m = OsvbngCgnatPoolInsidePrefixDump{} }
func (*OsvbngCgnatPoolInsidePrefixDump) GetMessageName() string {
	return "osvbng_cgnat_pool_inside_prefix_dump"
}
func (*OsvbngCgnatPoolInsidePrefixDump) GetCrcString() string { return "f797ec5c" }
func (*OsvbngCgnatPoolInsidePrefixDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatPoolInsidePrefixDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	return size
}
func (m *OsvbngCgnatPoolInsidePrefixDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolInsidePrefixDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	return nil
}

// OsvbngCgnatPoolOutsideAddressDetails defines message 'osvbng_cgnat_pool_outside_address_details'.
type OsvbngCgnatPoolOutsideAddressDetails struct {
	PoolID uint32          `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	Prefix ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
}

func (m *OsvbngCgnatPoolOutsideAddressDetails) Reset() { *m = OsvbngCgnatPoolOutsideAddressDetails{} }
func (*OsvbngCgnatPoolOutsideAddressDetails) GetMessageName() string {
	return "osvbng_cgnat_pool_outside_address_details"
}
func (*OsvbngCgnatPoolOutsideAddressDetails) GetCrcString() string { return "a3f82407" }
func (*OsvbngCgnatPoolOutsideAddressDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatPoolOutsideAddressDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.PoolID
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	return size
}
func (m *OsvbngCgnatPoolOutsideAddressDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolOutsideAddressDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	return nil
}

// Dump outside addresses for a pool (~0 for all pools)
// OsvbngCgnatPoolOutsideAddressDump defines message 'osvbng_cgnat_pool_outside_address_dump'.
type OsvbngCgnatPoolOutsideAddressDump struct {
	PoolID uint32 `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
}

func (m *OsvbngCgnatPoolOutsideAddressDump) Reset() { *m = OsvbngCgnatPoolOutsideAddressDump{} }
func (*OsvbngCgnatPoolOutsideAddressDump) GetMessageName() string {
	return "osvbng_cgnat_pool_outside_address_dump"
}
func (*OsvbngCgnatPoolOutsideAddressDump) GetCrcString() string { return "f797ec5c" }
func (*OsvbngCgnatPoolOutsideAddressDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatPoolOutsideAddressDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	return size
}
func (m *OsvbngCgnatPoolOutsideAddressDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolOutsideAddressDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	return nil
}

// Refcnt-enable/disable ip4-sv-reassembly on an outside interface
//
//	Required because the cgnat-in2out fast path reads L4 ports out of
//	vnet_buffer(b)->ip.reass.* (populated by ip4-sv-reassembly upstream).
//	Each outside interface must be refcnt-enabled once per pool that
//	references it; the refcount is global per sw_if so multiple pools
//	sharing an outside interface compose correctly.
//	- pool_id - pool that owns this outside interface entry
//	- sw_if_index - outside interface
//	- is_add - add (refcnt up) if true, delete (refcnt down) if false
//
// OsvbngCgnatPoolOutsideInterfaceAddDel defines message 'osvbng_cgnat_pool_outside_interface_add_del'.
type OsvbngCgnatPoolOutsideInterfaceAddDel struct {
	PoolID    uint32                         `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	IsAdd     bool                           `binapi:"bool,name=is_add" json:"is_add,omitempty"`
}

func (m *OsvbngCgnatPoolOutsideInterfaceAddDel) Reset() { *m = OsvbngCgnatPoolOutsideInterfaceAddDel{} }
func (*OsvbngCgnatPoolOutsideInterfaceAddDel) GetMessageName() string {
	return "osvbng_cgnat_pool_outside_interface_add_del"
}
func (*OsvbngCgnatPoolOutsideInterfaceAddDel) GetCrcString() string { return "00ef9780" }
func (*OsvbngCgnatPoolOutsideInterfaceAddDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatPoolOutsideInterfaceAddDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	size += 4 // m.SwIfIndex
	size += 1 // m.IsAdd
	return size
}
func (m *OsvbngCgnatPoolOutsideInterfaceAddDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeBool(m.IsAdd)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolOutsideInterfaceAddDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.IsAdd = buf.DecodeBool()
	return nil
}

// OsvbngCgnatPoolOutsideInterfaceAddDelReply defines message 'osvbng_cgnat_pool_outside_interface_add_del_reply'.
type OsvbngCgnatPoolOutsideInterfaceAddDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatPoolOutsideInterfaceAddDelReply) Reset() {
	*m = OsvbngCgnatPoolOutsideInterfaceAddDelReply{}
}
func (*OsvbngCgnatPoolOutsideInterfaceAddDelReply) GetMessageName() string {
	return "osvbng_cgnat_pool_outside_interface_add_del_reply"
}
func (*OsvbngCgnatPoolOutsideInterfaceAddDelReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCgnatPoolOutsideInterfaceAddDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatPoolOutsideInterfaceAddDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatPoolOutsideInterfaceAddDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolOutsideInterfaceAddDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Update pool parameters at runtime
//   - pool_id - pool to update
//   - max_sessions_per_sub - new session limit
//   - alg_bitmask - new ALG flags
//   - timeouts - new timeout values
//
// OsvbngCgnatPoolUpdate defines message 'osvbng_cgnat_pool_update'.
type OsvbngCgnatPoolUpdate struct {
	PoolID            uint32              `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	MaxSessionsPerSub uint32              `binapi:"u32,name=max_sessions_per_sub" json:"max_sessions_per_sub,omitempty"`
	AlgBitmask        uint8               `binapi:"u8,name=alg_bitmask" json:"alg_bitmask,omitempty"`
	Timeouts          OsvbngCgnatTimeouts `binapi:"osvbng_cgnat_timeouts,name=timeouts" json:"timeouts,omitempty"`
}

func (m *OsvbngCgnatPoolUpdate) Reset()               { *m = OsvbngCgnatPoolUpdate{} }
func (*OsvbngCgnatPoolUpdate) GetMessageName() string { return "osvbng_cgnat_pool_update" }
func (*OsvbngCgnatPoolUpdate) GetCrcString() string   { return "311437fa" }
func (*OsvbngCgnatPoolUpdate) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatPoolUpdate) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	size += 4 // m.MaxSessionsPerSub
	size += 1 // m.AlgBitmask
	size += 4 // m.Timeouts.TCPEstablished
	size += 4 // m.Timeouts.TCPTransitory
	size += 4 // m.Timeouts.UDP
	size += 4 // m.Timeouts.ICMP
	return size
}
func (m *OsvbngCgnatPoolUpdate) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint32(m.MaxSessionsPerSub)
	buf.EncodeUint8(m.AlgBitmask)
	buf.EncodeUint32(m.Timeouts.TCPEstablished)
	buf.EncodeUint32(m.Timeouts.TCPTransitory)
	buf.EncodeUint32(m.Timeouts.UDP)
	buf.EncodeUint32(m.Timeouts.ICMP)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolUpdate) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	m.MaxSessionsPerSub = buf.DecodeUint32()
	m.AlgBitmask = buf.DecodeUint8()
	m.Timeouts.TCPEstablished = buf.DecodeUint32()
	m.Timeouts.TCPTransitory = buf.DecodeUint32()
	m.Timeouts.UDP = buf.DecodeUint32()
	m.Timeouts.ICMP = buf.DecodeUint32()
	return nil
}

// OsvbngCgnatPoolUpdateReply defines message 'osvbng_cgnat_pool_update_reply'.
type OsvbngCgnatPoolUpdateReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatPoolUpdateReply) Reset()               { *m = OsvbngCgnatPoolUpdateReply{} }
func (*OsvbngCgnatPoolUpdateReply) GetMessageName() string { return "osvbng_cgnat_pool_update_reply" }
func (*OsvbngCgnatPoolUpdateReply) GetCrcString() string   { return "e8d4e804" }
func (*OsvbngCgnatPoolUpdateReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatPoolUpdateReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatPoolUpdateReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatPoolUpdateReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// Count active CGNAT sessions (global, O(1) — no table walk).
// OsvbngCgnatSessionCount defines message 'osvbng_cgnat_session_count'.
type OsvbngCgnatSessionCount struct{}

func (m *OsvbngCgnatSessionCount) Reset()               { *m = OsvbngCgnatSessionCount{} }
func (*OsvbngCgnatSessionCount) GetMessageName() string { return "osvbng_cgnat_session_count" }
func (*OsvbngCgnatSessionCount) GetCrcString() string   { return "51077d14" }
func (*OsvbngCgnatSessionCount) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatSessionCount) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *OsvbngCgnatSessionCount) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatSessionCount) Unmarshal(b []byte) error {
	return nil
}

// OsvbngCgnatSessionCountReply defines message 'osvbng_cgnat_session_count_reply'.
type OsvbngCgnatSessionCountReply struct {
	Retval int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	Total  uint64 `binapi:"u64,name=total" json:"total,omitempty"`
}

func (m *OsvbngCgnatSessionCountReply) Reset() { *m = OsvbngCgnatSessionCountReply{} }
func (*OsvbngCgnatSessionCountReply) GetMessageName() string {
	return "osvbng_cgnat_session_count_reply"
}
func (*OsvbngCgnatSessionCountReply) GetCrcString() string { return "f88ba2bd" }
func (*OsvbngCgnatSessionCountReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatSessionCountReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	size += 8 // m.Total
	return size
}
func (m *OsvbngCgnatSessionCountReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint64(m.Total)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatSessionCountReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.Total = buf.DecodeUint64()
	return nil
}

// One active CGNAT session. Ports host-order; age is seconds since the
//
//	session was last active (computed at dump time).
//
// OsvbngCgnatSessionDetails defines message 'osvbng_cgnat_session_details'.
type OsvbngCgnatSessionDetails struct {
	SessionIndex   uint32              `binapi:"u32,name=session_index" json:"session_index,omitempty"`
	PoolID         uint32              `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	InsideIP       ip_types.IP4Address `binapi:"ip4_address,name=inside_ip" json:"inside_ip,omitempty"`
	OutsideIP      ip_types.IP4Address `binapi:"ip4_address,name=outside_ip" json:"outside_ip,omitempty"`
	RemoteIP       ip_types.IP4Address `binapi:"ip4_address,name=remote_ip" json:"remote_ip,omitempty"`
	InsidePort     uint16              `binapi:"u16,name=inside_port" json:"inside_port,omitempty"`
	OutsidePort    uint16              `binapi:"u16,name=outside_port" json:"outside_port,omitempty"`
	RemotePort     uint16              `binapi:"u16,name=remote_port" json:"remote_port,omitempty"`
	Proto          uint8               `binapi:"u8,name=proto" json:"proto,omitempty"`
	AlgFlags       uint8               `binapi:"u8,name=alg_flags" json:"alg_flags,omitempty"`
	InsideFibIndex uint32              `binapi:"u32,name=inside_fib_index" json:"inside_fib_index,omitempty"`
	MappingIndex   uint32              `binapi:"u32,name=mapping_index" json:"mapping_index,omitempty"`
	Age            float64             `binapi:"f64,name=age" json:"age,omitempty"`
	Timeout        uint32              `binapi:"u32,name=timeout" json:"timeout,omitempty"`
	TotalPkts      uint64              `binapi:"u64,name=total_pkts" json:"total_pkts,omitempty"`
	TotalBytes     uint64              `binapi:"u64,name=total_bytes" json:"total_bytes,omitempty"`
}

func (m *OsvbngCgnatSessionDetails) Reset()               { *m = OsvbngCgnatSessionDetails{} }
func (*OsvbngCgnatSessionDetails) GetMessageName() string { return "osvbng_cgnat_session_details" }
func (*OsvbngCgnatSessionDetails) GetCrcString() string   { return "20cd8049" }
func (*OsvbngCgnatSessionDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatSessionDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4     // m.SessionIndex
	size += 4     // m.PoolID
	size += 1 * 4 // m.InsideIP
	size += 1 * 4 // m.OutsideIP
	size += 1 * 4 // m.RemoteIP
	size += 2     // m.InsidePort
	size += 2     // m.OutsidePort
	size += 2     // m.RemotePort
	size += 1     // m.Proto
	size += 1     // m.AlgFlags
	size += 4     // m.InsideFibIndex
	size += 4     // m.MappingIndex
	size += 8     // m.Age
	size += 4     // m.Timeout
	size += 8     // m.TotalPkts
	size += 8     // m.TotalBytes
	return size
}
func (m *OsvbngCgnatSessionDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.SessionIndex)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeBytes(m.InsideIP[:], 4)
	buf.EncodeBytes(m.OutsideIP[:], 4)
	buf.EncodeBytes(m.RemoteIP[:], 4)
	buf.EncodeUint16(m.InsidePort)
	buf.EncodeUint16(m.OutsidePort)
	buf.EncodeUint16(m.RemotePort)
	buf.EncodeUint8(m.Proto)
	buf.EncodeUint8(m.AlgFlags)
	buf.EncodeUint32(m.InsideFibIndex)
	buf.EncodeUint32(m.MappingIndex)
	buf.EncodeFloat64(m.Age)
	buf.EncodeUint32(m.Timeout)
	buf.EncodeUint64(m.TotalPkts)
	buf.EncodeUint64(m.TotalBytes)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatSessionDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SessionIndex = buf.DecodeUint32()
	m.PoolID = buf.DecodeUint32()
	copy(m.InsideIP[:], buf.DecodeBytes(4))
	copy(m.OutsideIP[:], buf.DecodeBytes(4))
	copy(m.RemoteIP[:], buf.DecodeBytes(4))
	m.InsidePort = buf.DecodeUint16()
	m.OutsidePort = buf.DecodeUint16()
	m.RemotePort = buf.DecodeUint16()
	m.Proto = buf.DecodeUint8()
	m.AlgFlags = buf.DecodeUint8()
	m.InsideFibIndex = buf.DecodeUint32()
	m.MappingIndex = buf.DecodeUint32()
	m.Age = buf.DecodeFloat64()
	m.Timeout = buf.DecodeUint32()
	m.TotalPkts = buf.DecodeUint64()
	m.TotalBytes = buf.DecodeUint64()
	return nil
}

// Dump active CGNAT sessions (translations), filtered and windowed.
//
//	All filter fields are optional: a zero/empty value means "do not filter on
//	this field". Sentinels: 0.0.0.0 for IPs, 0 for ports/proto/pool_id (port 0
//	is reserved and pool_id 0 is not used by deployments).
//	Ports are presented host-order on the wire (the session struct stores them
//	network-order; the handler converts). For ICMP, inside_port/outside_port
//	carry the ICMP identifier and remote_port is 0.
//	The plugin both filters and windows: the walk resumes from start_index (a
//	session pool index) and emits at most `limit` matches, each carrying its own
//	session_index so the caller can resume the next page. limit 0 means the
//	plugin default (CGNAT_SESSION_DUMP_DEFAULT_LIMIT).
//	- inside_ip - filter on subscriber address (0.0.0.0 = any)
//	- outside_ip - filter on translated address (0.0.0.0 = any)
//	- remote_ip - filter on remote peer address (0.0.0.0 = any)
//	- inside_port - filter on subscriber port (0 = any; host-order)
//	- outside_port - filter on translated port (0 = any; host-order)
//	- remote_port - filter on remote port (0 = any; host-order)
//	- proto - filter on IP protocol, IP_PROTOCOL_* (0 = any)
//	- pool_id - filter on pool (0 = any)
//	- start_index - resume cursor; session pool index to start from (0 = begin)
//	- limit - max sessions to emit this page (0 = plugin default)
//
// OsvbngCgnatSessionDump defines message 'osvbng_cgnat_session_dump'.
type OsvbngCgnatSessionDump struct {
	InsideIP    ip_types.IP4Address `binapi:"ip4_address,name=inside_ip" json:"inside_ip,omitempty"`
	OutsideIP   ip_types.IP4Address `binapi:"ip4_address,name=outside_ip" json:"outside_ip,omitempty"`
	RemoteIP    ip_types.IP4Address `binapi:"ip4_address,name=remote_ip" json:"remote_ip,omitempty"`
	InsidePort  uint16              `binapi:"u16,name=inside_port" json:"inside_port,omitempty"`
	OutsidePort uint16              `binapi:"u16,name=outside_port" json:"outside_port,omitempty"`
	RemotePort  uint16              `binapi:"u16,name=remote_port" json:"remote_port,omitempty"`
	Proto       uint8               `binapi:"u8,name=proto" json:"proto,omitempty"`
	PoolID      uint32              `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	StartIndex  uint32              `binapi:"u32,name=start_index" json:"start_index,omitempty"`
	Limit       uint32              `binapi:"u32,name=limit" json:"limit,omitempty"`
}

func (m *OsvbngCgnatSessionDump) Reset()               { *m = OsvbngCgnatSessionDump{} }
func (*OsvbngCgnatSessionDump) GetMessageName() string { return "osvbng_cgnat_session_dump" }
func (*OsvbngCgnatSessionDump) GetCrcString() string   { return "ca7397ff" }
func (*OsvbngCgnatSessionDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatSessionDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 4 // m.InsideIP
	size += 1 * 4 // m.OutsideIP
	size += 1 * 4 // m.RemoteIP
	size += 2     // m.InsidePort
	size += 2     // m.OutsidePort
	size += 2     // m.RemotePort
	size += 1     // m.Proto
	size += 4     // m.PoolID
	size += 4     // m.StartIndex
	size += 4     // m.Limit
	return size
}
func (m *OsvbngCgnatSessionDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.InsideIP[:], 4)
	buf.EncodeBytes(m.OutsideIP[:], 4)
	buf.EncodeBytes(m.RemoteIP[:], 4)
	buf.EncodeUint16(m.InsidePort)
	buf.EncodeUint16(m.OutsidePort)
	buf.EncodeUint16(m.RemotePort)
	buf.EncodeUint8(m.Proto)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint32(m.StartIndex)
	buf.EncodeUint32(m.Limit)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatSessionDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	copy(m.InsideIP[:], buf.DecodeBytes(4))
	copy(m.OutsideIP[:], buf.DecodeBytes(4))
	copy(m.RemoteIP[:], buf.DecodeBytes(4))
	m.InsidePort = buf.DecodeUint16()
	m.OutsidePort = buf.DecodeUint16()
	m.RemotePort = buf.DecodeUint16()
	m.Proto = buf.DecodeUint8()
	m.PoolID = buf.DecodeUint32()
	m.StartIndex = buf.DecodeUint32()
	m.Limit = buf.DecodeUint32()
	return nil
}

// Set the outside VRF for a pool
//   - pool_id - pool identifier
//   - vrf_id - VRF table ID for outside routing (0 = default)
//
// OsvbngCgnatSetOutsideFib defines message 'osvbng_cgnat_set_outside_fib'.
type OsvbngCgnatSetOutsideFib struct {
	PoolID uint32 `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	VrfID  uint32 `binapi:"u32,name=vrf_id" json:"vrf_id,omitempty"`
}

func (m *OsvbngCgnatSetOutsideFib) Reset()               { *m = OsvbngCgnatSetOutsideFib{} }
func (*OsvbngCgnatSetOutsideFib) GetMessageName() string { return "osvbng_cgnat_set_outside_fib" }
func (*OsvbngCgnatSetOutsideFib) GetCrcString() string   { return "9cb97b7c" }
func (*OsvbngCgnatSetOutsideFib) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatSetOutsideFib) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	size += 4 // m.VrfID
	return size
}
func (m *OsvbngCgnatSetOutsideFib) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint32(m.VrfID)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatSetOutsideFib) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	m.VrfID = buf.DecodeUint32()
	return nil
}

// OsvbngCgnatSetOutsideFibReply defines message 'osvbng_cgnat_set_outside_fib_reply'.
type OsvbngCgnatSetOutsideFibReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *OsvbngCgnatSetOutsideFibReply) Reset() { *m = OsvbngCgnatSetOutsideFibReply{} }
func (*OsvbngCgnatSetOutsideFibReply) GetMessageName() string {
	return "osvbng_cgnat_set_outside_fib_reply"
}
func (*OsvbngCgnatSetOutsideFibReply) GetCrcString() string { return "e8d4e804" }
func (*OsvbngCgnatSetOutsideFibReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatSetOutsideFibReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *OsvbngCgnatSetOutsideFibReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatSetOutsideFibReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// OsvbngCgnatSubscriberMappingDetails defines message 'osvbng_cgnat_subscriber_mapping_details'.
type OsvbngCgnatSubscriberMappingDetails struct {
	PoolID         uint32                         `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
	SwIfIndex      interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	InsideIP       ip_types.IP4Address            `binapi:"ip4_address,name=inside_ip" json:"inside_ip,omitempty"`
	InsideVrfID    uint32                         `binapi:"u32,name=inside_vrf_id" json:"inside_vrf_id,omitempty"`
	OutsideIP      ip_types.IP4Address            `binapi:"ip4_address,name=outside_ip" json:"outside_ip,omitempty"`
	PortBlockStart uint16                         `binapi:"u16,name=port_block_start" json:"port_block_start,omitempty"`
	PortBlockEnd   uint16                         `binapi:"u16,name=port_block_end" json:"port_block_end,omitempty"`
	ActiveSessions uint32                         `binapi:"u32,name=active_sessions" json:"active_sessions,omitempty"`
}

func (m *OsvbngCgnatSubscriberMappingDetails) Reset() { *m = OsvbngCgnatSubscriberMappingDetails{} }
func (*OsvbngCgnatSubscriberMappingDetails) GetMessageName() string {
	return "osvbng_cgnat_subscriber_mapping_details"
}
func (*OsvbngCgnatSubscriberMappingDetails) GetCrcString() string { return "a8a5e91c" }
func (*OsvbngCgnatSubscriberMappingDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *OsvbngCgnatSubscriberMappingDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4     // m.PoolID
	size += 4     // m.SwIfIndex
	size += 1 * 4 // m.InsideIP
	size += 4     // m.InsideVrfID
	size += 1 * 4 // m.OutsideIP
	size += 2     // m.PortBlockStart
	size += 2     // m.PortBlockEnd
	size += 4     // m.ActiveSessions
	return size
}
func (m *OsvbngCgnatSubscriberMappingDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeBytes(m.InsideIP[:], 4)
	buf.EncodeUint32(m.InsideVrfID)
	buf.EncodeBytes(m.OutsideIP[:], 4)
	buf.EncodeUint16(m.PortBlockStart)
	buf.EncodeUint16(m.PortBlockEnd)
	buf.EncodeUint32(m.ActiveSessions)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatSubscriberMappingDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	copy(m.InsideIP[:], buf.DecodeBytes(4))
	m.InsideVrfID = buf.DecodeUint32()
	copy(m.OutsideIP[:], buf.DecodeBytes(4))
	m.PortBlockStart = buf.DecodeUint16()
	m.PortBlockEnd = buf.DecodeUint16()
	m.ActiveSessions = buf.DecodeUint32()
	return nil
}

// Dump subscriber mappings
//   - pool_id - pool to dump (~0 for all)
//
// OsvbngCgnatSubscriberMappingDump defines message 'osvbng_cgnat_subscriber_mapping_dump'.
type OsvbngCgnatSubscriberMappingDump struct {
	PoolID uint32 `binapi:"u32,name=pool_id" json:"pool_id,omitempty"`
}

func (m *OsvbngCgnatSubscriberMappingDump) Reset() { *m = OsvbngCgnatSubscriberMappingDump{} }
func (*OsvbngCgnatSubscriberMappingDump) GetMessageName() string {
	return "osvbng_cgnat_subscriber_mapping_dump"
}
func (*OsvbngCgnatSubscriberMappingDump) GetCrcString() string { return "f797ec5c" }
func (*OsvbngCgnatSubscriberMappingDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *OsvbngCgnatSubscriberMappingDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.PoolID
	return size
}
func (m *OsvbngCgnatSubscriberMappingDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.PoolID)
	return buf.Bytes(), nil
}
func (m *OsvbngCgnatSubscriberMappingDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PoolID = buf.DecodeUint32()
	return nil
}

func init() { file_osvbng_cgnat_binapi_init() }
func file_osvbng_cgnat_binapi_init() {
	api.RegisterMessage((*OsvbngCgnatAddDelBypass)(nil), "osvbng_cgnat_add_del_bypass_a1ab2cd2")
	api.RegisterMessage((*OsvbngCgnatAddDelBypassReply)(nil), "osvbng_cgnat_add_del_bypass_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatAddDelSubscriberMapping)(nil), "osvbng_cgnat_add_del_subscriber_mapping_cd65f0f6")
	api.RegisterMessage((*OsvbngCgnatAddDelSubscriberMappingReply)(nil), "osvbng_cgnat_add_del_subscriber_mapping_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatAddSubscriberMappingBulk)(nil), "osvbng_cgnat_add_subscriber_mapping_bulk_78614fbd")
	api.RegisterMessage((*OsvbngCgnatAddSubscriberMappingBulkReply)(nil), "osvbng_cgnat_add_subscriber_mapping_bulk_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatEnableOnSession)(nil), "osvbng_cgnat_enable_on_session_b7da3880")
	api.RegisterMessage((*OsvbngCgnatEnableOnSessionReply)(nil), "osvbng_cgnat_enable_on_session_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatPoolAddDel)(nil), "osvbng_cgnat_pool_add_del_22bb2f86")
	api.RegisterMessage((*OsvbngCgnatPoolAddDelInsidePrefix)(nil), "osvbng_cgnat_pool_add_del_inside_prefix_5afa7500")
	api.RegisterMessage((*OsvbngCgnatPoolAddDelInsidePrefixReply)(nil), "osvbng_cgnat_pool_add_del_inside_prefix_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatPoolAddDelOutsideAddress)(nil), "osvbng_cgnat_pool_add_del_outside_address_9142422f")
	api.RegisterMessage((*OsvbngCgnatPoolAddDelOutsideAddressReply)(nil), "osvbng_cgnat_pool_add_del_outside_address_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatPoolAddDelReply)(nil), "osvbng_cgnat_pool_add_del_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatPoolDetails)(nil), "osvbng_cgnat_pool_details_bf778eb1")
	api.RegisterMessage((*OsvbngCgnatPoolDump)(nil), "osvbng_cgnat_pool_dump_f797ec5c")
	api.RegisterMessage((*OsvbngCgnatPoolInsidePrefixDetails)(nil), "osvbng_cgnat_pool_inside_prefix_details_5b82b5f2")
	api.RegisterMessage((*OsvbngCgnatPoolInsidePrefixDump)(nil), "osvbng_cgnat_pool_inside_prefix_dump_f797ec5c")
	api.RegisterMessage((*OsvbngCgnatPoolOutsideAddressDetails)(nil), "osvbng_cgnat_pool_outside_address_details_a3f82407")
	api.RegisterMessage((*OsvbngCgnatPoolOutsideAddressDump)(nil), "osvbng_cgnat_pool_outside_address_dump_f797ec5c")
	api.RegisterMessage((*OsvbngCgnatPoolOutsideInterfaceAddDel)(nil), "osvbng_cgnat_pool_outside_interface_add_del_00ef9780")
	api.RegisterMessage((*OsvbngCgnatPoolOutsideInterfaceAddDelReply)(nil), "osvbng_cgnat_pool_outside_interface_add_del_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatPoolUpdate)(nil), "osvbng_cgnat_pool_update_311437fa")
	api.RegisterMessage((*OsvbngCgnatPoolUpdateReply)(nil), "osvbng_cgnat_pool_update_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatSessionCount)(nil), "osvbng_cgnat_session_count_51077d14")
	api.RegisterMessage((*OsvbngCgnatSessionCountReply)(nil), "osvbng_cgnat_session_count_reply_f88ba2bd")
	api.RegisterMessage((*OsvbngCgnatSessionDetails)(nil), "osvbng_cgnat_session_details_20cd8049")
	api.RegisterMessage((*OsvbngCgnatSessionDump)(nil), "osvbng_cgnat_session_dump_ca7397ff")
	api.RegisterMessage((*OsvbngCgnatSetOutsideFib)(nil), "osvbng_cgnat_set_outside_fib_9cb97b7c")
	api.RegisterMessage((*OsvbngCgnatSetOutsideFibReply)(nil), "osvbng_cgnat_set_outside_fib_reply_e8d4e804")
	api.RegisterMessage((*OsvbngCgnatSubscriberMappingDetails)(nil), "osvbng_cgnat_subscriber_mapping_details_a8a5e91c")
	api.RegisterMessage((*OsvbngCgnatSubscriberMappingDump)(nil), "osvbng_cgnat_subscriber_mapping_dump_f797ec5c")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*OsvbngCgnatAddDelBypass)(nil),
		(*OsvbngCgnatAddDelBypassReply)(nil),
		(*OsvbngCgnatAddDelSubscriberMapping)(nil),
		(*OsvbngCgnatAddDelSubscriberMappingReply)(nil),
		(*OsvbngCgnatAddSubscriberMappingBulk)(nil),
		(*OsvbngCgnatAddSubscriberMappingBulkReply)(nil),
		(*OsvbngCgnatEnableOnSession)(nil),
		(*OsvbngCgnatEnableOnSessionReply)(nil),
		(*OsvbngCgnatPoolAddDel)(nil),
		(*OsvbngCgnatPoolAddDelInsidePrefix)(nil),
		(*OsvbngCgnatPoolAddDelInsidePrefixReply)(nil),
		(*OsvbngCgnatPoolAddDelOutsideAddress)(nil),
		(*OsvbngCgnatPoolAddDelOutsideAddressReply)(nil),
		(*OsvbngCgnatPoolAddDelReply)(nil),
		(*OsvbngCgnatPoolDetails)(nil),
		(*OsvbngCgnatPoolDump)(nil),
		(*OsvbngCgnatPoolInsidePrefixDetails)(nil),
		(*OsvbngCgnatPoolInsidePrefixDump)(nil),
		(*OsvbngCgnatPoolOutsideAddressDetails)(nil),
		(*OsvbngCgnatPoolOutsideAddressDump)(nil),
		(*OsvbngCgnatPoolOutsideInterfaceAddDel)(nil),
		(*OsvbngCgnatPoolOutsideInterfaceAddDelReply)(nil),
		(*OsvbngCgnatPoolUpdate)(nil),
		(*OsvbngCgnatPoolUpdateReply)(nil),
		(*OsvbngCgnatSessionCount)(nil),
		(*OsvbngCgnatSessionCountReply)(nil),
		(*OsvbngCgnatSessionDetails)(nil),
		(*OsvbngCgnatSessionDump)(nil),
		(*OsvbngCgnatSetOutsideFib)(nil),
		(*OsvbngCgnatSetOutsideFibReply)(nil),
		(*OsvbngCgnatSubscriberMappingDetails)(nil),
		(*OsvbngCgnatSubscriberMappingDump)(nil),
	}
}
