// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package osvbng_cgnat

import (
	"context"
	"fmt"
	"io"

	memclnt "github.com/veesix-networks/osvbng/pkg/vpp/binapi/memclnt"
	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service osvbng_cgnat.
type RPCService interface {
	OsvbngCgnatAddDelBypass(ctx context.Context, in *OsvbngCgnatAddDelBypass) (*OsvbngCgnatAddDelBypassReply, error)
	OsvbngCgnatAddDelSubscriberMapping(ctx context.Context, in *OsvbngCgnatAddDelSubscriberMapping) (*OsvbngCgnatAddDelSubscriberMappingReply, error)
	OsvbngCgnatAddSubscriberMappingBulk(ctx context.Context, in *OsvbngCgnatAddSubscriberMappingBulk) (*OsvbngCgnatAddSubscriberMappingBulkReply, error)
	OsvbngCgnatEnableOnSession(ctx context.Context, in *OsvbngCgnatEnableOnSession) (*OsvbngCgnatEnableOnSessionReply, error)
	OsvbngCgnatPoolAddDel(ctx context.Context, in *OsvbngCgnatPoolAddDel) (*OsvbngCgnatPoolAddDelReply, error)
	OsvbngCgnatPoolAddDelInsidePrefix(ctx context.Context, in *OsvbngCgnatPoolAddDelInsidePrefix) (*OsvbngCgnatPoolAddDelInsidePrefixReply, error)
	OsvbngCgnatPoolAddDelOutsideAddress(ctx context.Context, in *OsvbngCgnatPoolAddDelOutsideAddress) (*OsvbngCgnatPoolAddDelOutsideAddressReply, error)
	OsvbngCgnatPoolUpdate(ctx context.Context, in *OsvbngCgnatPoolUpdate) (*OsvbngCgnatPoolUpdateReply, error)
	OsvbngCgnatSetOutsideFib(ctx context.Context, in *OsvbngCgnatSetOutsideFib) (*OsvbngCgnatSetOutsideFibReply, error)
	OsvbngCgnatSubscriberMappingDump(ctx context.Context, in *OsvbngCgnatSubscriberMappingDump) (RPCService_OsvbngCgnatSubscriberMappingDumpClient, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) OsvbngCgnatAddDelBypass(ctx context.Context, in *OsvbngCgnatAddDelBypass) (*OsvbngCgnatAddDelBypassReply, error) {
	out := new(OsvbngCgnatAddDelBypassReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatAddDelSubscriberMapping(ctx context.Context, in *OsvbngCgnatAddDelSubscriberMapping) (*OsvbngCgnatAddDelSubscriberMappingReply, error) {
	out := new(OsvbngCgnatAddDelSubscriberMappingReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatAddSubscriberMappingBulk(ctx context.Context, in *OsvbngCgnatAddSubscriberMappingBulk) (*OsvbngCgnatAddSubscriberMappingBulkReply, error) {
	out := new(OsvbngCgnatAddSubscriberMappingBulkReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatEnableOnSession(ctx context.Context, in *OsvbngCgnatEnableOnSession) (*OsvbngCgnatEnableOnSessionReply, error) {
	out := new(OsvbngCgnatEnableOnSessionReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatPoolAddDel(ctx context.Context, in *OsvbngCgnatPoolAddDel) (*OsvbngCgnatPoolAddDelReply, error) {
	out := new(OsvbngCgnatPoolAddDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatPoolAddDelInsidePrefix(ctx context.Context, in *OsvbngCgnatPoolAddDelInsidePrefix) (*OsvbngCgnatPoolAddDelInsidePrefixReply, error) {
	out := new(OsvbngCgnatPoolAddDelInsidePrefixReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatPoolAddDelOutsideAddress(ctx context.Context, in *OsvbngCgnatPoolAddDelOutsideAddress) (*OsvbngCgnatPoolAddDelOutsideAddressReply, error) {
	out := new(OsvbngCgnatPoolAddDelOutsideAddressReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatPoolUpdate(ctx context.Context, in *OsvbngCgnatPoolUpdate) (*OsvbngCgnatPoolUpdateReply, error) {
	out := new(OsvbngCgnatPoolUpdateReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatSetOutsideFib(ctx context.Context, in *OsvbngCgnatSetOutsideFib) (*OsvbngCgnatSetOutsideFibReply, error) {
	out := new(OsvbngCgnatSetOutsideFibReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngCgnatSubscriberMappingDump(ctx context.Context, in *OsvbngCgnatSubscriberMappingDump) (RPCService_OsvbngCgnatSubscriberMappingDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_OsvbngCgnatSubscriberMappingDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_OsvbngCgnatSubscriberMappingDumpClient interface {
	Recv() (*OsvbngCgnatSubscriberMappingDetails, error)
	api.Stream
}

type serviceClient_OsvbngCgnatSubscriberMappingDumpClient struct {
	api.Stream
}

func (c *serviceClient_OsvbngCgnatSubscriberMappingDumpClient) Recv() (*OsvbngCgnatSubscriberMappingDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *OsvbngCgnatSubscriberMappingDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}
