// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package openbng_accounting

import (
	"context"
	"fmt"
	"io"

	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service openbng_accounting.
type RPCService interface {
	OpenbngAcctInterfaceEnableDisable(ctx context.Context, in *OpenbngAcctInterfaceEnableDisable) (*OpenbngAcctInterfaceEnableDisableReply, error)
	OpenbngAcctSubscriberAdd(ctx context.Context, in *OpenbngAcctSubscriberAdd) (*OpenbngAcctSubscriberAddReply, error)
	OpenbngAcctSubscriberDel(ctx context.Context, in *OpenbngAcctSubscriberDel) (*OpenbngAcctSubscriberDelReply, error)
	OpenbngAcctSubscriberDump(ctx context.Context, in *OpenbngAcctSubscriberDump) (RPCService_OpenbngAcctSubscriberDumpClient, error)
	OpenbngAcctSubscriberGet(ctx context.Context, in *OpenbngAcctSubscriberGet) (*OpenbngAcctSubscriberGetReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) OpenbngAcctInterfaceEnableDisable(ctx context.Context, in *OpenbngAcctInterfaceEnableDisable) (*OpenbngAcctInterfaceEnableDisableReply, error) {
	out := new(OpenbngAcctInterfaceEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OpenbngAcctSubscriberAdd(ctx context.Context, in *OpenbngAcctSubscriberAdd) (*OpenbngAcctSubscriberAddReply, error) {
	out := new(OpenbngAcctSubscriberAddReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OpenbngAcctSubscriberDel(ctx context.Context, in *OpenbngAcctSubscriberDel) (*OpenbngAcctSubscriberDelReply, error) {
	out := new(OpenbngAcctSubscriberDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OpenbngAcctSubscriberDump(ctx context.Context, in *OpenbngAcctSubscriberDump) (RPCService_OpenbngAcctSubscriberDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_OpenbngAcctSubscriberDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_OpenbngAcctSubscriberDumpClient interface {
	Recv() (*OpenbngAcctSubscriberDetails, *OpenbngAcctSubscriberDumpReply, error)
	api.Stream
}

type serviceClient_OpenbngAcctSubscriberDumpClient struct {
	api.Stream
}

func (c *serviceClient_OpenbngAcctSubscriberDumpClient) Recv() (*OpenbngAcctSubscriberDetails, *OpenbngAcctSubscriberDumpReply, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, nil, err
	}
	switch m := msg.(type) {
	case *OpenbngAcctSubscriberDetails:
		return m, nil, nil
	case *OpenbngAcctSubscriberDumpReply:
		if err := api.RetvalToVPPApiError(m.Retval); err != nil {
			c.Stream.Close()
			return nil, m, err
		}
		err = c.Stream.Close()
		if err != nil {
			return nil, m, err
		}
		return nil, m, io.EOF
	default:
		return nil, nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) OpenbngAcctSubscriberGet(ctx context.Context, in *OpenbngAcctSubscriberGet) (*OpenbngAcctSubscriberGetReply, error) {
	out := new(OpenbngAcctSubscriberGetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
