# Copyright 2026 Veesix Networks Ltd
# Licensed under the GNU General Public License v3.0 or later.
# SPDX-License-Identifier: GPL-3.0-or-later

name: cgnat-tests

on:
  workflow_call:

jobs:
  cgnat-ipoe-pba:
    name: CGNAT IPoE PBA
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - name: Run CGNAT IPoE PBA tests
        run: |
          mkdir -p test-results
          robot --loglevel DEBUG --output test-results/output.xml --log test-results/08-cgnat-ipoe-pba-log.html --report NONE tests/08-cgnat-ipoe-pba/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cgnat-ipoe-pba-test-results
          path: test-results/
          retention-days: 14

  cgnat-ha-ipoe-pba:
    name: CGNAT HA IPoE PBA
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - name: Run CGNAT HA IPoE PBA tests
        run: |
          mkdir -p test-results
          robot --loglevel DEBUG --output test-results/output.xml --log test-results/12-cgnat-ha-ipoe-pba-log.html --report NONE tests/12-cgnat-ha-ipoe-pba/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cgnat-ha-ipoe-pba-test-results
          path: test-results/
          retention-days: 14

  cgnat-pppoe-pba:
    name: CGNAT PPPoE PBA
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - name: Run CGNAT PPPoE PBA tests
        run: |
          mkdir -p test-results
          robot --loglevel DEBUG --output test-results/output.xml --log test-results/10-cgnat-pppoe-pba-log.html --report NONE tests/10-cgnat-pppoe-pba/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cgnat-pppoe-pba-test-results
          path: test-results/
          retention-days: 14

  cgnat-ha-pppoe-pba:
    name: CGNAT HA PPPoE PBA
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - name: Run CGNAT HA PPPoE PBA tests
        run: |
          mkdir -p test-results
          robot --loglevel DEBUG --output test-results/output.xml --log test-results/13-cgnat-ha-pppoe-pba-log.html --report NONE tests/13-cgnat-ha-pppoe-pba/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cgnat-ha-pppoe-pba-test-results
          path: test-results/
          retention-days: 14
