# Copyright 2026 Veesix Networks Ltd
# Licensed under the GNU General Public License v3.0 or later.
# SPDX-License-Identifier: GPL-3.0-or-later

name: ipoe-linux-client-tests

on:
  workflow_call:

jobs:
  ipoe-linux-client:
    name: IPoE Linux Client (${{ matrix.subscriber }})
    runs-on: self-hosted
    timeout-minutes: 25
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        subscriber: [alpine, debian, ubuntu]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-setup
        with:
          topology: tests/18-ipoe-linux-client/18-ipoe-linux-client.clab.yml

      - name: Pull bngtester image
        env:
          SUBSCRIBER: ${{ matrix.subscriber }}
        run: docker pull "veesixnetworks/bngtester:${SUBSCRIBER}-latest"

      - name: Run IPoE linux client tests
        env:
          SUBSCRIBER: ${{ matrix.subscriber }}
        run: |
          mkdir -p test-results
          robot --loglevel DEBUG --variable "subscriber-image:veesixnetworks/bngtester:${{ matrix.subscriber }}-latest" --output test-results/output.xml --log test-results/18-ipoe-linux-client-${SUBSCRIBER}-log.html --report NONE tests/18-ipoe-linux-client/

      - uses: ./.github/actions/test-cleanup
        if: always()
        with:
          topology: tests/18-ipoe-linux-client/18-ipoe-linux-client.clab.yml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ipoe-linux-client-${{ matrix.subscriber }}-test-results
          path: test-results/
          retention-days: 14
